Repository FreshRSS/FreshRSS, pull requests merged in 2018-03, with the labels that each got.

#1805 Add tooltips on share configuration buttons
  app/i18n/cz/conf.php
  app/i18n/de/conf.php
  app/i18n/en/conf.php
  app/i18n/es/conf.php
  app/i18n/fr/conf.php
  app/i18n/he/conf.php
  app/i18n/it/conf.php
  app/i18n/kr/conf.php
  app/i18n/nl/conf.php
  app/i18n/pt-br/conf.php
  app/i18n/ru/conf.php
  app/i18n/tr/conf.php
  app/i18n/zh-cn/conf.php
  app/views/configure/sharing.phtml
Labels: UI :art:

#1808 Improve translating tools
  cli/i18n/I18nFile.php
Labels: I18n :earth_africa:

#1809 Fix bug when using double authentication
  app/Models/Auth.php
Labels: Security :shield:

#1814 Fix documentation links
  README.fr.md
  README.md
Labels: Documentation :books:

#1818 Add new tools to manipulate translations
  cli/i18n/I18nData.php
  cli/i18n/I18nFile.php
  cli/manipulate.translation.php
Labels: I18n :earth_africa:

#1810 FreshRSS 1.10.1
  .dockerignore
  CHANGELOG.md
  CREDITS.md
  Docker/Dockerfile
  Docker/FreshRSS.Apache.conf
  Docker/README.md
  README.fr.md
  README.md
  app/Controllers/entryController.php
  app/Controllers/feedController.php
  app/FreshRSS.php
  app/Models/Auth.php
  app/Models/EntryDAO.php
  app/Models/Feed.php
  app/Models/FeedDAO.php
  app/i18n/cz/conf.php
  app/i18n/de/conf.php
  app/i18n/en/conf.php
  app/i18n/es/conf.php
  app/i18n/fr/conf.php
  app/i18n/he/conf.php
  app/i18n/it/conf.php
  app/i18n/kr/conf.php
  app/i18n/nl/conf.php
  app/i18n/pt-br/conf.php
  app/i18n/ru/conf.php
  app/i18n/tr/conf.php
  app/i18n/zh-cn/conf.php
  app/shares.php
  app/views/configure/sharing.phtml
  cli/README.md
  cli/i18n/I18nData.php
  cli/i18n/I18nFile.php
  cli/manipulate.translation.php
  cli/prepare.php
  constants.php
  docs/en/admins/02_Installation.md
  docs/en/users/07_Frequently_Asked_Questions.md
  docs/fr/users/01_Installation.md
  docs/fr/users/07_Frequently_Asked_Questions.md
  lib/Minz/Request.php
  p/api/greader.php
Labels: Important :fire:

#1823 Improve user queries
  app/i18n/cz/conf.php
  app/i18n/de/conf.php
  app/i18n/en/conf.php
  app/i18n/es/conf.php
  app/i18n/fr/conf.php
  app/i18n/he/conf.php
  app/i18n/it/conf.php
  app/i18n/kr/conf.php
  app/i18n/nl/conf.php
  app/i18n/pt-br/conf.php
  app/i18n/ru/conf.php
  app/i18n/tr/conf.php
  app/i18n/zh-cn/conf.php
  app/views/configure/queries.phtml
Labels: I18n :earth_africa:

#1832 Minor docs
  cli/README.md
  config.default.php
Labels: Documentation :books:

#1829 Improve i18n tools
  cli/i18n/I18nData.php
  cli/i18n/I18nFile.php
  cli/i18n/I18nFileInterface.php
  cli/i18n/I18nIgnoreFile.php
  cli/manipulate.translation.php
Labels: I18n :earth_africa:

#1834 Add configuration documentation
  docs/en/img/users/configuration.article.icons.png
  docs/en/img/users/configuration.navigation.button.png
  docs/en/img/users/configuration.sharing.png
  docs/en/users/05_Configuration.md
Labels: Documentation :books:

#1828 Light Boolean search implementation
  app/Controllers/entryController.php
  app/Controllers/indexController.php
  app/Models/BooleanSearch.php
  app/Models/EntryDAO.php
  app/Models/EntryDAOSQLite.php
  app/Models/UserQuery.php
  docs/en/users/03_Main_view.md
  docs/fr/users/03_Main_view.md
  p/api/greader.php
Labels: Search :mag:

#1833 SVG version of FreshRSS logo + text
  docs/img/FreshRSS-logo-font.svg
  docs/img/FreshRSS-logo.svg
Labels: UI :art:
