Repository FreshRSS/FreshRSS, pull requests merged in 2018-11, with the labels that each got.

#2110 [i18n] Add the Occitan locale
  app/i18n/cz/gen.php
  app/i18n/de/gen.php
  app/i18n/en/gen.php
  app/i18n/es/gen.php
  app/i18n/fr/gen.php
  app/i18n/he/gen.php
  app/i18n/it/gen.php
  app/i18n/kr/gen.php
  app/i18n/nl/gen.php
  app/i18n/oc/admin.php
  app/i18n/oc/conf.php
  app/i18n/oc/feedback.php
  app/i18n/oc/gen.php
  app/i18n/oc/index.php
  app/i18n/oc/install.php
  app/i18n/oc/sub.php
  app/i18n/pt-br/gen.php
  app/i18n/ru/gen.php
  app/i18n/tr/gen.php
  app/i18n/zh-cn/gen.php
  cli/i18n/ignore/oc.php
Labels: I18n :earth_africa:

#2114 [i18n] Missing string in Occitan locale
  app/i18n/oc/index.php
Labels: I18n :earth_africa:

#2116 [docs] Bookmarklet
  docs/en/users/04_Subscriptions.md
  docs/fr/users/04_Subscriptions.md
Labels: Documentation :books:

#2093 Tweaks for Vienna RSS
  app/Models/BooleanSearch.php
  app/Models/EntryDAO.php
  app/Models/Feed.php
  app/Models/Search.php
  lib/lib_rss.php
  p/api/greader.php
Labels: API :handshake:, Important :fire:

#2112 Note stating manually adding custom subscription services removed in FF 63
  docs/en/users/04_Subscriptions.md
Labels: Documentation :books:

#2120 API encoding tuning
  app/Models/Feed.php
  lib/lib_rss.php
  p/api/greader.php
Labels: API :handshake:

#2108 Improve long dropdown menu lists
  app/views/helpers/index/normal/entry_bottom.phtml
  p/themes/base-theme/template.css
Labels: UI :art:

#2122 Login tweaks
  p/themes/Swage/swage.css
  p/themes/Swage/swage.scss
  p/themes/base-theme/template.css
Labels: UI :art:

#2135 Strip embedded SVG images for now
  lib/lib_rss.php
Labels: SimplePie :cake:

#2136 Manual update to SimplePie 1.5.2
  lib/SimplePie/SimplePie.php
  lib/SimplePie/SimplePie/Author.php
  lib/SimplePie/SimplePie/Cache/MySQL.php
  lib/SimplePie/SimplePie/Cache/Redis.php
  lib/SimplePie/SimplePie/Caption.php
  lib/SimplePie/SimplePie/Content/Type/Sniffer.php
  lib/SimplePie/SimplePie/Copyright.php
  lib/SimplePie/SimplePie/Credit.php
  lib/SimplePie/SimplePie/Decode/HTML/Entities.php
  lib/SimplePie/SimplePie/Enclosure.php
  lib/SimplePie/SimplePie/File.php
  lib/SimplePie/SimplePie/HTTP/Parser.php
  lib/SimplePie/SimplePie/IRI.php
  lib/SimplePie/SimplePie/Item.php
  lib/SimplePie/SimplePie/Locator.php
  lib/SimplePie/SimplePie/Misc.php
  lib/SimplePie/SimplePie/Net/IPv6.php
  lib/SimplePie/SimplePie/Parse/Date.php
  lib/SimplePie/SimplePie/Parser.php
  lib/SimplePie/SimplePie/Rating.php
  lib/SimplePie/SimplePie/Restriction.php
  lib/SimplePie/SimplePie/Sanitize.php
  lib/SimplePie/SimplePie/Source.php
  lib/SimplePie/SimplePie/XML/Declaration/Parser.php
  lib/SimplePie/SimplePie/gzdecode.php
Labels: SimplePie :cake:

#1767 Add shortcuts for focusing next and previous without opening articles.
  app/i18n/en/conf.php
  app/views/configure/shortcut.phtml
  app/views/helpers/javascript_vars.phtml
  config-user.default.php
  p/scripts/main.js
Labels: UI :art:

#2140 [fix] Finishing touches for next/previous without focus
  app/i18n/cz/conf.php
  app/i18n/de/conf.php
  app/i18n/en/conf.php
  app/i18n/es/conf.php
  app/i18n/fr/conf.php
  app/i18n/he/conf.php
  app/i18n/it/conf.php
  app/i18n/kr/conf.php
  app/i18n/nl/conf.php
  app/i18n/oc/conf.php
  app/i18n/pt-br/conf.php
  app/i18n/ru/conf.php
  app/i18n/tr/conf.php
  app/i18n/zh-cn/conf.php
  app/views/configure/shortcut.phtml
  p/scripts/main.js
Labels: UI :art:

#2142 [docs] Add note about specific user for webcron
  docs/en/users/03_Main_view.md
  docs/fr/users/03_Main_view.md
Labels: Documentation :books:

#2141 [i18n] Update missing string for Occitan
  app/i18n/oc/sub.php
Labels: I18n :earth_africa:

#2145 [i18n] Missing strings for Occitan locale
  app/i18n/oc/admin.php
  app/i18n/oc/conf.php
Labels: I18n :earth_africa:

#2151 Update Docker README.md for Nginx reverse proxy configuration
  Docker/README.md
Labels: Documentation :books:

#2156 [i18n] Add `conf.shortcut.skip_next_article` and `conf.shortcut.skip_…
  app/i18n/cz/conf.php
  app/i18n/de/conf.php
  app/i18n/es/conf.php
  app/i18n/fr/conf.php
  app/i18n/he/conf.php
  app/i18n/it/conf.php
  app/i18n/kr/conf.php
  app/i18n/nl/conf.php
  app/i18n/oc/conf.php
  app/i18n/pt-br/conf.php
  app/i18n/ru/conf.php
  app/i18n/tr/conf.php
  app/i18n/zh-cn/conf.php
Labels: I18n :earth_africa:

#2157 Minz: Fix HTML injections
  app/views/error/index.phtml
  lib/Minz/ActionException.php
  lib/Minz/ControllerNotExistException.php
Labels: Security :shield:
