Repository FreshRSS/FreshRSS, pull requests merged in 2018-02, with the labels that each got.

#1764 Option to hide nav_entries
  app/Controllers/configureController.php
  app/Models/ConfigurationSetter.php
  app/i18n/cz/conf.php
  app/i18n/de/conf.php
  app/i18n/en/conf.php
  app/i18n/es/conf.php
  app/i18n/fr/conf.php
  app/i18n/he/conf.php
  app/i18n/it/conf.php
  app/i18n/kr/conf.php
  app/i18n/nl/conf.php
  app/i18n/pt-br/conf.php
  app/i18n/ru/conf.php
  app/i18n/tr/conf.php
  app/i18n/zh-cn/conf.php
  app/views/configure/display.phtml
  app/views/index/normal.phtml
  config-user.default.php
Labels: UI

#1792 Fix Dutch typos
  app/i18n/nl/sub.php
Labels: I18n :earth_africa:

#1794 Fix MySQL minimal requirement
  docs/en/admins/02_Installation.md
  docs/fr/users/01_Installation.md
Labels: Documentation :books:

#1800 Fix API bug with EasyRSS
  p/api/greader.php
Labels: Important :fire:

#1798 Add a section in the FAQ about changing a password
  docs/en/users/07_Frequently_Asked_Questions.md
  docs/fr/users/07_Frequently_Asked_Questions.md
Labels: Documentation :books:
