Repository FreshRSS/FreshRSS, pull requests merged in 2019-09, with the labels that each got.

#2519 [i18n] Occitan update + improvement
  app/i18n/oc/conf.php
  app/i18n/oc/gen.php
  app/i18n/oc/user.php
Labels: I18n :earth_africa:

#2526 API Reeder compatibility
  p/api/greader.php
Labels: API :handshake:, Security :shield:

#2530 Redirect connected users accessing registration page
  app/Controllers/authController.php
Labels: Security :shield:

#2531 Hide the admin checkbox if user is not admin
  app/views/user/profile.phtml
Labels: UI :art:

#2533 Explicit Traefik 1.7
  Docker/README.md
Labels: Documentation :books:, Important :fire:

#2539 Optimize dynamic favicon for HiDPI screens
  p/scripts/main.js
Labels: UI :art:

#2540 Document Reeder compatibility
  CHANGELOG.md
  README.fr.md
  README.md
  docs/en/users/06_Fever_API.md
  docs/en/users/06_Mobile_access.md
  docs/fr/users/06_Fever_API.md
  docs/fr/users/06_Mobile_access.md
Labels: API :handshake:, Documentation :books:

#2545 Quick fix: API PDO visibility bug
  p/api/greader.php
Labels: Critical :skull_and_crossbones:

#2546 Quick fix: forgotten PDO values
  app/Models/EntryDAO.php
Labels: Critical :skull_and_crossbones:
