Repository FreshRSS/FreshRSS, pull requests merged in 2019-12, with the labels that each got.

#2590 Translate docs with po4a
  cli/translation-update.sh
  docs/en/contributing.md
  docs/en/developers/01_First_steps.md
  docs/en/developers/02_Github.md
  docs/en/developers/03_Backend/05_Extensions.md
  docs/en/developers/05_Release_new_version.md
  docs/en/index.md
  docs/en/users/02_First_steps.md
  docs/en/users/03_Main_view.md
  docs/en/users/04_Subscriptions.md
  docs/en/users/05_Configuration.md
  docs/en/users/06_Fever_API.md
  docs/en/users/06_Mobile_access.md
  docs/en/users/07_Frequently_Asked_Questions.md
  docs/fr/contributing.md
  docs/fr/developers/01_First_steps.md
  docs/fr/developers/02_Github.md
  docs/fr/developers/03_Backend/02_Minz.md
  docs/fr/developers/03_Backend/04_Changing_source_code.md
  docs/fr/developers/03_Backend/05_Extensions.md
  docs/fr/developers/04_Frontend/01_View_files.md
  docs/fr/developers/04_Frontend/02_Design.md
  docs/fr/developers/05_Release_new_version.md
  docs/fr/index.md
  docs/fr/users/02_First_steps.md
  docs/fr/users/03_Main_view.md
  docs/fr/users/04_Subscriptions.md
  docs/fr/users/05_Configuration.md
  docs/fr/users/06_Fever_API.md
  docs/fr/users/06_Mobile_access.md
  docs/fr/users/07_Frequently_Asked_Questions.md
  docs/i18n/freshrss.fr.po
  docs/i18n/templates/freshrss.pot
  docs/po4a.conf
Labels: Documentation :books:, I18n :earth_africa:

#2685 Fix doc links
  README.fr.md
  README.md
  cli/README.md
Labels: Documentation :books:

#2687 Update navigation on empty feeds
  p/scripts/main.js
Labels: Shortcuts

#2702 Manual update to SimplePie 1.5.3
  lib/SimplePie/SimplePie.php
  lib/SimplePie/SimplePie/Locator.php
  lib/SimplePie/SimplePie/Parse/Date.php
Labels: SimplePie :cake:

#2704 extend hooks
  app/Controllers/feedController.php
  lib/Minz/ExtensionManager.php
Labels: Extension :electric_plug:

#2708 tec: Allow to change CSP header from controllers
  app/Controllers/indexController.php
  app/Controllers/statsController.php
  app/FreshRSS.php
  lib/Minz/ActionController.php
  lib/Minz/Dispatcher.php
Labels: Extension :electric_plug:, Security :shield:

#2730 Update zh-cn (i18n)
  app/i18n/zh-cn/admin.php
  app/i18n/zh-cn/conf.php
  app/i18n/zh-cn/feedback.php
  app/i18n/zh-cn/gen.php
  app/i18n/zh-cn/index.php
  app/i18n/zh-cn/install.php
  app/i18n/zh-cn/sub.php
  app/i18n/zh-cn/user.php
  cli/i18n/ignore/zh-cn.php
Labels: I18n :earth_africa:

#2727 Fix labels dropdown not scrollable after a while
  app/views/helpers/index/normal/entry_bottom.phtml
  p/themes/base-theme/template.css
Labels: UI :art:

#2735 Fix PostgreSQL install
  lib/lib_install.php
Labels: Important :fire:
