Repository FreshRSS/FreshRSS, pull requests merged in 2019-11, with the labels that each got.

#2621 API 64-bit ID as string
  p/api/greader.php
Labels: API :handshake:, Important :fire:

#2628 Correction in the line 38
  docs/en/admins/07_LinuxUpdate.md
Labels: Documentation :books:

#2634 Fix favorite display for "current" articles
  p/themes/Ansum/_list-view.scss
  p/themes/Ansum/ansum.css
  p/themes/Flat/flat.css
  p/themes/Mapco/_list-view.scss
  p/themes/Mapco/mapco.css
  p/themes/Origine-compact/origine-compact.css
  p/themes/Origine/origine.css
  p/themes/Pafat/pafat.css
  p/themes/Swage/swage.css
  p/themes/Swage/swage.scss
Labels: UI :art:

#2630 Cookie same-site
  Docker/README.md
  p/.htaccess
Labels: Security :shield:

#2635 Fix database autocreate at install
  Docker/README.md
  app/Models/FeedDAO.php
  app/install.php
  cli/do-install.php
  lib/Minz/ModelPdo.php
  lib/lib_install.php
Labels: Important :fire:

#2633 FreshRSS 1.15.1
  CHANGELOG.md
  Docker/README.md
  app/Controllers/updateController.php
  app/Controllers/userController.php
  app/Models/CategoryDAO.php
  app/Models/DatabaseDAO.php
  app/Models/DatabaseDAOPGSQL.php
  app/Models/FeedDAO.php
  app/Models/UserDAO.php
  app/SQL/install.sql.mysql.php
  app/SQL/install.sql.pgsql.php
  app/SQL/install.sql.sqlite.php
  app/install.php
  cli/do-install.php
  config.default.php
  constants.php
  data/.gitignore
  docs/en/admins/07_LinuxUpdate.md
  lib/Minz/ModelPdo.php
  lib/lib_install.php
  opml.default.xml
  p/.htaccess
  p/api/greader.php
  p/themes/Ansum/_list-view.scss
  p/themes/Ansum/ansum.css
  p/themes/Flat/flat.css
  p/themes/Mapco/_list-view.scss
  p/themes/Mapco/mapco.css
  p/themes/Origine-compact/origine-compact.css
  p/themes/Origine/origine.css
  p/themes/Pafat/pafat.css
  p/themes/Swage/swage.css
  p/themes/Swage/swage.scss
Labels: Important :fire:

#2646 Fix CLI bug regarding an empty user
  cli/_cli.php
  cli/user-info.php
  lib/Minz/ModelPdo.php
Labels: Critical :skull_and_crossbones:

#2648 Fix CLI install for SQLite
  cli/do-install.php
Labels: Important :fire:

#2655 FreshRSS 1.15.2
  CHANGELOG.md
  app/Controllers/configureController.php
  app/Models/DatabaseDAO.php
  app/Models/DatabaseDAOPGSQL.php
  app/Models/DatabaseDAOSQLite.php
  app/Models/EntryDAO.php
  app/layout/aside_configure.phtml
  app/layout/header.phtml
  app/views/configure/integration.phtml
  cli/_cli.php
  cli/do-install.php
  cli/user-info.php
  constants.php
  docs/en/users/07_Frequently_Asked_Questions.md
  lib/Minz/ModelPdo.php
  lib/lib_rss.php
Labels: Important :fire:

#2656 Automatic mostly-right RTL with dir="auto"
  app/views/helpers/index/normal/entry_header.phtml
  app/views/index/normal.phtml
  app/views/index/reader.phtml
Labels: UI :art:

#2665 Fix link to installation instructions on first steps
  docs/en/users/02_First_steps.md
Labels: Documentation :books:

#2669 Fix sharing/integration
  app/views/configure/integration.phtml
Labels: Important :fire:

#2672 Fix adding categories in MySQL 5.5
  app/Models/CategoryDAO.php
Labels: Important :fire:

#2659 Do not obbey rel=self if WebSub is disabled
  app/Controllers/feedController.php
Labels: API :handshake:

#2683 FreshRSS 1.15.3
  CHANGELOG.md
  Makefile
  app/Controllers/feedController.php
  app/Controllers/userController.php
  app/Models/CategoryDAO.php
  app/Models/TagDAO.php
  app/views/configure/integration.phtml
  app/views/feed/add.phtml
  app/views/helpers/feed/update.phtml
  app/views/helpers/index/normal/entry_header.phtml
  app/views/index/normal.phtml
  app/views/index/reader.phtml
  constants.php
  docs/en/users/02_First_steps.md
  docs/en/users/07_Frequently_Asked_Questions.md
  docs/fr/users/07_Frequently_Asked_Questions.md
  lib/lib_rss.php
Labels: Important :fire:

#2690 i18n german translations
  app/i18n/de/admin.php
  app/i18n/de/conf.php
  app/i18n/de/gen.php
  app/i18n/de/index.php
  app/i18n/de/sub.php
  app/i18n/de/user.php
Labels: I18n :earth_africa:
