Repository FreshRSS/FreshRSS, pull requests merged in 2019-03, with the labels that each got.

#2264 Add reference to Readably app
  CHANGELOG.md
  README.fr.md
  README.md
  docs/en/users/06_Fever_API.md
  docs/fr/users/06_Fever_API.md
Labels: API :handshake:

#2266 Fix base theme border regression
  p/themes/base-theme/template.css
Labels: UI :art:

#2268 Improved auto load more articles
  p/scripts/main.js
Labels: UI :art:

#2269 [i18n] Minor correction for Occitan
  app/i18n/oc/index.php
Labels: I18n :earth_africa:

#2277 Update some translation strings
  app/i18n/en/conf.php
  app/i18n/fr/conf.php
Labels: I18n :earth_africa:

#2280 update zh-cn (i18n)
  app/i18n/zh-cn/admin.php
  app/i18n/zh-cn/conf.php
  app/i18n/zh-cn/feedback.php
  app/i18n/zh-cn/gen.php
  app/i18n/zh-cn/index.php
  app/i18n/zh-cn/install.php
  app/i18n/zh-cn/sub.php
  cli/i18n/ignore/zh-cn.php
Labels: I18n :earth_africa:

#2282 Add Authorization header forwarding to the Nginx configuration for Docker
  Docker/README.md
Labels: Documentation :books:

#2283 Fever remove semicolomn from author
  p/api/fever.php
Labels: API :handshake:

#2284 Minor docker doc changes
  Docker/README.md
Labels: Documentation :books:

#2285 Docker ca-certificates missing
  Docker/Dockerfile
Labels: Important :fire:

#2286 Session fix when form + HTTP auth are used
  app/Models/Auth.php
Labels: Security :shield:

#2290 Rework CSRF interaction with sessions
  app/Controllers/authController.php
  app/Controllers/userController.php
  app/FreshRSS.php
  app/Models/Auth.php
  p/scripts/main.js
Labels: Security :shield:

#2299 [i18n] Update Occitan language
  app/i18n/oc/sub.php
Labels: I18n :earth_africa:
