Repository FreshRSS/FreshRSS, pull requests merged in 2019-06, with the labels that each got.

#2406 Fix shortcut configuration page.
  app/views/configure/shortcut.phtml
Labels: UI :art:

#2409 Add Dockerfile links for PHP modules list
  docs/en/admins/02_Installation.md
  docs/fr/users/01_Installation.md
Labels: Documentation :books:

#2412 Fix API remove category
  p/api/greader.php
Labels: API :handshake:

#2413 Fix line break in table
  docs/en/admins/02_Installation.md
  docs/fr/users/01_Installation.md
Labels: Documentation :books:

#2421 Allow email as admin username
  app/install.php
Labels: Security :shield:

#2427 Add FAQ for admin section
  docs/en/admins/01_Index.md
  docs/en/admins/04_Frequently_Asked_Questions.md
Labels: Documentation :books:

#2431 Fix wrong mark-as-read maxId argument
  app/Controllers/indexController.php
  app/layout/nav_menu.phtml
  app/views/index/global.phtml
  app/views/index/normal.phtml
  app/views/index/reader.phtml
Labels: Important :fire:
