Repository FreshRSS/FreshRSS, pull requests merged in 2020-06, with the labels that each got.

#3024 Updates PHPMailer to 6.1.6
  lib/PHPMailer/PHPMailer/PHPMailer.php
  lib/PHPMailer/PHPMailer/SMTP.php
Labels: Security :shield:

#3028 Fix form layout
  p/themes/BlueLagoon/BlueLagoon.css
  p/themes/Screwdriver/screwdriver.css
Labels: UI :art:

#3022 Add language detection when the user is not logged in
  app/Controllers/authController.php
  app/FreshRSS.php
  app/views/auth/register.phtml
  lib/Minz/Request.php
  lib/Minz/Translate.php
Labels: I18n :earth_africa:

#3034 Add missing translations
  Makefile
  app/Controllers/extensionController.php
  app/i18n/cz/feedback.php
  app/i18n/de/feedback.php
  app/i18n/en/feedback.php
  app/i18n/es/feedback.php
  app/i18n/fr/feedback.php
  app/i18n/he/feedback.php
  app/i18n/it/feedback.php
  app/i18n/kr/feedback.php
  app/i18n/nl/feedback.php
  app/i18n/oc/feedback.php
  app/i18n/pt-br/feedback.php
  app/i18n/ru/feedback.php
  app/i18n/sk/feedback.php
  app/i18n/tr/feedback.php
  app/i18n/zh-cn/feedback.php
  cli/i18n/I18nData.php
  cli/manipulate.translation.php
Labels: I18n :earth_africa:

#3036 Add controls on media
  app/i18n/cz/conf.php
  app/i18n/de/conf.php
  app/i18n/en/conf.php
  app/i18n/es/conf.php
  app/i18n/fr/conf.php
  app/i18n/he/conf.php
  app/i18n/it/conf.php
  app/i18n/kr/conf.php
  app/i18n/nl/conf.php
  app/i18n/oc/conf.php
  app/i18n/pt-br/conf.php
  app/i18n/ru/conf.php
  app/i18n/sk/conf.php
  app/i18n/tr/conf.php
  app/i18n/zh-cn/conf.php
  app/views/configure/shortcut.phtml
  app/views/helpers/javascript_vars.phtml
  config-user.default.php
  p/scripts/main.js
Labels: Shortcuts, UI :art:

#3037 Fix user queries when they contain "
  app/Controllers/configureController.php
  app/views/configure/queries.phtml
Labels: Important :fire:, Search :mag:, Security :shield:, UI :art:

#3051 Fix API quickadd
  p/api/greader.php
Labels: API :handshake:

#3050 Fix inline code tag contrast in ansum.css
  CREDITS.md
  p/themes/Ansum/ansum.css
Labels: UI :art:

#3056 Add a way to disable/enable users
  app/Controllers/authController.php
  app/Controllers/userController.php
  app/actualize_script.php
  app/i18n/cz/admin.php
  app/i18n/de/admin.php
  app/i18n/en/admin.php
  app/i18n/es/admin.php
  app/i18n/fr/admin.php
  app/i18n/he/admin.php
  app/i18n/it/admin.php
  app/i18n/kr/admin.php
  app/i18n/nl/admin.php
  app/i18n/oc/admin.php
  app/i18n/pt-br/admin.php
  app/i18n/ru/admin.php
  app/i18n/sk/admin.php
  app/i18n/tr/admin.php
  app/i18n/zh-cn/admin.php
  app/install.php
  app/views/user/details.phtml
  app/views/user/manage.phtml
  cli/user-info.php
  config-user.default.php
  p/api/fever.php
  p/api/greader.php
  p/api/pshb.php
  p/themes/base-theme/template.css
  p/themes/base-theme/template.rtl.css
Labels: Security :shield:

#3063 [i18n] Update Dutch translation
  app/i18n/nl/admin.php
  app/i18n/nl/conf.php
  app/i18n/nl/feedback.php
  app/i18n/nl/gen.php
  app/i18n/nl/sub.php
Labels: I18n :earth_africa:

#3003 Add auto-registration when using http_auth
  app/Models/Auth.php
  config.default.php
  docs/en/admins/09_AccessControl.md
Labels: Security :shield:

#3061 API discard common API URL errors
  p/api/greader.php
Labels: API :handshake:

#3073 API Compatibility Reeder
  p/api/greader.php
Labels: API :handshake:

#3074 Reeder update table
  README.fr.md
  README.md
Labels: API :handshake:, Documentation :books:

#3075 FeedMe table manage feeds + fix warning addFeed
  README.fr.md
  README.md
  app/Controllers/feedController.php
Labels: API :handshake:

#3072 Change how updating a key works
  Makefile
  cli/i18n/I18nData.php
Labels: I18n :earth_africa:
