Repository FreshRSS/FreshRSS, pull requests merged in 2020-10, with the labels that each got.

#3205 Add toggle password visibility button on login form
  app/views/auth/formLogin.phtml
  p/themes/Alternative-Dark/adark.css
  p/themes/Alternative-Dark/adark.rtl.css
  p/themes/BlueLagoon/BlueLagoon.css
  p/themes/BlueLagoon/BlueLagoon.rtl.css
  p/themes/Dark/dark.css
  p/themes/Dark/dark.rtl.css
  p/themes/Flat/flat.css
  p/themes/Flat/flat.rtl.css
  p/themes/Origine-compact/origine-compact.css
  p/themes/Origine-compact/origine-compact.rtl.css
  p/themes/Origine/origine.css
  p/themes/Origine/origine.rtl.css
  p/themes/Pafat/pafat.css
  p/themes/Pafat/pafat.rtl.css
  p/themes/Screwdriver/screwdriver.css
  p/themes/Screwdriver/screwdriver.rtl.css
Labels: UI :art:

#3206 Update SimplePie (PHP8)
  lib/SimplePie/SimplePie.php
  lib/SimplePie/SimplePie/File.php
  lib/SimplePie/SimplePie/Item.php
  lib/SimplePie/SimplePie/Locator.php
  lib/SimplePie/SimplePie/Misc.php
Labels: SimplePie :cake:

#3213 Use of existing tag name via input field
  app/Controllers/tagController.php
Labels: UI :art:

#3096 Minz allow parallel sessions
  app/Controllers/authController.php
  app/Controllers/errorController.php
  app/Controllers/userController.php
  app/Models/Auth.php
  app/Models/DatabaseDAO.php
  app/actualize_script.php
  app/install.php
  cli/_cli.php
  cli/do-install.php
  lib/Minz/Error.php
  lib/Minz/Request.php
  lib/Minz/Session.php
  p/api/fever.php
  p/api/greader.php
  p/i/index.php
Labels: Security :shield:

#3222 Fix sanitize feed description
  app/Models/FeedDAO.php
  app/views/helpers/feed/update.phtml
  lib/lib_rss.php
Labels: Important :fire:, Security :shield:

#3225 Update FAQ with firewall issues.
  docs/en/users/07_Frequently_Asked_Questions.md
Labels: Documentation :books:

#3226 Docker: Use Apache remoteip
  Docker/Dockerfile
  Docker/Dockerfile-Alpine
  Docker/Dockerfile-QEMU-ARM
  Docker/FreshRSS.Apache.conf
Labels: Security :shield:

#3231 Remember sidebar position
  p/scripts/main.js
Labels: UI :art:

#3235 Docker LogFormat Alpine
  Docker/FreshRSS.Apache.conf
Labels: Important :fire:
