Repository FreshRSS/FreshRSS, pull requests merged in 2020-07, with the labels that each got.

#3077 Fixed nginx split paths config issue
  CREDITS.md
  docs/en/admins/10_ServerConfig.md
  docs/fr/users/01_Installation.md
Labels: API :handshake:, Documentation :books:

#3098 Fix HTTP Basic Auth when adding a new feed
  app/views/subscription/add.phtml
Labels: Important :fire:

#3099 Hide feed credentials when adding a new feed
  app/Models/Feed.php
Labels: Security :shield:

#3102 Dropdown menu max-height
  p/themes/base-theme/template.css
  p/themes/base-theme/template.rtl.css
Labels: UI :art:

#3081 Show feed name inside the article
  app/views/index/normal.phtml
  app/views/index/reader.phtml
  p/themes/Alternative-Dark/adark.css
  p/themes/Alternative-Dark/adark.rtl.css
  p/themes/Ansum/ansum.css
  p/themes/Ansum/ansum.rtl.css
  p/themes/BlueLagoon/BlueLagoon.css
  p/themes/BlueLagoon/BlueLagoon.rtl.css
  p/themes/Dark/dark.css
  p/themes/Dark/dark.rtl.css
  p/themes/Flat/flat.css
  p/themes/Flat/flat.rtl.css
  p/themes/Mapco/mapco.css
  p/themes/Mapco/mapco.rtl.css
  p/themes/Origine-compact/origine-compact.css
  p/themes/Origine-compact/origine-compact.rtl.css
  p/themes/Origine/origine.css
  p/themes/Origine/origine.rtl.css
  p/themes/Pafat/pafat.css
  p/themes/Pafat/pafat.rtl.css
  p/themes/Screwdriver/screwdriver.css
  p/themes/Screwdriver/screwdriver.rtl.css
  p/themes/Swage/swage.css
  p/themes/Swage/swage.rtl.css
  p/themes/base-theme/base.css
  p/themes/base-theme/base.rtl.css
  p/themes/base-theme/template.css
  p/themes/base-theme/template.rtl.css
Labels: UI :art:

#3112 US-English translation improvement
  app/i18n/en-us/index.php
Labels: I18n :earth_africa:

#3113 fix: Test setupMigrations doesn't return false
  lib/lib_install.php
Labels: Important :fire:

#3106 Add machine-readable dates in views
  app/Models/Entry.php
  app/views/helpers/index/normal/entry_bottom.phtml
  app/views/helpers/index/normal/entry_header.phtml
  app/views/index/reader.phtml
Labels: UI :art:

#3114 Add a way to disable shortcuts
  app/Controllers/configureController.php
  app/i18n/cz/gen.php
  app/i18n/de/gen.php
  app/i18n/en-us/gen.php
  app/i18n/en/gen.php
  app/i18n/es/gen.php
  app/i18n/fr/gen.php
  app/i18n/he/gen.php
  app/i18n/it/gen.php
  app/i18n/kr/gen.php
  app/i18n/nl/gen.php
  app/i18n/oc/gen.php
  app/i18n/pt-br/gen.php
  app/i18n/ru/gen.php
  app/i18n/sk/gen.php
  app/i18n/tr/gen.php
  app/i18n/zh-cn/gen.php
  app/views/configure/shortcut.phtml
  lib/lib_rss.php
Labels: UI :art:

#3115 Add tooltips on entries
  app/views/helpers/index/normal/entry_bottom.phtml
  app/views/helpers/index/normal/entry_header.phtml
Labels: UI :art:

#3124 Update doc about default configuration
  docs/en/admins/03_Installation.md
Labels: Documentation :books:

#3125 [lang] Tags management → tag management
  app/i18n/cz/sub.php
  app/i18n/de/sub.php
  app/i18n/en-us/sub.php
  app/i18n/en/sub.php
  app/i18n/es/sub.php
  app/i18n/he/sub.php
  app/i18n/it/sub.php
  app/i18n/kr/sub.php
  app/i18n/nl/sub.php
  app/i18n/oc/sub.php
  app/i18n/pt-br/sub.php
  app/i18n/ru/sub.php
  app/i18n/sk/sub.php
  app/i18n/tr/sub.php
  app/i18n/zh-cn/sub.php
  app/layout/aside_subscription.phtml
Labels: I18n :earth_africa:

#3134 i18n update for Occitan
  app/i18n/oc/admin.php
  app/i18n/oc/conf.php
  app/i18n/oc/feedback.php
  app/i18n/oc/gen.php
  app/i18n/oc/sub.php
Labels: I18n :earth_africa:
