Repository FreshRSS/FreshRSS, pull requests merged in 2020-03, with the labels that each got.

#2794 Improve login and registration pages
  app/Controllers/authController.php
  app/Controllers/userController.php
  app/Utils/passwordUtil.php
  app/i18n/cz/gen.php
  app/i18n/cz/user.php
  app/i18n/de/gen.php
  app/i18n/de/user.php
  app/i18n/en/gen.php
  app/i18n/en/user.php
  app/i18n/es/gen.php
  app/i18n/es/user.php
  app/i18n/fr/user.php
  app/i18n/he/gen.php
  app/i18n/he/user.php
  app/i18n/it/gen.php
  app/i18n/it/user.php
  app/i18n/kr/user.php
  app/i18n/nl/gen.php
  app/i18n/nl/user.php
  app/i18n/oc/gen.php
  app/i18n/oc/user.php
  app/i18n/pt-br/gen.php
  app/i18n/pt-br/user.php
  app/i18n/ru/gen.php
  app/i18n/ru/user.php
  app/i18n/sk/gen.php
  app/i18n/sk/user.php
  app/i18n/tr/gen.php
  app/i18n/tr/user.php
  app/i18n/zh-cn/user.php
  app/views/auth/formLogin.phtml
  app/views/auth/register.phtml
  p/themes/Origine/origine.css
  tests/app/Utils/passwordUtilTest.php
Labels: Security :shield:

#2821 Option to show/hide favicons
  app/layout/aside_feed.phtml
  app/views/helpers/index/normal/entry_header.phtml
  app/views/index/global.phtml
  app/views/index/reader.phtml
  app/views/subscription/index.phtml
  config-user.default.php
Labels: UI :art:

#2823 Add remaining Spanish translations
  app/i18n/es/gen.php
Labels: I18n :earth_africa:

#2811 Alternative-Dark theme
  p/themes/Alternative-Dark/adark.css
  p/themes/Alternative-Dark/icons/icon.svg
  p/themes/Alternative-Dark/loader.gif
  p/themes/Alternative-Dark/metadata.json
  p/themes/Alternative-Dark/template.css
  p/themes/Alternative-Dark/thumbs/original.png
Labels: UI :art:

#2832 Fix broken doc link
  docs/en/users/06_Mobile_access.md
Labels: Documentation :books:

#2830 Revert minor Spanish translations
  app/i18n/es/gen.php
  app/i18n/fr/gen.php
Labels: I18n :earth_africa:

#2833 Update and fix pt-br translation
  app/i18n/pt-br/admin.php
  app/i18n/pt-br/conf.php
  app/i18n/pt-br/feedback.php
  app/i18n/pt-br/gen.php
  app/i18n/pt-br/index.php
  app/i18n/pt-br/install.php
  app/i18n/pt-br/sub.php
  app/i18n/pt-br/user.php
Labels: I18n :earth_africa:

#2837 New core-extensions to allow Docker volumes for third-party extensions
  Docker/README.md
  Docker/docker-compose.yml
  constants.php
  extensions/README.md
  lib/Minz/ExtensionManager.php
  lib/core-extensions/README.md
  lib/core-extensions/Tumblr-GDPR/README.md
  lib/core-extensions/Tumblr-GDPR/extension.php
  lib/core-extensions/Tumblr-GDPR/metadata.json
  p/ext.php
Labels: Extension :electric_plug:

#2838 Add core extension for Google Groups
  config.default.php
  force-https.default.txt
  lib/core-extensions/Google-Groups/README.md
  lib/core-extensions/Google-Groups/extension.php
  lib/core-extensions/Google-Groups/metadata.json
Labels: Extension :electric_plug:

#2842 Reset scroll
  p/scripts/main.js
Labels: Important :fire:, UI :art:

#2843 Shortcut mark previous articles as read
  app/i18n/cz/conf.php
  app/i18n/de/conf.php
  app/i18n/en/conf.php
  app/i18n/es/conf.php
  app/i18n/fr/conf.php
  app/i18n/he/conf.php
  app/i18n/it/conf.php
  app/i18n/kr/conf.php
  app/i18n/nl/conf.php
  app/i18n/oc/conf.php
  app/i18n/pt-br/conf.php
  app/i18n/ru/conf.php
  app/i18n/sk/conf.php
  app/i18n/tr/conf.php
  app/i18n/zh-cn/conf.php
  app/views/configure/shortcut.phtml
  p/scripts/main.js
  p/themes/Alternative-Dark/template.css
  p/themes/base-theme/template.css
  p/themes/base-theme/template.rtl.css
Labels: Shortcuts

#2845 Loader animation while waiting for first articles
  app/layout/nav_menu.phtml
  p/themes/Alternative-Dark/template.css
  p/themes/Alternative-Dark/template.rtl.css
  p/themes/base-theme/template.css
  p/themes/base-theme/template.rtl.css
Labels: UI :art:

#2840 GReader API consistent default category
  p/api/greader.php
Labels: API :handshake:, Important :fire:

#2852 SimplePie use distint cache for force_feed
  lib/SimplePie/SimplePie.php
Labels: SimplePie :cake:

#2858 Fix wget in linux update guide
  docs/en/admins/07_LinuxUpdate.md
Labels: Documentation :books:

#2859 [doc] Include contributing.md in Jekyll
  docs/_config.yml
Labels: Documentation :books:

#2855 API return OK for an empty request
  p/api/greader.php
Labels: API :handshake:

#2863 Fix action filter when filtering on author
  app/Models/Entry.php
Labels: Important :fire:
