Repository FreshRSS/FreshRSS, pull requests merged in 2020-12, with the labels that each got.

#3273 Session compatibility PHP 7.1 and older
  lib/Minz/Session.php
Labels: Important :fire:

#3275 Prevent login before extra.js is loaded
  app/views/auth/formLogin.phtml
  p/scripts/extra.js
Labels: Security :shield:

#3285 Fix user queries with labels
  app/Controllers/configureController.php
  app/Models/UserQuery.php
  app/i18n/cz/conf.php
  app/i18n/de/conf.php
  app/i18n/en-us/conf.php
  app/i18n/en/conf.php
  app/i18n/es/conf.php
  app/i18n/fr/conf.php
  app/i18n/he/conf.php
  app/i18n/it/conf.php
  app/i18n/kr/conf.php
  app/i18n/nl/conf.php
  app/i18n/oc/conf.php
  app/i18n/pl/conf.php
  app/i18n/pt-br/conf.php
  app/i18n/ru/conf.php
  app/i18n/sk/conf.php
  app/i18n/tr/conf.php
  app/i18n/zh-cn/conf.php
Labels: I18n :earth_africa:, Search :mag:

#3289 Layout add subscription
  app/views/subscription/add.phtml
Labels: UI :art:

#3170 bump default logout from 30 days to 3 months
  app/Controllers/configureController.php
  app/Models/Auth.php
  config.default.php
Labels: Security :shield:

#3292 Fix tag management translation
  app/Controllers/tagController.php
  app/i18n/cz/feedback.php
  app/i18n/de/feedback.php
  app/i18n/en-us/feedback.php
  app/i18n/en/feedback.php
  app/i18n/es/feedback.php
  app/i18n/fr/feedback.php
  app/i18n/he/feedback.php
  app/i18n/it/feedback.php
  app/i18n/kr/feedback.php
  app/i18n/nl/feedback.php
  app/i18n/oc/feedback.php
  app/i18n/pl/feedback.php
  app/i18n/pt-br/feedback.php
  app/i18n/ru/feedback.php
  app/i18n/sk/feedback.php
  app/i18n/tr/feedback.php
  app/i18n/zh-cn/feedback.php
Labels: I18n :earth_africa:, UI :art:

#3288 SimplePie Strip HTML comments
  lib/lib_rss.php
Labels: SimplePie :cake:

#3287 Auto-renew login cookie
  app/Models/Auth.php
Labels: Security :shield:

#3297 Add a file for each PDO class
  app/Models/DatabaseDAO.php
  docs/en/developers/Minz/migrations.md
  lib/Minz/ModelPdo.php
  lib/Minz/Pdo.php
  lib/Minz/PdoMysql.php
  lib/Minz/PdoPgsql.php
  lib/Minz/PdoSqlite.php
Labels: Important :fire:

#3298 Add a file for each Auth class
  app/Models/Auth.php
  app/Models/FormAuth.php
Labels: Important :fire:

#3301 Add a file for each PDO class
  app/Models/DatabaseDAO.php
  docs/en/developers/Minz/migrations.md
  lib/Minz/ModelPdo.php
  lib/Minz/Pdo.php
  lib/Minz/PdoMysql.php
  lib/Minz/PdoPgsql.php
  lib/Minz/PdoSqlite.php
Labels: Important :fire:

#3305 Fix bugs in anomymous mode
  app/FreshRSS.php
  p/scripts/extra.js
  p/scripts/main.js
Labels: Important :fire:, Security :shield:

#3307 Update 03_Main_view.md
  docs/en/users/03_Main_view.md
Labels: Documentation :books:
