Repository FreshRSS/FreshRSS, pull requests merged in 2021-06, with the labels that each got.

#3655 Fix navigation JS error
  p/scripts/main.js
Labels: UI :art:

#3656 Fix user creation form redirection
  app/Controllers/userController.php
  app/views/user/manage.phtml
Labels: Important :fire:

#3635 Update 08_FeedUpdates.md
  docs/en/admins/08_FeedUpdates.md
Labels: Documentation :books:

#3666 Drop PHP5 and IE11
  .travis.yml
  CHANGELOG.md
  Docker/Dockerfile-Oldest
  README.fr.md
  README.md
  constants.php
  docs/en/admins/02_Prerequisites.md
  docs/fr/users/01_Installation.md
Labels: Important :fire:

#3668 [i18n] German: flip alter/neuer typo
  app/i18n/de/sub.php
Labels: I18n :earth_africa:

#3669 Git 2.21 compatiblity
  app/Controllers/updateController.php
Labels: Important :fire:

#3678 3672 notification icon
  p/scripts/main.js
  p/themes/icons/favicon-256-padding.png
Labels: UI :art:

#3681 [docs] Fix typo in server requirements
  docs/en/admins/02_Prerequisites.md
Labels: Documentation :books:
