Repository FreshRSS/FreshRSS, pull requests merged in 2021-12, with the labels that each got.

#4008 Improved German translation of "related tags"
  app/i18n/de/conf.php
  app/i18n/de/index.php
Labels: I18n :earth_africa:

#4011 Manual update SimplePie
  lib/SimplePie/SimplePie.php
  lib/SimplePie/SimplePie/Enclosure.php
  lib/SimplePie/SimplePie/HTTP/Parser.php
  lib/SimplePie/SimplePie/Registry.php
Labels: SimplePie :cake:

#4019 Fix some PHPstan errors
  app/Models/FeedDAO.php
  app/Models/Tag.php
  app/Models/UserDAO.php
  p/ext.php
Labels: Important :fire:

#4014 Fix: double main tags
  app/install.php
  app/layout/layout.phtml
  app/views/auth/formLogin.phtml
  app/views/auth/index.phtml
  app/views/auth/register.phtml
  app/views/configure/archiving.phtml
  app/views/configure/display.phtml
  app/views/configure/integration.phtml
  app/views/configure/queries.phtml
  app/views/configure/reading.phtml
  app/views/configure/shortcut.phtml
  app/views/configure/system.phtml
  app/views/error/index.phtml
  app/views/extension/index.phtml
  app/views/feed/add.phtml
  app/views/importExport/index.phtml
  app/views/index/about.phtml
  app/views/index/logs.phtml
  app/views/index/tos.phtml
  app/views/stats/idle.phtml
  app/views/stats/index.phtml
  app/views/stats/repartition.phtml
  app/views/subscription/add.phtml
  app/views/subscription/bookmarklet.phtml
  app/views/subscription/index.phtml
  app/views/tag/index.phtml
  app/views/update/apply.phtml
  app/views/update/checkInstall.phtml
  app/views/update/index.phtml
  app/views/user/details.phtml
  app/views/user/manage.phtml
  app/views/user/profile.phtml
  app/views/user/validateEmail.phtml
Labels: UI :art:

#4013 Add preventDefault to keydown event handler
  p/scripts/main.js
Labels: Shortcuts

#4027 Update polish translation.
  app/i18n/pl/admin.php
  app/i18n/pl/conf.php
  app/i18n/pl/feedback.php
  app/i18n/pl/gen.php
  app/i18n/pl/index.php
  app/i18n/pl/sub.php
  app/i18n/pl/user.php
Labels: I18n :earth_africa:

#4026 Updated japanese translation
  app/i18n/ja/admin.php
  app/i18n/ja/conf.php
  app/i18n/ja/gen.php
  app/i18n/ja/install.php
  app/i18n/ja/sub.php
Labels: I18n :earth_africa:

#4025 Fix: search in mobile view
  p/themes/Origine/origine.css
  p/themes/Origine/origine.rtl.css
  p/themes/Pafat/pafat.css
  p/themes/Pafat/pafat.rtl.css
  p/themes/base-theme/template.css
  p/themes/base-theme/template.rtl.css
Labels: Theme

#4015 Fix reader view header
  app/i18n/cz/gen.php
  app/i18n/de/conf.php
  app/i18n/de/gen.php
  app/i18n/en-us/gen.php
  app/i18n/en/gen.php
  app/i18n/es/gen.php
  app/i18n/fr/gen.php
  app/i18n/he/gen.php
  app/i18n/it/gen.php
  app/i18n/ja/gen.php
  app/i18n/ko/gen.php
  app/i18n/nl/gen.php
  app/i18n/oc/gen.php
  app/i18n/pl/gen.php
  app/i18n/pt-br/gen.php
  app/i18n/ru/gen.php
  app/i18n/sk/gen.php
  app/i18n/tr/gen.php
  app/i18n/zh-cn/gen.php
  app/views/configure/display.phtml
  app/views/index/reader.phtml
Labels: UI :art:

#4030 Updated translation
  app/i18n/sk/conf.php
Labels: I18n :earth_africa:

#4031 Updated translation
  app/i18n/sk/feedback.php
Labels: I18n :earth_africa:

#4032 Updated translation
  app/i18n/sk/gen.php
Labels: I18n :earth_africa:

#4033 Updated translation
  app/i18n/sk/index.php
Labels: I18n :earth_africa:

#4034 Updated translation
  app/i18n/sk/install.php
Labels: I18n :earth_africa:

#4035 Updated translation
  app/i18n/sk/sub.php
Labels: I18n :earth_africa:

#4036 Updated translation
  app/i18n/sk/user.php
Labels: I18n :earth_africa:

#4038 Updated translation
  app/i18n/sk/admin.php
Labels: I18n :earth_africa:

#4041 Fix: Swage theme
  p/themes/Swage/swage.css
  p/themes/Swage/swage.rtl.css
  p/themes/Swage/swage.scss
Labels: Theme

#4042 Fix: global view does not show "no articles to show" alert
  app/views/index/global.phtml
  p/scripts/main.js
  p/themes/base-theme/template.css
  p/themes/base-theme/template.rtl.css
Labels: UI :art:

#4040 Fix: Anonym. mode: do not show "Add new feeds" link in No-Article-Alert
  app/views/index/normal.phtml
  app/views/index/reader.phtml
Labels: UI :art:, Security :shield:

#4043 fix global view template
  app/views/index/global.phtml
Labels: UI :art:, Security :shield:

#4049 Update 02_First_steps.md
  docs/en/users/02_First_steps.md
Labels: Documentation :books:

#4056 fever: fix warning of unset array key
  p/api/fever.php
Labels: API :handshake:

#4074 Docker fix missing .htaccess
  Docker/FreshRSS.Apache.conf
  p/.htaccess
  p/themes/.htaccess
Labels: Docker

#4072 Improved: Manual: username+pw for demo login
  docs/en/index.md
Labels: Documentation :books:

#4079 Correct cron example
  docs/en/admins/08_FeedUpdates.md
Labels: Documentation :books:

#4081 Fix invalid user
  app/Controllers/authController.php
Labels: Security :shield:

#4083 Improved manual: User Management/User registration
  docs/en/admins/01_Index.md
  docs/en/admins/12_User_management.md
  docs/en/admins/13_Default_user.md
Labels: Documentation :books:

#4084 fix: incorrect translations
  app/i18n/zh-cn/sub.php
Labels: I18n :earth_africa:

#4082 Fix: loading wheel
  app/views/helpers/pagination.phtml
  p/scripts/global_view.js
Labels: UI :art:

#4058 Search on article IDs
  app/Models/EntryDAO.php
  app/Models/Search.php
  docs/en/users/03_Main_view.md
  docs/fr/users/03_Main_view.md
Labels: Search :mag:

#4090 Fix extensions_enabled
  lib/Minz/Configuration.php
Labels: System care

#4092 Fix article filter
  app/Models/Entry.php
Labels: Article filter

#4098 Check data URI
  p/scripts/main.js
Labels: UI :art:

#4085 Fix: Thumbnails alt text overflow
  p/themes/base-theme/template.css
  p/themes/base-theme/template.rtl.css
Labels: UI :art:

#4067 Improvement: No break in labels in mobile view
  p/themes/base-theme/template.css
  p/themes/base-theme/template.rtl.css
Labels: UI :art:

#4065 Fixed: "My labels" in aside navigation when it is empty
  app/layout/aside_feed.phtml
Labels: UI :art:

#4061 Improve: Aside slider: close slider when click on the outside of slider
  app/layout/aside_configure.phtml
  app/layout/aside_feed.phtml
  app/layout/aside_subscription.phtml
  p/themes/base-theme/template.css
  p/themes/base-theme/template.rtl.css
Labels: UI :art:

#4055 fixed: Left navigation with long category names
  p/themes/Ansum/_sidebar.scss
  p/themes/Ansum/ansum.css
  p/themes/Ansum/ansum.rtl.css
  p/themes/Mapco/_sidebar.scss
  p/themes/Mapco/mapco.css
  p/themes/Mapco/mapco.rtl.css
  p/themes/base-theme/template.css
  p/themes/base-theme/template.rtl.css
Labels: UI :art:

#4059 Improved: global view: Box title link (themes Origine and Origine compact)
  p/themes/Origine-compact/origine-compact.css
  p/themes/Origine-compact/origine-compact.rtl.css
  p/themes/Origine/origine.css
  p/themes/Origine/origine.rtl.css
Labels: Theme

#4099 Improved: install.php code quality
  app/install.php
Labels: System care
