Repository FreshRSS/FreshRSS, pull requests merged in 2022-06, with the labels that each got.

#4399 Fix update URL
  app/Controllers/updateController.php
Labels: Update action :floppy_disk:

#4378 New search engine
  app/Models/BooleanSearch.php
  app/Models/Entry.php
  app/Models/EntryDAO.php
  app/Models/EntryDAOPGSQL.php
  app/Models/EntryDAOSQLite.php
  app/Models/UserConfiguration.php
  app/Models/UserQuery.php
  app/layout/nav_menu.phtml
  docs/en/users/03_Main_view.md
  docs/fr/users/03_Main_view.md
  p/api/fever.php
  tests/app/Models/SearchTest.php
Labels: Important :fire:, Search :mag:

#4409 Added themeing to missing "category" -icon
  p/themes/Dark-pink/pinkdark.css
  p/themes/Dark-pink/pinkdark.rtl.css
Labels: Theme

#4413 README.md - GReader Redate not required for Reeder 5
  CREDITS.md
  README.md
Labels: Documentation :books:, API :handshake:

#4414 Fix Minz link
  README.fr.md
  README.md
  app/i18n/cz/index.php
  app/i18n/de/index.php
  app/i18n/en-us/index.php
  app/i18n/en/index.php
  app/i18n/es/index.php
  app/i18n/fr/index.php
  app/i18n/he/index.php
  app/i18n/it/index.php
  app/i18n/ja/index.php
  app/i18n/ko/index.php
  app/i18n/nl/index.php
  app/i18n/oc/index.php
  app/i18n/pl/index.php
  app/i18n/pt-br/index.php
  app/i18n/ru/index.php
  app/i18n/sk/index.php
  app/i18n/tr/index.php
  app/i18n/zh-cn/index.php
Labels: Documentation :books:

#4417 Docker entrypoint fix buffering
  Docker/entrypoint.sh
Labels: Docker

#4418 Document fixes & tests
  docs/en/developers/02_First_steps.md
Labels: Documentation :books:

#4419 Update all test dependencies
  .github/workflows/tests.yml
  .typos.toml
  CHANGELOG-old.md
  CHANGELOG.md
  Makefile
  app/Models/BooleanSearch.php
  app/Models/DatabaseDAO.php
  app/Models/Feed.php
  app/Models/FeedDAO.php
  app/Models/TagDAO.php
  composer.json
  composer.lock
  docs/en/users/05_Configuration.md
  lib/lib_opml.php
  lib/lib_rss.php
  p/api/fever.php
  p/scripts/statsWithChartjs.js
  p/themes/BlueLagoon/BlueLagoon.css
  p/themes/BlueLagoon/BlueLagoon.rtl.css
  package-lock.json
  package.json
Labels: System care

#4420 Docker Alpine updates
  Docker/Dockerfile-Alpine
  Docker/Dockerfile-Newest
  Docker/Dockerfile-Oldest
Labels: Docker

#4421 Initial support for PHP 8.2
  app/Models/View.php
  app/layout/layout.phtml
  app/layout/simple.phtml
  lib/Minz/ActionException.php
Labels: System care

#4424 Minor dev composer update
  composer.lock
Labels: System care
