Repository FreshRSS/FreshRSS, pull requests merged in 2022-09, with the labels that each got.

#4576 fix 4574
  p/themes/base-theme/template.css
  p/themes/base-theme/template.rtl.css
Labels: UI :art:

#4575 Improved: Flat theme
  p/themes/Flat/flat.css
  p/themes/Flat/flat.rtl.css
  p/themes/Flat/icons/all.svg
  p/themes/Flat/icons/close.svg
  p/themes/Flat/icons/configure.svg
  p/themes/Flat/icons/disabled-light.svg
  p/themes/Flat/icons/down.svg
  p/themes/Flat/icons/icon.svg
  p/themes/Flat/icons/key.svg
  p/themes/Flat/icons/next.svg
  p/themes/Flat/icons/prev.svg
  p/themes/Flat/icons/up.svg
Labels: Theme

#4577 Update zh-cn translation
  CREDITS.md
  app/i18n/zh-cn/sub.php
Labels: I18n :earth_africa:

#4581 fix: space key opens empty tab
  p/scripts/main.js
Labels: Shortcuts

#4566 remove margin-top: 2rem; in Swage
  p/themes/Swage/swage.css
  p/themes/Swage/swage.css.map
  p/themes/Swage/swage.rtl.css
  p/themes/Swage/swage.scss
Labels: Theme

#4532 Shortcuts: auto-load at least a few articles
  p/scripts/main.js
Labels: UI :art:, Shortcuts

#4565 SimplePie fix base
  lib/SimplePie/SimplePie/Item.php
Labels: SimplePie :cake:

#4583 API protection limit content size
  app/Models/Entry.php
Labels: API :handshake:

#4587 Use body text color for input in Alternative Dark theme to improve contrast
  p/themes/Alternative-Dark/adark.css
  p/themes/Alternative-Dark/adark.rtl.css
Labels: Theme, UX

#4592 Add freshrss network when creating container
  Makefile
Labels: Docker

#4593 Fix auto-loading of more articles
  p/scripts/main.js
Labels: UI :art:

#3859 Update README.md
  README.md
Labels: Documentation :books:, API :handshake:

#3860 Update README.fr.md
  README.fr.md
Labels: Documentation :books:, API :handshake:

#4595 Add Fluent Reader Lite
  README.fr.md
  README.md
  docs/en/developers/06_Fever_API.md
  docs/en/developers/06_GoogleReader_API.md
  docs/fr/users/06_Fever_API.md
  docs/fr/users/06_Mobile_access.md
Labels: Documentation :books:, API :handshake:

#4606 Improved: eslint + stylelint: Do not scan extension folder
  .eslintignore
  .stylelintignore
Labels: System care

#4619 Improved: (S)CSS .disable removed
  p/themes/Alternative-Dark/adark.css
  p/themes/Alternative-Dark/adark.rtl.css
  p/themes/Ansum/_sidebar.scss
  p/themes/Ansum/ansum.css
  p/themes/Ansum/ansum.rtl.css
  p/themes/BlueLagoon/BlueLagoon.css
  p/themes/BlueLagoon/BlueLagoon.rtl.css
  p/themes/Dark/dark.css
  p/themes/Dark/dark.rtl.css
  p/themes/Flat/flat.css
  p/themes/Flat/flat.rtl.css
  p/themes/Mapco/_sidebar.scss
  p/themes/Mapco/mapco.css
  p/themes/Mapco/mapco.rtl.css
  p/themes/Nord/nord.css
  p/themes/Nord/nord.rtl.css
  p/themes/Origine-compact/origine-compact.css
  p/themes/Origine-compact/origine-compact.rtl.css
  p/themes/Origine/origine.css
  p/themes/Origine/origine.rtl.css
  p/themes/Pafat/pafat.css
  p/themes/Pafat/pafat.rtl.css
  p/themes/Screwdriver/screwdriver.css
  p/themes/Screwdriver/screwdriver.rtl.css
  p/themes/Swage/swage.css
  p/themes/Swage/swage.rtl.css
  p/themes/Swage/swage.scss
  p/themes/base-theme/base.css
  p/themes/base-theme/base.rtl.css
Labels: UI :art:, System care

#4596 improved: CSS: clean .horizontal-list
  p/themes/Alternative-Dark/adark.css
  p/themes/Alternative-Dark/adark.rtl.css
  p/themes/Ansum/_components.scss
  p/themes/Ansum/_configuration.scss
  p/themes/Ansum/_stats.scss
  p/themes/Ansum/ansum.css
  p/themes/Ansum/ansum.rtl.css
  p/themes/BlueLagoon/BlueLagoon.css
  p/themes/BlueLagoon/BlueLagoon.rtl.css
  p/themes/Dark/dark.css
  p/themes/Dark/dark.rtl.css
  p/themes/Flat/flat.css
  p/themes/Flat/flat.rtl.css
  p/themes/Mapco/_components.scss
  p/themes/Mapco/_stats.scss
  p/themes/Mapco/mapco.css
  p/themes/Mapco/mapco.rtl.css
  p/themes/Nord/nord.css
  p/themes/Nord/nord.rtl.css
  p/themes/Origine-compact/origine-compact.css
  p/themes/Origine-compact/origine-compact.rtl.css
  p/themes/Origine/origine.css
  p/themes/Origine/origine.rtl.css
  p/themes/Pafat/pafat.css
  p/themes/Pafat/pafat.rtl.css
  p/themes/Screwdriver/screwdriver.css
  p/themes/Screwdriver/screwdriver.rtl.css
  p/themes/Swage/swage.css
  p/themes/Swage/swage.rtl.css
  p/themes/Swage/swage.scss
  p/themes/base-theme/base.css
  p/themes/base-theme/base.rtl.css
  p/themes/base-theme/template.css
  p/themes/base-theme/template.rtl.css
Labels: UI :art:, System care

#4620 Force default user before rendering login page
  app/Controllers/authController.php
Labels: UI :art:, Security :shield:

#4621 Fix login page when user does not exist
  app/Controllers/authController.php
Labels: UI :art:, Security :shield:

#4594 Improved: Cleanup CSS of ".log"
  app/views/index/logs.phtml
  p/themes/Alternative-Dark/adark.css
  p/themes/Alternative-Dark/adark.rtl.css
  p/themes/Ansum/_logs.scss
  p/themes/Ansum/ansum.css
  p/themes/Ansum/ansum.rtl.css
  p/themes/BlueLagoon/BlueLagoon.css
  p/themes/BlueLagoon/BlueLagoon.rtl.css
  p/themes/Dark/dark.css
  p/themes/Dark/dark.rtl.css
  p/themes/Flat/flat.css
  p/themes/Flat/flat.rtl.css
  p/themes/Mapco/_logs.scss
  p/themes/Mapco/mapco.css
  p/themes/Mapco/mapco.rtl.css
  p/themes/Nord/nord.css
  p/themes/Nord/nord.rtl.css
  p/themes/Origine-compact/origine-compact.css
  p/themes/Origine-compact/origine-compact.rtl.css
  p/themes/Origine/origine.css
  p/themes/Origine/origine.rtl.css
  p/themes/Pafat/pafat.css
  p/themes/Pafat/pafat.rtl.css
  p/themes/Screwdriver/screwdriver.css
  p/themes/Screwdriver/screwdriver.rtl.css
  p/themes/Swage/swage.css
  p/themes/Swage/swage.rtl.css
  p/themes/Swage/swage.scss
  p/themes/base-theme/base.css
  p/themes/base-theme/base.rtl.css
  p/themes/base-theme/template.css
  p/themes/base-theme/template.rtl.css
Labels: UI :art:

#4617 Improved: Mouse title on empty feeds
  app/layout/aside_feed.phtml
  app/views/index/global.phtml
  app/views/stats/idle.phtml
  app/views/subscription/index.phtml
Labels: UI :art:

#4625 Improved: Feed configuration: Archiving
  app/views/helpers/feed/update.phtml
Labels: UI :art:

#4629 Fix opcache bug during Web update
  app/Controllers/updateController.php
Labels: Update action :floppy_disk:

#4632 Minor update list of API clients
  README.fr.md
  README.md
Labels: Documentation :books:, API :handshake:

#4643 fixed: Safari issue with .stick dropdowns
  p/themes/Alternative-Dark/adark.css
  p/themes/Alternative-Dark/adark.rtl.css
  p/themes/Ansum/_sidebar.scss
  p/themes/Ansum/ansum.css
  p/themes/Ansum/ansum.rtl.css
  p/themes/BlueLagoon/BlueLagoon.css
  p/themes/BlueLagoon/BlueLagoon.rtl.css
  p/themes/Dark/dark.css
  p/themes/Dark/dark.rtl.css
  p/themes/Flat/flat.css
  p/themes/Flat/flat.rtl.css
  p/themes/Mapco/_sidebar.scss
  p/themes/Mapco/mapco.css
  p/themes/Mapco/mapco.rtl.css
  p/themes/Nord/nord.css
  p/themes/Nord/nord.rtl.css
  p/themes/Origine-compact/origine-compact.css
  p/themes/Origine-compact/origine-compact.rtl.css
  p/themes/Origine/origine.css
  p/themes/Origine/origine.rtl.css
  p/themes/Pafat/pafat.css
  p/themes/Pafat/pafat.rtl.css
  p/themes/Screwdriver/screwdriver.css
  p/themes/Screwdriver/screwdriver.rtl.css
  p/themes/Swage/swage.css
  p/themes/Swage/swage.rtl.css
  p/themes/Swage/swage.scss
  p/themes/base-theme/base.css
  p/themes/base-theme/base.rtl.css
  p/themes/base-theme/template.css
  p/themes/base-theme/template.rtl.css
Labels: UI :art:

#4648 fix: unread icons in Ansum/Mapco theme
  p/themes/Ansum/icons/unread.svg
  p/themes/Mapco/icons/unread.svg
Labels: Theme

#4636 Improved: Origine compact inherit from origine
  p/themes/Origine-compact/metadata.json
  p/themes/Origine-compact/origine-compact.css
  p/themes/Origine-compact/origine-compact.rtl.css
  p/themes/Origine/origine.css
  p/themes/Origine/origine.rtl.css
Labels: Theme

#4641 Improved: template.css (colors)
  p/themes/Ansum/ansum.css
  p/themes/Ansum/ansum.rtl.css
  p/themes/Ansum/ansum.scss
  p/themes/BlueLagoon/BlueLagoon.css
  p/themes/BlueLagoon/BlueLagoon.rtl.css
  p/themes/Flat/flat.css
  p/themes/Flat/flat.rtl.css
  p/themes/Mapco/mapco.css
  p/themes/Mapco/mapco.rtl.css
  p/themes/Mapco/mapco.scss
  p/themes/Origine/origine.css
  p/themes/Origine/origine.rtl.css
  p/themes/Screwdriver/screwdriver.css
  p/themes/Screwdriver/screwdriver.rtl.css
  p/themes/Swage/swage.css
  p/themes/Swage/swage.rtl.css
  p/themes/Swage/swage.scss
  p/themes/base-theme/base.css
  p/themes/base-theme/base.rtl.css
  p/themes/base-theme/template.css
  p/themes/base-theme/template.rtl.css
Labels: UI :art:, Theme, System care

#4635 Improved: Alternative Dark theme
  p/themes/Alternative-Dark/adark.css
  p/themes/Alternative-Dark/adark.rtl.css
Labels: Theme

#4652 Improved: Reader view: Mark article as read while scrolling
  p/scripts/main.js
Labels: UX

#4653 Improved: reader view with framed articles
  p/themes/Origine/origine.css
  p/themes/Origine/origine.rtl.css
Labels: Theme, View

#4644 Rename template.css
  app/install.php
  docs/en/developers/04_Frontend/02_Design.md
  p/themes/Alternative-Dark/metadata.json
  p/themes/Ansum/metadata.json
  p/themes/BlueLagoon/metadata.json
  p/themes/Dark-pink/metadata.json
  p/themes/Dark/metadata.json
  p/themes/Flat/metadata.json
  p/themes/Mapco/metadata.json
  p/themes/Nord/metadata.json
  p/themes/Origine-compact/metadata.json
  p/themes/Origine/metadata.json
  p/themes/Pafat/metadata.json
  p/themes/Screwdriver/metadata.json
  p/themes/Swage/metadata.json
  p/themes/base-theme/frss.css
  p/themes/base-theme/frss.rtl.css
  p/themes/base-theme/metadata.json
Labels: UI :art:

#4663 Improved: reader view with framed articles (all themes)
  p/themes/Alternative-Dark/adark.css
  p/themes/Alternative-Dark/adark.rtl.css
  p/themes/Ansum/_reader-view.scss
  p/themes/Ansum/ansum.css
  p/themes/Ansum/ansum.rtl.css
  p/themes/BlueLagoon/BlueLagoon.css
  p/themes/BlueLagoon/BlueLagoon.rtl.css
  p/themes/Dark/dark.css
  p/themes/Dark/dark.rtl.css
  p/themes/Flat/flat.css
  p/themes/Flat/flat.rtl.css
  p/themes/Mapco/_reader-view.scss
  p/themes/Mapco/mapco.css
  p/themes/Mapco/mapco.rtl.css
  p/themes/Nord/nord.css
  p/themes/Nord/nord.rtl.css
  p/themes/Origine/origine.css
  p/themes/Origine/origine.rtl.css
  p/themes/Pafat/pafat.css
  p/themes/Pafat/pafat.rtl.css
  p/themes/Screwdriver/screwdriver.css
  p/themes/Screwdriver/screwdriver.rtl.css
  p/themes/Swage/swage.css
  p/themes/Swage/swage.rtl.css
  p/themes/Swage/swage.scss
  p/themes/base-theme/base.css
  p/themes/base-theme/base.rtl.css
  p/themes/base-theme/frss.css
  p/themes/base-theme/frss.rtl.css
Labels: UI :art:, Theme
