Repository FreshRSS/FreshRSS, pull requests merged in 2022-07, with the labels that each got.

#4400 Added Nord based theme
  p/themes/Nord/LICENSE
  p/themes/Nord/README.md
  p/themes/Nord/icons/help.svg
  p/themes/Nord/icons/link.svg
  p/themes/Nord/icons/read.svg
  p/themes/Nord/icons/share.svg
  p/themes/Nord/icons/starred.svg
  p/themes/Nord/icons/unread.svg
  p/themes/Nord/loader.gif
  p/themes/Nord/metadata.json
  p/themes/Nord/nord.css
  p/themes/Nord/nord.rtl.css
  p/themes/Nord/thumbs/original.png
Labels: Theme

#4434 Update config.default.php
  config.default.php
Labels: Documentation :books:

#4450 Fix grammar on en & en-us About pages
  CREDITS.md
  app/i18n/en-us/index.php
  app/i18n/en/index.php
Labels: I18n :earth_africa:

#4451 Fix #4447: Nord theme
  p/themes/Alternative-Dark/adark.css
  p/themes/Alternative-Dark/adark.rtl.css
  p/themes/Ansum/ansum.css
  p/themes/Ansum/ansum.rtl.css
  p/themes/Ansum/ansum.scss
  p/themes/BlueLagoon/BlueLagoon.css
  p/themes/BlueLagoon/BlueLagoon.rtl.css
  p/themes/Dark/dark.css
  p/themes/Dark/dark.rtl.css
  p/themes/Flat/flat.css
  p/themes/Flat/flat.rtl.css
  p/themes/Mapco/mapco.css
  p/themes/Mapco/mapco.rtl.css
  p/themes/Mapco/mapco.scss
  p/themes/Origine-compact/origine-compact.css
  p/themes/Origine-compact/origine-compact.rtl.css
  p/themes/Origine/origine.css
  p/themes/Origine/origine.rtl.css
  p/themes/Pafat/pafat.css
  p/themes/Pafat/pafat.rtl.css
  p/themes/Screwdriver/screwdriver.css
  p/themes/Screwdriver/screwdriver.rtl.css
  p/themes/Swage/swage.css
  p/themes/Swage/swage.rtl.css
  p/themes/Swage/swage.scss
  p/themes/base-theme/template.css
  p/themes/base-theme/template.rtl.css
Labels: Theme

#4101 Improved: Article header
  app/Controllers/configureController.php
  app/Models/ConfigurationSetter.php
  app/Models/UserConfiguration.php
  app/i18n/cz/conf.php
  app/i18n/de/conf.php
  app/i18n/en-us/conf.php
  app/i18n/en/conf.php
  app/i18n/es/conf.php
  app/i18n/fr/conf.php
  app/i18n/he/conf.php
  app/i18n/it/conf.php
  app/i18n/ja/conf.php
  app/i18n/ko/conf.php
  app/i18n/nl/conf.php
  app/i18n/oc/conf.php
  app/i18n/pl/conf.php
  app/i18n/pt-br/conf.php
  app/i18n/ru/conf.php
  app/i18n/sk/conf.php
  app/i18n/tr/conf.php
  app/i18n/zh-cn/conf.php
  app/views/configure/reading.phtml
  app/views/configure/system.phtml
  app/views/index/normal.phtml
  app/views/index/reader.phtml
  config-user.default.php
  p/scripts/config.js
  p/scripts/main.js
  p/themes/Ansum/_layout.scss
  p/themes/Mapco/_layout.scss
  p/themes/Origine/origine.css
  p/themes/Origine/origine.rtl.css
  p/themes/base-theme/template.css
  p/themes/base-theme/template.rtl.css
Labels: UI :art:

#4452 Fix: header height
  p/themes/Alternative-Dark/adark.css
  p/themes/Alternative-Dark/adark.rtl.css
  p/themes/Ansum/_layout.scss
  p/themes/Ansum/ansum.css
  p/themes/Ansum/ansum.rtl.css
  p/themes/Dark/dark.css
  p/themes/Dark/dark.rtl.css
  p/themes/Flat/flat.css
  p/themes/Flat/flat.rtl.css
  p/themes/Mapco/_layout.scss
  p/themes/Mapco/mapco.css
  p/themes/Mapco/mapco.rtl.css
  p/themes/Nord/nord.css
  p/themes/Nord/nord.rtl.css
  p/themes/Origine-compact/origine-compact.css
  p/themes/Origine-compact/origine-compact.rtl.css
  p/themes/Origine/origine.css
  p/themes/Origine/origine.rtl.css
  p/themes/Pafat/pafat.css
  p/themes/Pafat/pafat.rtl.css
  p/themes/Screwdriver/screwdriver.css
  p/themes/Screwdriver/screwdriver.rtl.css
  p/themes/Swage/swage.css
  p/themes/Swage/swage.rtl.css
  p/themes/base-theme/template.css
  p/themes/base-theme/template.rtl.css
Labels: Theme

#4416 Fix/Improved: Slider mobile
  app/views/configure/queries.phtml
  app/views/extension/index.phtml
  app/views/helpers/category/update.phtml
  app/views/helpers/configure/query.phtml
  app/views/helpers/feed/update.phtml
  app/views/index/normal.phtml
  app/views/stats/idle.phtml
  app/views/subscription/index.phtml
  lib/Minz/Url.php
  p/scripts/extra.js
  p/themes/base-theme/template.css
  p/themes/base-theme/template.rtl.css
Labels: UI :art:

#4455 Cleanup CSS .pagination
  p/themes/Alternative-Dark/adark.css
  p/themes/Alternative-Dark/adark.rtl.css
  p/themes/Ansum/_components.scss
  p/themes/Ansum/ansum.css
  p/themes/Ansum/ansum.rtl.css
  p/themes/BlueLagoon/BlueLagoon.css
  p/themes/BlueLagoon/BlueLagoon.rtl.css
  p/themes/Dark/dark.css
  p/themes/Dark/dark.rtl.css
  p/themes/Flat/flat.css
  p/themes/Flat/flat.rtl.css
  p/themes/Mapco/_components.scss
  p/themes/Mapco/mapco.css
  p/themes/Mapco/mapco.rtl.css
  p/themes/Nord/nord.css
  p/themes/Nord/nord.rtl.css
  p/themes/Origine-compact/origine-compact.css
  p/themes/Origine-compact/origine-compact.rtl.css
  p/themes/Origine/origine.css
  p/themes/Origine/origine.rtl.css
  p/themes/Pafat/pafat.css
  p/themes/Pafat/pafat.rtl.css
  p/themes/Screwdriver/screwdriver.css
  p/themes/Screwdriver/screwdriver.rtl.css
  p/themes/Swage/swage.css
  p/themes/Swage/swage.rtl.css
  p/themes/Swage/swage.scss
  p/themes/base-theme/template.css
  p/themes/base-theme/template.rtl.css
Labels: Theme

#4466 Fix the subscription tool form
  app/views/feed/add.phtml
Labels: UI :art:

#4459 delete the link style given by default
  p/themes/base-theme/template.css
  p/themes/base-theme/template.rtl.css
Labels: UI :art:

#4474 Improved: show feed errors
  app/layout/aside_feed.phtml
  app/views/subscription/index.phtml
  p/themes/base-theme/template.css
  p/themes/base-theme/template.rtl.css
Labels: UI :art:

#4472 Improved: themes
  p/themes/Alternative-Dark/adark.css
  p/themes/Alternative-Dark/adark.rtl.css
  p/themes/Dark-pink/pinkdark.css
  p/themes/Dark-pink/pinkdark.rtl.css
  p/themes/Dark/dark.css
  p/themes/Dark/dark.rtl.css
  p/themes/Mapco/_forms.scss
  p/themes/Mapco/mapco.css
  p/themes/Mapco/mapco.rtl.css
  p/themes/Pafat/pafat.css
  p/themes/Pafat/pafat.rtl.css
  p/themes/Swage/swage.css
  p/themes/Swage/swage.rtl.css
  p/themes/Swage/swage.scss
Labels: Theme

#4471 Fix: [BUG] "Hide after read" and "mark on scroll" clears the whole list feed by feed.
  p/scripts/main.js
Labels: View
