Repository FreshRSS/FreshRSS, pull requests merged in 2022-04, with the labels that each got.

#4301 SimplePie fix status_code type
  lib/SimplePie/SimplePie.php
  lib/SimplePie/SimplePie/File.php
  lib/SimplePie/SimplePie/HTTP/Parser.php
Labels: SimplePie :cake:

#4063 Add HTTP_REMOTE_USER header for auth
  app/Models/SystemConfiguration.php
  config.default.php
  docs/en/admins/09_AccessControl.md
  lib/lib_rss.php
Labels: Security :shield:

#4297 Improved: slider
  app/views/configure/queries.phtml
  app/views/extension/index.phtml
  app/views/helpers/feed/update.phtml
  app/views/index/normal.phtml
  app/views/stats/idle.phtml
  app/views/subscription/index.phtml
  p/themes/base-theme/template.css
  p/themes/base-theme/template.rtl.css
Labels: UI :art:

#4293 Improved: dropdown close area
  app/layout/aside_feed.phtml
  app/layout/header.phtml
  app/layout/nav_menu.phtml
  app/views/helpers/index/normal/entry_bottom.phtml
  p/scripts/main.js
  p/themes/Ansum/_mobile.scss
  p/themes/Ansum/ansum.css
  p/themes/Ansum/ansum.rtl.css
  p/themes/Mapco/_mobile.scss
  p/themes/Mapco/mapco.css
  p/themes/Mapco/mapco.rtl.css
  p/themes/base-theme/template.css
  p/themes/base-theme/template.rtl.css
Labels: UI :art:

#4290 Docs: improve backup section
  docs/en/admins/05_Backup.md
Labels: Documentation :books:

#4315 Fix: wrong i18n key in integration.phtml
  app/views/configure/integration.phtml
Labels: I18n :earth_africa:

#4306 Fix: article footer + improve: labeling
  app/layout/aside_feed.phtml
  app/views/helpers/index/normal/entry_bottom.phtml
  p/scripts/main.js
  p/themes/Ansum/_components.scss
  p/themes/Ansum/_layout.scss
  p/themes/Ansum/ansum.css
  p/themes/Ansum/ansum.rtl.css
  p/themes/Flat/flat.css
  p/themes/Flat/flat.rtl.css
  p/themes/Mapco/_components.scss
  p/themes/Mapco/_layout.scss
  p/themes/Mapco/mapco.css
  p/themes/Mapco/mapco.rtl.css
  p/themes/Origine/origine.css
  p/themes/Origine/origine.rtl.css
  p/themes/Pafat/pafat.css
  p/themes/Pafat/pafat.rtl.css
  p/themes/base-theme/template.css
  p/themes/base-theme/template.rtl.css
  p/themes/icons/label.svg
Labels: UI :art:

#4312 Fix max-registrations-input data-leave-validation
  app/views/configure/system.phtml
Labels: UI :art:

#4292 Improved: Slider: Close area = grey background
  app/views/extension/index.phtml
  app/views/subscription/index.phtml
  p/themes/base-theme/template.css
  p/themes/base-theme/template.rtl.css
Labels: UI :art:

#4321 Fix navigator.share insertRule
  p/scripts/main.js
Labels: UI :art:

#4320 Update Docker readme
  Docker/.env
  Docker/.gitignore
  Docker/README.md
  Docker/docker-compose.yml
  Docker/freshrss/docker-compose-db.yml
  Docker/freshrss/docker-compose-development.yml
  Docker/freshrss/docker-compose-local.yml
  Docker/freshrss/docker-compose-proxy.yml
  Docker/freshrss/docker-compose.yml
  Docker/freshrss/example.env
  Docker/freshrss/traefik/tls.yml
Labels: Documentation :books:, Docker

#4325 Update 06_Mobile_access.md
  docs/en/users/06_Mobile_access.md
Labels: Documentation :books:

#4327 Fix: show password with touch
  p/scripts/extra.js
Labels: UI :art:

#4332 fixed a text error in zh-cn
  app/i18n/zh-cn/feedback.php
Labels: I18n :earth_africa:

#4331 fix depending results after changing value of "entry->isRead"
  app/Controllers/feedController.php
Labels: Extension :electric_plug:

#4311 Created new theme: Dark pink
  CREDITS.md
  p/themes/Dark-pink/README.md
  p/themes/Dark-pink/loader.gif
  p/themes/Dark-pink/metadata.json
  p/themes/Dark-pink/pinkdark.css
  p/themes/Dark-pink/pinkdark.rtl.css
  p/themes/Dark-pink/thumbs/original.png
Labels: Theme

#4333 add category automatically
  app/views/subscription/add.phtml
  app/views/subscription/index.phtml
Labels: UI :art:

#4337 Translated and modified part of the zh-cn version
  app/i18n/zh-cn/admin.php
  app/i18n/zh-cn/conf.php
  app/i18n/zh-cn/feedback.php
  app/i18n/zh-cn/gen.php
  app/i18n/zh-cn/install.php
  app/i18n/zh-cn/user.php
Labels: I18n :earth_africa:
