Repository FreshRSS/FreshRSS, pull requests merged in 2022-03, with the labels that each got.

#4247 Cloud Providers page
  docs/en/admins/01_Index.md
  docs/en/admins/14_CloudProviders.md
Labels: Documentation :books:

#4254 Better PWA color
  p/themes/manifest.json
Labels: Theme

#4262 News+ use GitHub links
  CHANGELOG.md
  README.fr.md
  README.md
  docs/en/developers/06_GoogleReader_API.md
  docs/fr/users/06_Mobile_access.md
  docs/i18n/freshrss.fr.po
  docs/i18n/templates/freshrss.pot
Labels: Documentation :books:, API :handshake:

#4263 Faster $simplePie->get_items()
  app/Models/Feed.php
Labels: SimplePie :cake:

#4266 Documentation: added information about code checks
  docs/en/developers/02_First_steps.md
Labels: Documentation :books:

#4181 Improved: Extension manager: new style
  app/views/extension/index.phtml
  app/views/helpers/extension/configure.phtml
  app/views/helpers/extension/details.phtml
  p/themes/Alternative-Dark/adark.css
  p/themes/Alternative-Dark/adark.rtl.css
  p/themes/Alternative-Dark/icons/disabled-light.svg
  p/themes/Dark/dark.css
  p/themes/Dark/dark.rtl.css
  p/themes/Flat/flat.css
  p/themes/Flat/flat.rtl.css
  p/themes/Flat/icons/disabled-light.svg
  p/themes/Screwdriver/screwdriver.css
  p/themes/Screwdriver/screwdriver.rtl.css
  p/themes/Swage/icons/disabled-light.svg
  p/themes/Swage/swage.css
  p/themes/Swage/swage.rtl.css
  p/themes/base-theme/template.css
  p/themes/base-theme/template.rtl.css
  p/themes/icons/disabled.svg
  p/themes/icons/enabled.svg
Labels: UI :art:, Theme

#4238 Improved: Show URL button
  app/i18n/cz/gen.php
  app/i18n/de/gen.php
  app/i18n/en-us/gen.php
  app/i18n/en/gen.php
  app/i18n/es/gen.php
  app/i18n/fr/gen.php
  app/i18n/he/gen.php
  app/i18n/it/gen.php
  app/i18n/ja/gen.php
  app/i18n/ko/gen.php
  app/i18n/nl/gen.php
  app/i18n/oc/gen.php
  app/i18n/pl/gen.php
  app/i18n/pt-br/gen.php
  app/i18n/ru/gen.php
  app/i18n/sk/gen.php
  app/i18n/tr/gen.php
  app/i18n/zh-cn/gen.php
  app/views/feed/add.phtml
  app/views/helpers/feed/update.phtml
  app/views/subscription/add.phtml
  p/scripts/extra.js
Labels: UI :art:

#4269 Improved: Sharing/Integration configuration
  app/Models/Share.php
  app/i18n/cz/conf.php
  app/i18n/de/conf.php
  app/i18n/en-us/conf.php
  app/i18n/en/conf.php
  app/i18n/es/conf.php
  app/i18n/fr/conf.php
  app/i18n/he/conf.php
  app/i18n/it/conf.php
  app/i18n/ja/conf.php
  app/i18n/ko/conf.php
  app/i18n/nl/conf.php
  app/i18n/oc/conf.php
  app/i18n/pl/conf.php
  app/i18n/pt-br/conf.php
  app/i18n/ru/conf.php
  app/i18n/sk/conf.php
  app/i18n/tr/conf.php
  app/i18n/zh-cn/conf.php
  app/shares.php
  app/views/configure/integration.phtml
  app/views/helpers/index/normal/entry_bottom.phtml
  docs/en/index.md
  docs/en/users/08_sharing_services.md
  p/scripts/draggable.js
  p/scripts/integration.js
  p/themes/base-theme/template.css
  p/themes/base-theme/template.rtl.css
Labels: UI :art:, Documentation :books:, View

#4273 fix: log
  app/Models/Themes.php
  app/views/index/logs.phtml
  p/themes/Alternative-Dark/adark.css
  p/themes/Alternative-Dark/adark.rtl.css
  p/themes/BlueLagoon/BlueLagoon.css
  p/themes/BlueLagoon/BlueLagoon.rtl.css
  p/themes/Dark/dark.css
  p/themes/Dark/dark.rtl.css
  p/themes/Flat/flat.css
  p/themes/Flat/flat.rtl.css
  p/themes/Mapco/_components.scss
  p/themes/Mapco/mapco.css
  p/themes/Mapco/mapco.rtl.css
  p/themes/Origine-compact/origine-compact.css
  p/themes/Origine-compact/origine-compact.rtl.css
  p/themes/Origine/origine.css
  p/themes/Origine/origine.rtl.css
  p/themes/Pafat/pafat.css
  p/themes/Pafat/pafat.rtl.css
  p/themes/Screwdriver/screwdriver.css
  p/themes/Screwdriver/screwdriver.rtl.css
  p/themes/Swage/swage.css
  p/themes/Swage/swage.rtl.css
  p/themes/Swage/swage.scss
  p/themes/base-theme/template.css
  p/themes/base-theme/template.rtl.css
  p/themes/icons/debug.svg
Labels: UI :art:

#4285 fix: Deprecated sharing service text information: link to docs
  app/i18n/cz/conf.php
  app/i18n/de/conf.php
  app/i18n/en-us/conf.php
  app/i18n/en/conf.php
  app/i18n/es/conf.php
  app/i18n/fr/conf.php
  app/i18n/he/conf.php
  app/i18n/it/conf.php
  app/i18n/ja/conf.php
  app/i18n/ko/conf.php
  app/i18n/nl/conf.php
  app/i18n/oc/conf.php
  app/i18n/pl/conf.php
  app/i18n/pt-br/conf.php
  app/i18n/ru/conf.php
  app/i18n/sk/conf.php
  app/i18n/tr/conf.php
  app/i18n/zh-cn/conf.php
Labels: Documentation :books:

#4281 Docs: information about extensions
  docs/en/admins/01_Index.md
  docs/en/admins/15_extensions.md
  docs/en/index.md
Labels: Documentation :books:

#4226 Improve: manage feed in view within a slider
  app/Controllers/feedController.php
  app/Controllers/indexController.php
  app/Controllers/subscriptionController.php
  app/layout/aside_feed.phtml
  app/views/configure/queries.phtml
  app/views/extension/index.phtml
  app/views/helpers/feed/update.phtml
  app/views/index/normal.phtml
  p/scripts/extra.js
  p/scripts/main.js
Labels: View

#4283 SimplePie fix parsing of HTTP Links
  app/Models/Feed.php
  lib/SimplePie/SimplePie.php
Labels: SimplePie :cake:

#4287 Fix handling of authors with ampersand &
  app/Models/Entry.php
  lib/lib_rss.php
Labels: Important :fire:

#4298 Fixed: Preview icon
  p/themes/Dark/dark.css
  p/themes/Dark/dark.rtl.css
  p/themes/Swage/swage.css
  p/themes/Swage/swage.rtl.css
  p/themes/Swage/swage.scss
  p/themes/icons/look.svg
Labels: Theme
