Repository FreshRSS/FreshRSS, pull requests merged in 2023-11, with the labels that each got.

#5796 Update feedback.php
  app/i18n/nl/feedback.php
Labels: I18n :earth_africa:

#5804 Fix Apache IfVersion
  CHANGELOG.md
  p/.htaccess
Labels: Security :shield:, Bug (confirmed) 🪲

#5813 Fix: inputs in add a new feed
  app/views/subscription/add.phtml
Labels: UI :art:

#5810 Improved: nord theme
  p/themes/Nord/nord.css
  p/themes/Nord/nord.rtl.css
Labels: Theme

#5815 init_posts(): load more posts on window resize
  p/scripts/main.js
Labels: UI :art:

#5805 document username:password@ syntax in proxy_help
  app/i18n/cz/sub.php
  app/i18n/de/sub.php
  app/i18n/el/sub.php
  app/i18n/en-us/sub.php
  app/i18n/en/sub.php
  app/i18n/es/sub.php
  app/i18n/fa/sub.php
  app/i18n/fr/sub.php
  app/i18n/he/sub.php
  app/i18n/hu/sub.php
  app/i18n/id/sub.php
  app/i18n/it/sub.php
  app/i18n/ja/sub.php
  app/i18n/ko/sub.php
  app/i18n/nl/sub.php
  app/i18n/oc/sub.php
  app/i18n/pl/sub.php
  app/i18n/pt-br/sub.php
  app/i18n/ru/sub.php
  app/i18n/sk/sub.php
  app/i18n/tr/sub.php
  app/i18n/zh-cn/sub.php
  app/i18n/zh-tw/sub.php
Labels: Documentation :books:

#5818 Update CREDITS.md
  CREDITS.md
Labels: Documentation :books:

#5808 add multi arch docker build
  .github/workflows/docker-publish.yml
  .github/workflows/dockerhub-description.yml
  CHANGELOG.md
  Docker/Dockerfile
  Docker/Dockerfile-Alpine
  Docker/Dockerfile-Newest
  Docker/Dockerfile-Oldest
  Docker/Dockerfile-QEMU-ARM
  Docker/README.md
  Docker/hooks/build
  Docker/hooks/post_checkout
  Docker/hooks/pre_build
  Makefile
  docs/en/developers/02_First_steps.md
  docs/fr/developers/01_First_steps.md
Labels: Docker

#5819 Fix minor GitHub Actions
  .github/workflows/docker-publish.yml
  .github/workflows/dockerhub-description.yml
  .github/workflows/jekyll-gh-pages.yml
Labels: Documentation :books:, Docker

#5826 Compatibility PHP 8.2 for running automated tests
  app/Models/CategoryDAO.php
  app/Models/CategoryDAOSQLite.php
  app/Models/EntryDAO.php
  app/Models/EntryDAOPGSQL.php
  app/Models/EntryDAOSQLite.php
  app/Models/FeedDAO.php
  app/Models/FeedDAOSQLite.php
Labels: System care

#5827 Do not show message Add some feeds
  app/i18n/cz/index.php
  app/i18n/de/index.php
  app/i18n/el/index.php
  app/i18n/en-us/index.php
  app/i18n/en/index.php
  app/i18n/es/index.php
  app/i18n/fa/index.php
  app/i18n/fr/index.php
  app/i18n/he/index.php
  app/i18n/hu/index.php
  app/i18n/id/index.php
  app/i18n/it/index.php
  app/i18n/ja/index.php
  app/i18n/ko/index.php
  app/i18n/lv/index.php
  app/i18n/nl/index.php
  app/i18n/oc/index.php
  app/i18n/pl/index.php
  app/i18n/pt-br/index.php
  app/i18n/ru/index.php
  app/i18n/sk/index.php
  app/i18n/tr/index.php
  app/i18n/zh-cn/index.php
  app/i18n/zh-tw/index.php
  app/views/index/global.phtml
  app/views/index/normal.phtml
  app/views/index/reader.phtml
Labels: UI :art:

#5831 Remove unneeded execution permissions
  app/i18n/hu/admin.php
  app/i18n/hu/conf.php
  app/i18n/hu/feedback.php
  app/i18n/hu/gen.php
  app/i18n/hu/index.php
  app/i18n/hu/install.php
  app/i18n/hu/sub.php
  app/i18n/hu/user.php
  app/views/entry/bookmark.phtml
  app/views/entry/read.phtml
  app/views/helpers/logs_pagination.phtml
  app/views/helpers/stream-footer.phtml
  app/views/index/rss.phtml
Labels: Security :shield:

#5829 Update WebSub documentation a bit
  Docker/README.md
  README.fr.md
  README.md
  app/Models/Feed.php
  docs/en/users/02_First_steps.md
  docs/en/users/05_Configuration.md
  docs/en/users/09_refreshing_feeds.md
  docs/en/users/WebSub.md
  docs/fr/users/02_First_steps.md
  docs/fr/users/08_PubSubHubbub.md
  p/api/pshb.php
Labels: Documentation :books:

#5812 Added ability to mark articles as read on focus.
  CHANGELOG.md
  app/Controllers/configureController.php
  app/i18n/cz/conf.php
  app/i18n/de/conf.php
  app/i18n/el/conf.php
  app/i18n/en-us/conf.php
  app/i18n/en/conf.php
  app/i18n/es/conf.php
  app/i18n/fa/conf.php
  app/i18n/fr/conf.php
  app/i18n/he/conf.php
  app/i18n/hu/conf.php
  app/i18n/id/conf.php
  app/i18n/it/conf.php
  app/i18n/ja/conf.php
  app/i18n/ko/conf.php
  app/i18n/lv/conf.php
  app/i18n/nl/conf.php
  app/i18n/oc/conf.php
  app/i18n/pl/conf.php
  app/i18n/pt-br/conf.php
  app/i18n/ru/conf.php
  app/i18n/sk/conf.php
  app/i18n/tr/conf.php
  app/i18n/zh-cn/conf.php
  app/i18n/zh-tw/conf.php
  app/views/configure/reading.phtml
  app/views/helpers/javascript_vars.phtml
  config-user.default.php
  p/scripts/main.js
Labels: UX

#5842 Fix updateTagName
  app/Models/TagDAO.php
Labels: Bug (confirmed) 🪲

#5845 Document Traefik PathPrefix
  Docker/README.md
  Docker/freshrss/docker-compose-proxy.yml
Labels: Documentation :books:, Docker

#5853 Fix trusted cidrs check
  docs/en/admins/09_AccessControl.md
  lib/lib_rss.php
Labels: Security :shield:

#5863 Docs: How to contribute new theme
  docs/en/admins/11_Themes.md
  docs/en/contributing.md
  docs/en/developers/04_Frontend/02_Design.md
  docs/en/users/05_Configuration.md
Labels: Documentation :books:, Theme

#5868 API fix add feed with title
  app/Models/Feed.php
  p/api/greader.php
Labels: API :handshake:, Bug (confirmed) 🪲

#5867 Favicon: avoid echo exception
  lib/favicons.php
Labels: Security :shield:

#5862 More WebSub doc
  README.fr.md
  README.md
  app/i18n/cz/admin.php
  app/i18n/de/admin.php
  app/i18n/el/admin.php
  app/i18n/el/sub.php
  app/i18n/en-us/admin.php
  app/i18n/en-us/sub.php
  app/i18n/en/admin.php
  app/i18n/en/sub.php
  app/i18n/es/admin.php
  app/i18n/fa/admin.php
  app/i18n/fr/admin.php
  app/i18n/fr/conf.php
  app/i18n/fr/feedback.php
  app/i18n/fr/sub.php
  app/i18n/he/admin.php
  app/i18n/he/sub.php
  app/i18n/hu/admin.php
  app/i18n/id/admin.php
  app/i18n/id/sub.php
  app/i18n/it/admin.php
  app/i18n/ja/admin.php
  app/i18n/ko/admin.php
  app/i18n/lv/admin.php
  app/i18n/nl/admin.php
  app/i18n/oc/admin.php
  app/i18n/pl/admin.php
  app/i18n/pt-br/admin.php
  app/i18n/ru/admin.php
  app/i18n/sk/admin.php
  app/i18n/tr/admin.php
  app/i18n/zh-cn/admin.php
  app/i18n/zh-tw/admin.php
  app/views/configure/system.phtml
  docs/en/users/WebSub.md
  docs/fr/users/08_PubSubHubbub.md
Labels: Documentation :books:

#5886 Improved: headlines font-sizes
  p/themes/base-theme/frss.css
  p/themes/base-theme/frss.rtl.css
Labels: UI :art:, UX

#5885 Improved: Nord theme
  p/themes/Nord/nord.css
  p/themes/Nord/nord.rtl.css
Labels: Theme

#5884 Added: Display option for "My labels"
  app/Controllers/configureController.php
  app/Models/UserConfiguration.php
  app/views/configure/display.phtml
  app/views/helpers/index/normal/entry_bottom.phtml
  config-user.default.php
Labels: UI :art:

#5889 Fix Minz_Session::param visibility
  lib/Minz/Session.php
Labels: Bug (confirmed) 🪲

#5891 Fix Minz_Extension::getVersion
  lib/Minz/Extension.php
Labels: Extension :electric_plug:, Bug (confirmed) 🪲

#5893 Fix PHP 7 compatibility strict_types
  Docker/Dockerfile-Oldest
  app/Models/CategoryDAO.php
  app/Models/DatabaseDAO.php
  app/Models/Entry.php
  app/Models/FeedDAO.php
  app/Models/StatsDAO.php
  app/actualize_script.php
  lib/lib_rss.php
Labels: Bug (confirmed) 🪲

#5898 Improve filtering of Cron env variables
  Docker/entrypoint.sh
Labels: Security :shield:, Docker

#5901 Fix types for extensions
  .dockerignore
  .eslintignore
  .gitignore
  .jshintignore
  .markdownlintignore
  app/Controllers/authController.php
  app/Controllers/javascriptController.php
  app/Controllers/statsController.php
  app/Mailers/UserMailer.php
  app/Models/ActionController.php
  app/layout/aside_configure.phtml
  lib/Minz/Extension.php
  lib/Minz/Mailer.php
  lib/Minz/View.php
  phpcs.xml
  phpstan.neon
Labels: Extension :electric_plug:, System care

#5902 Pass FreshRSS version to JS client side for extensions
  app/views/helpers/javascript_vars.phtml
Labels: UI :art:, Extension :electric_plug:

#5912 Fix XPath encoding
  app/views/index/rss.phtml
Labels: Bug (confirmed) 🪲
