Repository FreshRSS/FreshRSS, pull requests merged in 2023-07, with the labels that each got.

#5374 Delete deprecated themes: BlueLagoon & Screwdriver
  p/themes/BlueLagoon/icons/favicon-16-32-48-64.ico
  p/themes/BlueLagoon/icons/favicon-256.png
  p/themes/BlueLagoon/icons/favicon.svg
  p/themes/BlueLagoon/icons/icon.svg
  p/themes/BlueLagoon/icons/non-starred.svg
  p/themes/BlueLagoon/icons/read.svg
  p/themes/BlueLagoon/icons/starred.svg
  p/themes/BlueLagoon/icons/unread.svg
  p/themes/BlueLagoon/loader.gif
  p/themes/BlueLagoon/metadata.json
  p/themes/BlueLagoon/thumbs/original.png
  p/themes/Screwdriver/README.md
  p/themes/Screwdriver/icons/favicon-16-32-48-64.ico
  p/themes/Screwdriver/icons/favicon-256.png
  p/themes/Screwdriver/icons/favicon.svg
  p/themes/Screwdriver/icons/icon.svg
  p/themes/Screwdriver/icons/read.svg
  p/themes/Screwdriver/icons/starred.svg
  p/themes/Screwdriver/icons/unread.svg
  p/themes/Screwdriver/loader.gif
  p/themes/Screwdriver/metadata.json
  p/themes/Screwdriver/thumbs/original.png
Labels: UI :art:, Theme, deprecated

#5505 New extension hook entry_auto_read
  app/Controllers/feedController.php
  app/Models/Entry.php
  docs/en/developers/03_Backend/05_Extensions.md
  docs/fr/developers/03_Backend/05_Extensions.md
  lib/Minz/ExtensionManager.php
Labels: Extension :electric_plug:

#5501 fix many "Only booleans are allowed in an if condition"
  cli/create-user.php
  cli/delete-user.php
  cli/i18n/I18nUsageValidator.php
  lib/Minz/ExtensionException.php
  lib/Minz/ExtensionManager.php
  lib/Minz/Log.php
  lib/Minz/Migrator.php
  lib/Minz/ModelPdo.php
  lib/Minz/Pdo.php
  lib/Minz/Request.php
  lib/favicons.php
  lib/http-conditional.php
  lib/lib_rss.php
  p/api/greader.php
  p/i/index.php
Labels: System care

#5504 Chore/processing of depreciations and updating code to php72 minimum
  app/Controllers/authController.php
  app/Controllers/categoryController.php
  app/Controllers/configureController.php
  app/Controllers/entryController.php
  app/Controllers/errorController.php
  app/Controllers/extensionController.php
  app/Controllers/feedController.php
  app/Controllers/importExportController.php
  app/Controllers/indexController.php
  app/Controllers/statsController.php
  app/Controllers/subscriptionController.php
  app/Controllers/tagController.php
  app/Controllers/updateController.php
  app/Controllers/userController.php
  app/FreshRSS.php
  app/Mailers/UserMailer.php
  app/Models/Auth.php
  app/Models/BooleanSearch.php
  app/Models/Category.php
  app/Models/CategoryDAO.php
  app/Models/Context.php
  app/Models/DatabaseDAO.php
  app/Models/DatabaseDAOPGSQL.php
  app/Models/DatabaseDAOSQLite.php
  app/Models/Entry.php
  app/Models/EntryDAO.php
  app/Models/EntryDAOSQLite.php
  app/Models/Feed.php
  app/Models/FeedDAO.php
  app/Models/FilterAction.php
  app/Models/FormAuth.php
  app/Models/ReadingMode.php
  app/Models/Search.php
  app/Models/Share.php
  app/Models/StatsDAO.php
  app/Models/TagDAO.php
  app/Models/Themes.php
  app/Models/UserQuery.php
  app/Services/ImportService.php
  app/Utils/passwordUtil.php
  app/install.php
Labels: System care

#5515 Fix get and order when saving user query
  app/Controllers/configureController.php
Labels: Bug (confirmed) 🪲

#5523 Add OIDC_X_FORWARDED_HEADERS environment variable (fixes #5516)
  Docker/FreshRSS.Apache.conf
  docs/en/admins/16_OpenID-Connect.md
Labels: Security :shield:

#5531 Docker: Add DATA_PATH to cron env
  Docker/entrypoint.sh
Labels: Docker

#5541 Minor update dev dependencies
  composer.json
  composer.lock
  package-lock.json
  package.json
Labels: System care

#5549 Rework trusted proxies
  .devcontainer/Dockerfile
  Docker/Dockerfile
  Docker/Dockerfile-Alpine
  Docker/Dockerfile-Newest
  Docker/Dockerfile-Oldest
  Docker/Dockerfile-QEMU-ARM
  Docker/FreshRSS.Apache.conf
  Docker/README.md
  Docker/entrypoint.sh
  Docker/freshrss/docker-compose-proxy.yml
  Docker/freshrss/docker-compose.yml
  app/Controllers/authController.php
  app/install.php
  config.default.php
  docs/en/admins/09_AccessControl.md
  lib/lib_rss.php
  p/.htaccess
Labels: Security :shield:
