Repository FreshRSS/FreshRSS, pull requests merged in 2023-01, with the labels that each got.

#4979 Fix: Nord Theme: "Mark all" menu item
  p/themes/Alternative-Dark/adark.css
  p/themes/Alternative-Dark/adark.rtl.css
  p/themes/Ansum/_components.scss
  p/themes/Dark/dark.css
  p/themes/Dark/dark.rtl.css
  p/themes/Flat/flat.css
  p/themes/Flat/flat.rtl.css
  p/themes/Mapco/_components.scss
  p/themes/Nord/nord.css
  p/themes/Nord/nord.rtl.css
  p/themes/Origine/origine.css
  p/themes/Origine/origine.rtl.css
  p/themes/Pafat/pafat.css
  p/themes/Pafat/pafat.rtl.css
  p/themes/base-theme/frss.css
  p/themes/base-theme/frss.rtl.css
Labels: Theme

#4980 Improve: open "manage feed" with Ctrl in a new tab
  p/scripts/extra.js
Labels: Shortcuts

#4983 compile Mapco + Ansum again
  p/themes/Ansum/_components.scss
  p/themes/Ansum/ansum.css
  p/themes/Ansum/ansum.rtl.css
  p/themes/Mapco/_components.scss
  p/themes/Mapco/mapco.css
  p/themes/Mapco/mapco.rtl.css
Labels: Theme

#4944 Better enclosures
  app/Controllers/feedController.php
  app/Models/Entry.php
  app/Models/Feed.php
  app/views/helpers/index/normal/entry_header.phtml
  app/views/index/normal.phtml
  app/views/index/reader.phtml
  app/views/index/rss.phtml
  lib/SimplePie/SimplePie/Enclosure.php
  lib/SimplePie/SimplePie/Item.php
Labels: Important :fire:, SimplePie :cake:

#4995 fix: Ansum/Mapco theme: updating notification
  p/themes/Ansum/_layout.scss
  p/themes/Ansum/ansum.css
  p/themes/Ansum/ansum.rtl.css
  p/themes/Mapco/_layout.scss
  p/themes/Mapco/mapco.css
  p/themes/Mapco/mapco.rtl.css
Labels: Theme

#4985 fix: CSS "content:"
  p/themes/Alternative-Dark/adark.css
  p/themes/Alternative-Dark/adark.rtl.css
  p/themes/Ansum/_forms.scss
  p/themes/Ansum/ansum.css
  p/themes/Ansum/ansum.rtl.css
  p/themes/BlueLagoon/BlueLagoon.css
  p/themes/BlueLagoon/BlueLagoon.rtl.css
  p/themes/Dark/dark.css
  p/themes/Dark/dark.rtl.css
  p/themes/Flat/flat.css
  p/themes/Flat/flat.rtl.css
  p/themes/Mapco/_forms.scss
  p/themes/Mapco/mapco.css
  p/themes/Mapco/mapco.rtl.css
  p/themes/Nord/nord.css
  p/themes/Nord/nord.rtl.css
  p/themes/Origine-compact/origine-compact.css
  p/themes/Origine-compact/origine-compact.rtl.css
  p/themes/Origine/origine.css
  p/themes/Origine/origine.rtl.css
  p/themes/Pafat/pafat.css
  p/themes/Pafat/pafat.rtl.css
  p/themes/Screwdriver/screwdriver.css
  p/themes/Screwdriver/screwdriver.rtl.css
  p/themes/Swage/swage.css
  p/themes/Swage/swage.rtl.css
  p/themes/Swage/swage.scss
  p/themes/base-theme/base.css
  p/themes/base-theme/base.rtl.css
  p/themes/base-theme/frss.css
  p/themes/base-theme/frss.rtl.css
Labels: UI :art:, Theme

#4998 Lazy load logo on install, logo on header and theme thumbs in config slide
  app/install.php
  app/layout/header.phtml
  app/layout/simple.phtml
  app/views/configure/display.phtml
  p/index.html
Labels: UI :art:

#4843 Added: Dark mode for Origine +Origine compact themes
  app/Controllers/configureController.php
  app/Models/ConfigurationSetter.php
  app/Models/UserConfiguration.php
  app/i18n/cz/conf.php
  app/i18n/de/conf.php
  app/i18n/el/conf.php
  app/i18n/en-us/conf.php
  app/i18n/en/conf.php
  app/i18n/es/conf.php
  app/i18n/fr/conf.php
  app/i18n/he/conf.php
  app/i18n/id/conf.php
  app/i18n/it/conf.php
  app/i18n/ja/conf.php
  app/i18n/ko/conf.php
  app/i18n/nl/conf.php
  app/i18n/oc/conf.php
  app/i18n/pl/conf.php
  app/i18n/pt-br/conf.php
  app/i18n/ru/conf.php
  app/i18n/sk/conf.php
  app/i18n/tr/conf.php
  app/i18n/zh-cn/conf.php
  app/i18n/zh-tw/conf.php
  app/layout/layout.phtml
  app/views/configure/display.phtml
  config-user.default.php
  p/themes/Origine-compact/origine-compact.css
  p/themes/Origine-compact/origine-compact.rtl.css
  p/themes/Origine/origine.css
  p/themes/Origine/origine.rtl.css
Labels: UI :art:, Theme, FR: dark themes

#4989 Better handling of special chars in searches
  app/Models/BooleanSearch.php
  docs/en/users/03_Main_view.md
  docs/fr/users/03_Main_view.md
  tests/app/Models/SearchTest.php
Labels: Search :mag:

#4993 Update dev dependencies
  .github/workflows/tests.yml
  .typos.toml
  Makefile
  app/Controllers/updateController.php
  app/Models/Entry.php
  app/Models/Searchable.php
  app/Models/UserQuery.php
  composer.json
  composer.lock
  docs/en/admins/05_Configuring_email_validation.md
  docs/en/developers/02_Github.md
  docs/en/internationalization.md
  lib/http-conditional.php
  p/ext.php
  package-lock.json
  package.json
  tests/app/Models/UserQueryTest.php
Labels: System care, dependencies

#5006 Minor dev dependencies update
  composer.lock
  package-lock.json
  package.json
Labels: System care

#5013 documentation improved: split en/users/03_Main_view.md into 3 parts
  docs/en/admins/08_FeedUpdates.md
  docs/en/users/02_First_steps.md
  docs/en/users/03_Main_view.md
  docs/en/users/04_Subscriptions.md
  docs/en/users/09_refreshing_feeds.md
  docs/en/users/10_filter.md
Labels: Documentation :books:

#4807 Added: Mark theme as deprecated
  app/i18n/cz/conf.php
  app/i18n/de/conf.php
  app/i18n/el/conf.php
  app/i18n/en-us/conf.php
  app/i18n/en/conf.php
  app/i18n/es/conf.php
  app/i18n/fr/conf.php
  app/i18n/he/conf.php
  app/i18n/id/conf.php
  app/i18n/it/conf.php
  app/i18n/ja/conf.php
  app/i18n/ko/conf.php
  app/i18n/nl/conf.php
  app/i18n/oc/conf.php
  app/i18n/pl/conf.php
  app/i18n/pt-br/conf.php
  app/i18n/ru/conf.php
  app/i18n/sk/conf.php
  app/i18n/tr/conf.php
  app/i18n/zh-cn/conf.php
  app/i18n/zh-tw/conf.php
  app/views/configure/display.phtml
  docs/en/users/05_Configuration.md
  docs/fr/users/05_Configuration.md
  p/themes/BlueLagoon/metadata.json
  p/themes/Flat/metadata.json
  p/themes/Screwdriver/metadata.json
  p/themes/base-theme/frss.css
  p/themes/base-theme/frss.rtl.css
Labels: Theme, System care

#4937 Improved: navigation menu structure
  app/layout/aside_configure.phtml
  app/layout/aside_subscription.phtml
  p/themes/Alternative-Dark/adark.css
  p/themes/Alternative-Dark/adark.rtl.css
  p/themes/Ansum/_sidebar.scss
  p/themes/Ansum/ansum.css
  p/themes/Ansum/ansum.rtl.css
  p/themes/BlueLagoon/BlueLagoon.css
  p/themes/BlueLagoon/BlueLagoon.rtl.css
  p/themes/Dark/dark.css
  p/themes/Dark/dark.rtl.css
  p/themes/Flat/flat.css
  p/themes/Flat/flat.rtl.css
  p/themes/Mapco/_sidebar.scss
  p/themes/Mapco/mapco.css
  p/themes/Mapco/mapco.rtl.css
  p/themes/Nord/nord.css
  p/themes/Nord/nord.rtl.css
  p/themes/Origine/origine.css
  p/themes/Origine/origine.rtl.css
  p/themes/Pafat/pafat.css
  p/themes/Pafat/pafat.rtl.css
  p/themes/Screwdriver/screwdriver.css
  p/themes/Screwdriver/screwdriver.rtl.css
  p/themes/Swage/swage.css
  p/themes/Swage/swage.rtl.css
  p/themes/Swage/swage.scss
  p/themes/base-theme/frss.css
  p/themes/base-theme/frss.rtl.css
Labels: UI :art:

#5017 Docs: Explain the "Do not automatically refresh more often than"
  docs/en/users/09_refreshing_feeds.md
Labels: Documentation :books:

#5022 Minz i18n safer vsprintf
  lib/Minz/Translate.php
Labels: I18n :earth_africa:, Bug (confirmed) 🪲

#5025 Use paramBoolean consistently
  app/Controllers/configureController.php
Labels: System care

#5029 fix: Swage theme dropdown triangle
  p/themes/Swage/swage.css
  p/themes/Swage/swage.rtl.css
  p/themes/Swage/swage.scss
Labels: Theme

#5032 type hinting javascriptController
  app/Controllers/javascriptController.php
Labels: System care

#5028 statsController at phpStan level 9
  app/Controllers/statsController.php
  app/views/index/logs.phtml
Labels: System care

#5034 fix: "Mark selection as unread"
  p/themes/Alternative-Dark/adark.css
  p/themes/Alternative-Dark/adark.rtl.css
  p/themes/BlueLagoon/BlueLagoon.css
  p/themes/BlueLagoon/BlueLagoon.rtl.css
  p/themes/Dark/dark.css
  p/themes/Dark/dark.rtl.css
  p/themes/Flat/flat.css
  p/themes/Flat/flat.rtl.css
  p/themes/Nord/nord.css
  p/themes/Nord/nord.rtl.css
  p/themes/Origine/origine.css
  p/themes/Origine/origine.rtl.css
  p/themes/Pafat/pafat.css
  p/themes/Pafat/pafat.rtl.css
  p/themes/Screwdriver/screwdriver.css
  p/themes/Screwdriver/screwdriver.rtl.css
Labels: UI :art:

#5040 Improved: expanding inputs
  app/layout/header.phtml
  app/views/configure/system.phtml
  app/views/feed/add.phtml
  app/views/helpers/category/update.phtml
  app/views/helpers/configure/query.phtml
  app/views/subscription/add.phtml
  p/themes/Alternative-Dark/adark.css
  p/themes/Alternative-Dark/adark.rtl.css
  p/themes/Ansum/_forms.scss
  p/themes/Ansum/_layout.scss
  p/themes/Ansum/ansum.css
  p/themes/Ansum/ansum.rtl.css
  p/themes/BlueLagoon/BlueLagoon.css
  p/themes/BlueLagoon/BlueLagoon.rtl.css
  p/themes/Dark/dark.css
  p/themes/Dark/dark.rtl.css
  p/themes/Flat/flat.css
  p/themes/Flat/flat.rtl.css
  p/themes/Mapco/_forms.scss
  p/themes/Mapco/_layout.scss
  p/themes/Mapco/mapco.css
  p/themes/Mapco/mapco.rtl.css
  p/themes/Nord/nord.css
  p/themes/Nord/nord.rtl.css
  p/themes/Origine/origine.css
  p/themes/Origine/origine.rtl.css
  p/themes/Pafat/pafat.css
  p/themes/Pafat/pafat.rtl.css
  p/themes/Screwdriver/screwdriver.css
  p/themes/Screwdriver/screwdriver.rtl.css
  p/themes/Swage/swage.css
  p/themes/Swage/swage.rtl.css
  p/themes/Swage/swage.scss
  p/themes/base-theme/base.css
  p/themes/base-theme/base.rtl.css
  p/themes/base-theme/frss.css
  p/themes/base-theme/frss.rtl.css
Labels: UI :art:

#5039 Fix error handling when updating URL
  app/Controllers/subscriptionController.php
  app/Models/Feed.php
  lib/lib_rss.php
Labels: Bug (confirmed) 🪲

#5045 Fix types hint in UserQuery.php
  app/Models/UserQuery.php
  tests/app/Models/UserQueryTest.php
Labels: System care

#5050 Document cleaning the logs for passwords
  docs/en/admins/10_ServerConfig.md
Labels: Documentation :books:, Security :shield:

#5049 PHPStan level 9 for ./p/ and lib_rss.php
  app/FreshRSS.php
  app/Models/Entry.php
  app/Models/EntryDAO.php
  lib/Minz/ModelPdo.php
  lib/Minz/Translate.php
  lib/lib_rss.php
  p/api/fever.php
  p/api/greader.php
  p/api/pshb.php
  p/ext.php
  p/f.php
  p/i/index.php
Labels: System care

#5058 fix: Thumbnails background
  p/themes/base-theme/frss.css
  p/themes/base-theme/frss.rtl.css
Labels: UI :art:

#5055 Fix: dropdowns' overflow
  app/views/index/reader.phtml
  p/themes/base-theme/frss.css
  p/themes/base-theme/frss.rtl.css
Labels: UI :art:
