Repository FreshRSS/FreshRSS, pull requests merged in 2023-10, with the labels that each got.

#5688 Improved: Theme selector
  p/themes/base-theme/frss.css
  p/themes/base-theme/frss.rtl.css
Labels: UI :art:, UX

#5693 Minor update dependencies
  .github/workflows/tests.yml
  .typos.toml
  CHANGELOG.md
  composer.lock
  docs/en/internationalization.md
  docs/en/users/05_Configuration.md
  docs/i18n/freshrss.fr.po
  docs/i18n/templates/freshrss.pot
  lib/composer.json
  lib/phpmailer/phpmailer/README.md
  lib/phpmailer/phpmailer/VERSION
  lib/phpmailer/phpmailer/src/PHPMailer.php
  lib/phpmailer/phpmailer/src/SMTP.php
  package-lock.json
  package.json
Labels: System care

#5694 delete BlueLagoon and Screwdriver
  .typos.toml
  p/themes/BlueLagoon/BlueLagoon.css
  p/themes/BlueLagoon/BlueLagoon.rtl.css
  p/themes/BlueLagoon/README.md
  p/themes/Screwdriver/screwdriver.css
  p/themes/Screwdriver/screwdriver.rtl.css
Labels: Theme

#5695 fixed: margins in feed navigation bar
  app/layout/aside_feed.phtml
  p/themes/Pafat/pafat.css
  p/themes/Pafat/pafat.rtl.css
  p/themes/base-theme/frss.css
  p/themes/base-theme/frss.rtl.css
Labels: UI :art:

#5699 fix(minz): fix malformed HTTP header
  CREDITS.md
  lib/Minz/FrontController.php
Labels: Bug (confirmed) 🪲

#5689 improved: Nord theme
  p/themes/Nord/icons/help.svg
  p/themes/Nord/icons/link.svg
  p/themes/Nord/icons/read.svg
  p/themes/Nord/icons/share.svg
  p/themes/Nord/icons/starred.svg
  p/themes/Nord/icons/unread.svg
  p/themes/Nord/nord.css
  p/themes/Nord/nord.rtl.css
Labels: Theme

#5629 Do not update feeds after import
  app/Controllers/importExportController.php
  app/i18n/cz/feedback.php
  app/i18n/de/feedback.php
  app/i18n/el/feedback.php
  app/i18n/en-us/feedback.php
  app/i18n/en/feedback.php
  app/i18n/es/feedback.php
  app/i18n/fa/feedback.php
  app/i18n/fr/feedback.php
  app/i18n/he/feedback.php
  app/i18n/hu/feedback.php
  app/i18n/id/feedback.php
  app/i18n/it/feedback.php
  app/i18n/ja/feedback.php
  app/i18n/ko/feedback.php
  app/i18n/lv/feedback.php
  app/i18n/nl/feedback.php
  app/i18n/oc/feedback.php
  app/i18n/pl/feedback.php
  app/i18n/pt-br/feedback.php
  app/i18n/ru/feedback.php
  app/i18n/sk/feedback.php
  app/i18n/tr/feedback.php
  app/i18n/zh-cn/feedback.php
  app/i18n/zh-tw/feedback.php
Labels: UX

#5717 Changelog 1.22
  CHANGELOG.md
  CREDITS.md
  tests/phpstan-next.txt
Labels: Documentation :books:

#5719 Improved: Theme nord more improvement
  p/themes/Nord/nord.css
  p/themes/Nord/nord.rtl.css
Labels: Theme

#5681 Move to GitHub Actions for our GitHub Pages
  .github/workflows/jekyll-gh-pages.yml
Labels: Documentation :books:

#5730 Note about OpenID Connect only for x64
  docs/en/admins/16_OpenID-Connect.md
Labels: Documentation :books:

#5737 Navigation buttons: Group icons (.group instead of .stick)
  app/layout/nav_menu.phtml
  p/themes/Alternative-Dark/adark.css
  p/themes/Alternative-Dark/adark.rtl.css
  p/themes/Ansum/_layout.scss
  p/themes/Ansum/_mobile.scss
  p/themes/Ansum/_sidebar.scss
  p/themes/Ansum/ansum.css
  p/themes/Ansum/ansum.rtl.css
  p/themes/Flat/flat.css
  p/themes/Flat/flat.rtl.css
  p/themes/Mapco/_layout.scss
  p/themes/Mapco/_mobile.scss
  p/themes/Mapco/_sidebar.scss
  p/themes/Mapco/mapco.css
  p/themes/Mapco/mapco.rtl.css
  p/themes/Origine/origine.css
  p/themes/Origine/origine.rtl.css
  p/themes/Pafat/pafat.css
  p/themes/Pafat/pafat.rtl.css
  p/themes/Swage/swage.css
  p/themes/Swage/swage.rtl.css
  p/themes/Swage/swage.scss
  p/themes/base-theme/frss.css
  p/themes/base-theme/frss.rtl.css
Labels: UI :art:, Theme

#5733 Avoid a warning on non-numeric TRUSTED_PROXY en var
  Docker/entrypoint.sh
Labels: Security :shield:, Docker

#5740 Use RemoteIPInternalProxy directive of remoteip Apache module
  Docker/FreshRSS.Apache.conf
  Docker/README.md
  Docker/entrypoint.sh
  docs/en/admins/09_AccessControl.md
Labels: Security :shield:, Docker

#5741 Add Mossroy to CREDITS.md
  CREDITS.md
Labels: Documentation :books:

#5745 Fix origine dark mode
  p/themes/Origine/origine.css
  p/themes/Origine/origine.rtl.css
Labels: Theme

#5746 Create "Authentik" specific OIDC configuration.
  docs/en/admins/16_OpenID-Connect-Authentik.md
  docs/en/admins/16_OpenID-Connect.md
  docs/en/img/admins/authentik-01.png
  docs/en/img/admins/authentik-02.png
  docs/en/img/admins/authentik-03.png
  docs/en/img/admins/authentik-04.png
Labels: Documentation :books:, Security :shield:

#5747 Update CREDITS.md
  CREDITS.md
Labels: Documentation :books:

#5750 Fix searching thumbnails
  app/Models/Entry.php
Labels: Bug (confirmed) 🪲

#5752 Fix extensions i18n English fallback
  lib/Minz/Translate.php
Labels: Extension :electric_plug:, I18n :earth_africa:, Bug (confirmed) 🪲

#5753 OIDC_SCOPES compatibility colon
  CHANGELOG.md
  Docker/entrypoint.sh
  docs/en/admins/16_OpenID-Connect.md
Labels: Security :shield:, Docker

#5759 [i18n] Update Dutch translations
  app/i18n/nl/admin.php
  app/i18n/nl/conf.php
  app/i18n/nl/gen.php
  app/i18n/nl/index.php
  app/i18n/nl/sub.php
Labels: I18n :earth_africa:

#5762 Better i18n string for feed submenu for mark as read
  app/layout/aside_feed.phtml
Labels: I18n :earth_africa:, UX

#5754 More improvements/fixes of Nord theme
  p/themes/Nord/nord.css
  p/themes/Nord/nord.rtl.css
  p/themes/base-theme/frss.css
  p/themes/base-theme/frss.rtl.css
Labels: Theme

#5764 Prepare Alpine OIDC
  CHANGELOG.md
  Docker/Dockerfile-Newest
  Docker/entrypoint.sh
Labels: Security :shield:, Docker

#5765 Fix: inputs manage feed
  app/views/helpers/feed/update.phtml
  p/themes/base-theme/frss.css
  p/themes/base-theme/frss.rtl.css
Labels: UI :art:

#5766 Dev updates with stylelint-stylistic
  .github/workflows/tests.yml
  .stylelintrc.json
  Makefile
  composer.lock
  package-lock.json
  package.json
Labels: System care

#5773 Improve manage feeds: purge section
  app/views/helpers/feed/update.phtml
Labels: UX

#5774 Improve table scrolling
  app/views/extension/index.phtml
  app/views/index/logs.phtml
  app/views/stats/index.phtml
  app/views/stats/repartition.phtml
  app/views/user/manage.phtml
Labels: UX

#5772 Export all environment variables to cron
  Docker/entrypoint.sh
Labels: Docker

#5777 Update Readkit URL
  README.fr.md
  README.md
Labels: Documentation :books:, API :handshake:

#5511 applies several small optimizations
  app/Exceptions/ContextException.php
  app/Exceptions/DAOException.php
  app/Exceptions/EntriesGetterException.php
  app/Exceptions/FeedException.php
  app/Exceptions/ZipMissingException.php
  app/Models/ActionController.php
  app/Models/Log.php
  app/Models/SystemConfiguration.php
  app/Models/TagDAOPGSQL.php
  app/Models/UserConfiguration.php
  app/Models/ViewJavascript.php
  app/Models/ViewStats.php
  app/Utils/feverUtil.php
  app/install.php
  app/shares.php
Labels: System care

#5720 Require PHP 7.4+
  Docker/Dockerfile-Oldest
  README.fr.md
  README.md
  app/Controllers/entryController.php
  app/Controllers/importExportController.php
  app/Controllers/tagController.php
  app/Exceptions/AlreadySubscribedException.php
  app/Exceptions/FeedNotAddedException.php
  app/Exceptions/ZipException.php
  app/Models/Auth.php
  app/Models/BooleanSearch.php
  app/Models/Category.php
  app/Models/Context.php
  app/Models/Entry.php
  app/Models/EntryDAO.php
  app/Models/Feed.php
  app/Models/FilterAction.php
  app/Models/Log.php
  app/Models/ReadingMode.php
  app/Models/Search.php
  app/Models/Share.php
  app/Models/Tag.php
  app/Models/Themes.php
  app/Models/UserQuery.php
  app/Models/View.php
  app/Models/ViewJavascript.php
  app/Models/ViewStats.php
  app/Services/ExportService.php
  app/Services/ImportService.php
  cli/i18n/I18nCompletionValidator.php
  cli/i18n/I18nData.php
  cli/i18n/I18nUsageValidator.php
  cli/i18n/I18nValue.php
  composer.json
  composer.lock
  constants.php
  docs/en/admins/02_Prerequisites.md
  docs/en/admins/10_ServerConfig.md
  docs/fr/users/01_Installation.md
  lib/Minz/ActionController.php
  lib/Minz/Configuration.php
  lib/Minz/Dispatcher.php
  lib/Minz/Extension.php
  lib/Minz/ExtensionManager.php
  lib/Minz/FrontController.php
  lib/Minz/Mailer.php
  lib/Minz/Migrator.php
  lib/Minz/ModelArray.php
  lib/Minz/ModelPdo.php
  lib/Minz/Paginator.php
  lib/Minz/Pdo.php
  lib/Minz/Request.php
  lib/Minz/Session.php
  lib/Minz/Translate.php
  lib/Minz/View.php
  p/api/fever.php
  tests/app/Models/LogDAOTest.php
  tests/cli/i18n/I18nDataTest.php
  tests/cli/i18n/I18nUsageValidatorTest.php
Labels: System care

#5785 Fix JS regression dropdown label
  p/scripts/main.js
Labels: UI :art:, Bug (confirmed) 🪲

#5786 Fix type regression filterActions
  app/Models/Feed.php
Labels: Bug (confirmed) 🪲

#5787 Branch stylelint-config-recommended-scss
  package-lock.json
  package.json
Labels: System care

#5789 Clarify documentation on OIDC_X_FORWARDED_HEADERS
  docs/en/admins/16_OpenID-Connect.md
Labels: Documentation :books:, Security :shield:, Docker

#5798 Fix lang_name
  lib/Minz/Translate.php
Labels: Extension :electric_plug:, Bug (confirmed) 🪲

#5795 Fix Docker CRON_MIN for env with special characters
  CHANGELOG.md
  Docker/entrypoint.sh
Labels: Security :shield:, Docker, Bug (confirmed) 🪲

#5793 Update DB recommendations
  README.fr.md
  README.md
  app/install.php
  docs/en/admins/02_Prerequisites.md
  docs/fr/users/01_Installation.md
Labels: Documentation :books:
