Repository FreshRSS/FreshRSS, pull requests merged in 2023-09, with the labels that each got.

#5626 Fix JSON export/import
  app/Controllers/importExportController.php
  app/Models/Entry.php
  app/Models/TagDAO.php
  app/views/helpers/export/articles.phtml
  lib/lib_rss.php
  p/api/greader.php
Labels: Important :fire:, Bug (confirmed) 🪲

#5633 Fix parenthesis escaping bug
  app/Models/BooleanSearch.php
  app/Models/Search.php
  tests/app/Models/SearchTest.php
Labels: Bug (confirmed) 🪲

#5640 i18n: German translation of admin.php (new update page)
  app/i18n/de/admin.php
Labels: I18n :earth_africa:

#5639 Docker MySQL update doc
  Docker/README.md
Labels: Documentation :books:, Docker

#5636 i18n: shortened text strings
  app/i18n/cz/admin.php
  app/i18n/de/admin.php
  app/i18n/el/admin.php
  app/i18n/en-us/admin.php
  app/i18n/es/admin.php
  app/i18n/fr/admin.php
  app/i18n/he/admin.php
  app/i18n/id/admin.php
  app/i18n/it/admin.php
  app/i18n/ja/admin.php
  app/i18n/ko/admin.php
  app/i18n/lv/admin.php
  app/i18n/nl/admin.php
  app/i18n/oc/admin.php
  app/i18n/pl/admin.php
  app/i18n/pt-br/admin.php
  app/i18n/ru/admin.php
  app/i18n/sk/admin.php
  app/i18n/tr/admin.php
  app/i18n/zh-cn/admin.php
  app/i18n/zh-tw/admin.php
Labels: I18n :earth_africa:

#5646 add oidc callback URL and hints for Authelia to docs
  CREDITS.md
  docs/en/admins/16_OpenID-Connect.md
Labels: Documentation :books:, Security :shield:

#5647 Improved: Update page
  app/views/update/index.phtml
Labels: UI :art:, UX

#5649 SQL: clean old auto-updates
  app/Models/DatabaseDAO.php
  app/Models/EntryDAO.php
  app/Models/EntryDAOPGSQL.php
  app/Models/EntryDAOSQLite.php
  app/Models/FeedDAO.php
  app/Models/TagDAO.php
  app/Models/TagDAOSQLite.php
  app/Models/UserDAO.php
  app/SQL/install.sql.mysql.php
  app/SQL/install.sql.pgsql.php
  app/SQL/install.sql.sqlite.php
Labels: Update action :floppy_disk:

#5650 Fix labels in anonymous mode
  app/Controllers/tagController.php
  app/i18n/cz/gen.php
  app/i18n/de/gen.php
  app/i18n/el/gen.php
  app/i18n/en-us/gen.php
  app/i18n/en/gen.php
  app/i18n/es/gen.php
  app/i18n/fa/gen.php
  app/i18n/fr/gen.php
  app/i18n/he/gen.php
  app/i18n/hu/gen.php
  app/i18n/id/gen.php
  app/i18n/it/gen.php
  app/i18n/ja/gen.php
  app/i18n/ko/gen.php
  app/i18n/lv/gen.php
  app/i18n/nl/gen.php
  app/i18n/oc/gen.php
  app/i18n/pl/gen.php
  app/i18n/pt-br/gen.php
  app/i18n/ru/gen.php
  app/i18n/sk/gen.php
  app/i18n/tr/gen.php
  app/i18n/zh-cn/gen.php
  app/i18n/zh-tw/gen.php
  app/views/helpers/javascript_vars.phtml
  p/scripts/main.js
  p/themes/Alternative-Dark/adark.css
  p/themes/Alternative-Dark/adark.rtl.css
  p/themes/Origine/origine.css
  p/themes/Origine/origine.rtl.css
Labels: Security :shield:, Bug (confirmed) 🪲

#5655 Fix MariaDB size calculation
  app/Models/DatabaseDAO.php
Labels: Bug (confirmed) 🪲

#5653 Allow string in XPath tags
  app/Models/Feed.php
Labels: Bug (confirmed) 🪲

#5660 Fix dev container Apache logs
  .devcontainer/README.md
  .devcontainer/postCreateCommand.sh
Labels: Bug (confirmed) 🪲

#5667 fix: Fix check of existing usernames in cli scripts
  cli/create-user.php
  cli/delete-user.php
Labels: Bug (confirmed) 🪲

#5661 docker-compose PostgreSQL 16
  Docker/freshrss/docker-compose-db.yml
Labels: Documentation :books:, Docker

#5669 Fix search using user queries
  app/Models/BooleanSearch.php
  app/Models/UserQuery.php
  tests/app/Models/UserQueryTest.php
Labels: Bug (confirmed) 🪲
