Repository FreshRSS/FreshRSS, pull requests merged in 2023-08, with the labels that each got.

#5562 Fix cache refresh
  app/Controllers/feedController.php
  app/Models/Feed.php
Labels: Bug (confirmed) 🪲

#5559 OPML export fix empty attributes
  app/views/helpers/export/opml.phtml
Labels: Bug (confirmed) 🪲

#5561 Revert auto mark as read same titles for existing articles
  app/Controllers/feedController.php
Labels: Bug (confirmed) 🪲

#5567 [docs] Fix typos on the word 'scrape' and its variations
  docs/en/users/02_First_steps.md
  docs/en/users/11_website_scraping.md
Labels: Documentation :books:

#5571 Add Persian/فارسی Language
  .typos.toml
  CREDITS.md
  app/i18n/cz/gen.php
  app/i18n/de/gen.php
  app/i18n/el/gen.php
  app/i18n/en-us/gen.php
  app/i18n/en/gen.php
  app/i18n/es/gen.php
  app/i18n/fa/admin.php
  app/i18n/fa/conf.php
  app/i18n/fa/feedback.php
  app/i18n/fa/gen.php
  app/i18n/fa/index.php
  app/i18n/fa/install.php
  app/i18n/fa/sub.php
  app/i18n/fa/user.php
  app/i18n/fr/gen.php
  app/i18n/he/gen.php
  app/i18n/id/gen.php
  app/i18n/it/gen.php
  app/i18n/ja/gen.php
  app/i18n/ko/gen.php
  app/i18n/lv/gen.php
  app/i18n/nl/gen.php
  app/i18n/oc/gen.php
  app/i18n/pl/gen.php
  app/i18n/pt-br/gen.php
  app/i18n/ru/gen.php
  app/i18n/sk/gen.php
  app/i18n/tr/gen.php
  app/i18n/zh-cn/gen.php
  app/i18n/zh-tw/gen.php
Labels: I18n :earth_africa:

#5578 tec: Make FreshRSS_Share::register public
  app/Models/Share.php
Labels: Extension :electric_plug:, Bug (confirmed) 🪲

#5580 fix: Fix the "Show all articles" option
  app/Models/Context.php
Labels: Bug (confirmed) 🪲

#5576 Fix hash of articles with loadCompleteContent
  app/Models/Entry.php
  app/Models/EntryDAO.php
Labels: Bug (confirmed) 🪲

#5589 Add Hungarian language
  CREDITS.md
  app/i18n/cz/gen.php
  app/i18n/de/gen.php
  app/i18n/el/gen.php
  app/i18n/en-us/gen.php
  app/i18n/en/gen.php
  app/i18n/es/gen.php
  app/i18n/fa/gen.php
  app/i18n/fr/gen.php
  app/i18n/he/gen.php
  app/i18n/hu/admin.php
  app/i18n/hu/conf.php
  app/i18n/hu/feedback.php
  app/i18n/hu/gen.php
  app/i18n/hu/index.php
  app/i18n/hu/install.php
  app/i18n/hu/sub.php
  app/i18n/hu/user.php
  app/i18n/id/gen.php
  app/i18n/it/gen.php
  app/i18n/ja/gen.php
  app/i18n/ko/gen.php
  app/i18n/lv/gen.php
  app/i18n/nl/gen.php
  app/i18n/oc/gen.php
  app/i18n/pl/gen.php
  app/i18n/pt-br/gen.php
  app/i18n/ru/gen.php
  app/i18n/sk/gen.php
  app/i18n/tr/gen.php
  app/i18n/zh-cn/gen.php
  app/i18n/zh-tw/gen.php
  docs/en/users/05_Configuration.md
Labels: I18n :earth_africa:

#5603 fix: background color of <pre>
  p/themes/Origine/origine.css
  p/themes/Origine/origine.rtl.css
Labels: UI :art:

#5593 Fixed some typos in the Hungarian translation
  app/i18n/hu/admin.php
  app/i18n/hu/conf.php
  app/i18n/hu/feedback.php
  app/i18n/hu/gen.php
  app/i18n/hu/install.php
  app/i18n/hu/sub.php
  app/i18n/hu/user.php
Labels: I18n :earth_africa:

#5609 Fixed Spanish translation typo
  app/i18n/es/sub.php
Labels: I18n :earth_africa:

#5606 Fix: sharing via clipboard for no https/localhost environments
  p/scripts/main.js
  p/themes/base-theme/frss.css
  p/themes/base-theme/frss.rtl.css
Labels: UI :art:
