Repository FreshRSS/FreshRSS, pull requests merged in 2023-12, with the labels that each got.

#5906 Allow reas-as-scroll in important view
  app/views/index/normal.phtml
Labels: UX

#5927 Fix export
  app/Models/DatabaseDAO.php
  app/Models/TagDAO.php
Labels: Bug (confirmed) 🪲

#5935 Fix archiving
  app/Controllers/configureController.php
  app/Models/UserConfiguration.php
Labels: Bug (confirmed) 🪲

#5933 Alpine 3.19
  Docker/Dockerfile-Alpine
Labels: Docker

#5930 Fix font priority for languages using Han characters
  CREDITS.md
  p/themes/Alternative-Dark/adark.css
  p/themes/Alternative-Dark/adark.rtl.css
  p/themes/Flat/flat.css
  p/themes/Flat/flat.rtl.css
  p/themes/Origine/origine.css
  p/themes/Origine/origine.rtl.css
  p/themes/Pafat/pafat.css
  p/themes/Pafat/pafat.rtl.css
  p/themes/base-theme/base.css
  p/themes/base-theme/base.rtl.css
Labels: UI :art:, I18n :earth_africa:

#5937 Fix read_when_same_title_in_feed
  app/Controllers/configureController.php
Labels: Bug (confirmed) 🪲

#5959 Fix notifications
  app/Controllers/authController.php
  app/FreshRSS.php
  app/Models/View.php
  app/layout/layout.phtml
  app/layout/simple.phtml
  lib/Minz/Request.php
Labels: Bug (confirmed) 🪲

#5965 API add unsubscribe example
  docs/en/developers/06_GoogleReader_API.md
  docs/fr/users/06_Mobile_access.md
Labels: Documentation :books:, API :handshake:

#5977 Update zh-cn translations
  app/i18n/zh-cn/admin.php
  app/i18n/zh-cn/conf.php
  app/i18n/zh-cn/feedback.php
  app/i18n/zh-cn/gen.php
  app/i18n/zh-cn/index.php
  app/i18n/zh-cn/sub.php
Labels: I18n :earth_africa:

#5979 Fix extensions enableByList
  lib/Minz/ExtensionManager.php
Labels: Extension :electric_plug:, Bug (unconfirmed)

#5978 Fix show_tags_max
  app/views/index/normal.phtml
  app/views/index/reader.phtml
  config-user.default.php
Labels: Bug (confirmed) 🪲

#5992 fix: `base_url` becomes empty after saving configuration
  CHANGELOG.md
  app/Controllers/configureController.php
  app/views/configure/system.phtml
Labels: Bug (confirmed) 🪲

#5995 Doc Web git update
  README.fr.md
  docs/en/admins/06_LinuxInstall.md
Labels: Update action :floppy_disk:

#6000 Fixed peroid names in the Hungarian translation
  app/i18n/hu/gen.php
Labels: I18n :earth_africa:

#5999 fix: update page buttons
  p/themes/Alternative-Dark/adark.css
  p/themes/Alternative-Dark/adark.rtl.css
  p/themes/Ansum/_forms.scss
  p/themes/Ansum/ansum.css
  p/themes/Ansum/ansum.rtl.css
  p/themes/Flat/flat.css
  p/themes/Flat/flat.rtl.css
  p/themes/Mapco/_forms.scss
  p/themes/Mapco/mapco.css
  p/themes/Mapco/mapco.rtl.css
  p/themes/Origine/origine.css
  p/themes/Origine/origine.rtl.css
  p/themes/Pafat/pafat.css
  p/themes/Pafat/pafat.rtl.css
  p/themes/Swage/swage.css
  p/themes/Swage/swage.rtl.css
  p/themes/Swage/swage.scss
  p/themes/base-theme/base.css
  p/themes/base-theme/base.rtl.css
Labels: UI :art:

#6005 Translated the websub help line in the Hungarian translation
  app/i18n/hu/admin.php
Labels: I18n :earth_africa:

#5994 Docker Debian disable unused PHP modules
  Docker/Dockerfile
Labels: Docker

#5969 Authentik oAuth setup documentation updates
  app/views/auth/index.phtml
  docs/en/admins/16_OpenID-Connect-Authentik.md
  docs/en/img/admins/authentik-05.png
Labels: Documentation :books:, Security :shield:
