Repository FreshRSS/FreshRSS, pull requests merged in 2023-05, with the labels that each got.

#5366 Fix API starred
  app/Models/EntryDAO.php
  p/api/greader.php
Labels: API :handshake:, Bug (confirmed) 🪲

#5367 Fix mark-selection-as-unread
  app/layout/nav_menu.phtml
Labels: Bug (confirmed) 🪲

#5354 PHPStan Level 7 complete DAOs
  app/Controllers/feedController.php
  app/Controllers/indexController.php
  app/Controllers/statsController.php
  app/Models/CategoryDAO.php
  app/Models/Context.php
  app/Models/Entry.php
  app/Models/EntryDAO.php
  app/Models/Feed.php
  app/Models/FeedDAO.php
  app/Models/Search.php
  app/Models/TagDAO.php
  app/Models/UserQuery.php
  app/Services/ExportService.php
  cli/user-info.php
  tests/phpstan-next.txt
Labels: System care

#5358 Automatic trusted_sources during install
  app/Controllers/authController.php
  app/Controllers/userController.php
  app/Models/Auth.php
  app/Models/SystemConfiguration.php
  app/install.php
  lib/lib_rss.php
Labels: Security :shield:

#5370 Use PHPStan dynamicConstantNames
  app/Models/Feed.php
  app/actualize_script.php
  lib/Minz/Log.php
  lib/lib_install.php
  lib/lib_rss.php
  phpstan.neon
Labels: System care

#5361 phpstan level 7 for importExportController.php
  app/Controllers/importExportController.php
  app/i18n/cz/feedback.php
  app/i18n/de/feedback.php
  app/i18n/el/feedback.php
  app/i18n/en-us/feedback.php
  app/i18n/en/feedback.php
  app/i18n/es/feedback.php
  app/i18n/fr/feedback.php
  app/i18n/he/feedback.php
  app/i18n/id/feedback.php
  app/i18n/it/feedback.php
  app/i18n/ja/feedback.php
  app/i18n/ko/feedback.php
  app/i18n/lv/feedback.php
  app/i18n/nl/feedback.php
  app/i18n/oc/feedback.php
  app/i18n/pl/feedback.php
  app/i18n/pt-br/feedback.php
  app/i18n/ru/feedback.php
  app/i18n/sk/feedback.php
  app/i18n/tr/feedback.php
  app/i18n/zh-cn/feedback.php
  app/i18n/zh-tw/feedback.php
  tests/phpstan-next.txt
Labels: System care

#5373 phpstan level 7 for feedController.php
  app/Controllers/feedController.php
  app/Models/Entry.php
  tests/phpstan-next.txt
Labels: System care

#5376 phpstan level 7 for updateController.php
  app/Controllers/updateController.php
  tests/phpstan-next.txt
Labels: System care

#5375 docs: language table added
  Docker/README.md
  app/Models/BooleanSearch.php
  app/Services/ImportService.php
  docs/en/admins/05_Backup.md
  docs/en/internationalization.md
  docs/en/users/05_Configuration.md
  docs/en/users/08_sharing_services.md
  docs/en/users/10_filter.md
  docs/fr/internationalization.md
  docs/fr/users/05_Configuration.md
  lib/Minz/CurrentPagePaginationException.php
  lib/Minz/Log.php
  lib/Minz/Migrator.php
  lib/Minz/Session.php
  lib/lib_rss.php
  p/themes/Nord/README.md
  p/themes/Nord/metadata.json
  tests/lib/Minz/MigratorTest.php
Labels: Documentation :books:

#5261 Share in anonymous mode
  app/views/helpers/index/normal/entry_bottom.phtml
Labels: Security :shield:

#5349 Improved: "Mark an article as read…" text area. Added a link to the documentation
  app/i18n/cz/sub.php
  app/i18n/de/sub.php
  app/i18n/el/sub.php
  app/i18n/en-us/sub.php
  app/i18n/en/sub.php
  app/i18n/es/sub.php
  app/i18n/fr/sub.php
  app/i18n/he/sub.php
  app/i18n/id/sub.php
  app/i18n/it/sub.php
  app/i18n/ja/sub.php
  app/i18n/ko/sub.php
  app/i18n/lv/sub.php
  app/i18n/nl/sub.php
  app/i18n/oc/sub.php
  app/i18n/pl/sub.php
  app/i18n/pt-br/sub.php
  app/i18n/ru/sub.php
  app/i18n/sk/sub.php
  app/i18n/tr/sub.php
  app/i18n/zh-cn/sub.php
  app/i18n/zh-tw/sub.php
Labels: Documentation :books:

#5383 Update Docker image Alpine 3.18
  Docker/Dockerfile-Alpine
  cli/access-permissions.sh
Labels: Docker

#5391 Docs: delete 04_Changing_source_code.md
  docs/en/developers/01_Index.md
  docs/en/developers/03_Backend/04_Changing_source_code.md
  docs/fr/developers/03_Backend/04_Changing_source_code.md
  docs/i18n/freshrss.fr.po
  docs/i18n/templates/freshrss.pot
  docs/po4a.conf
Labels: Documentation :books:

#5350 Improved: Install process: give more infos
  README.fr.md
  README.md
  app/i18n/cz/index.php
  app/i18n/de/index.php
  app/i18n/es/index.php
  app/i18n/fr/index.php
  app/i18n/he/index.php
  app/i18n/it/index.php
  app/i18n/ja/index.php
  app/i18n/ko/index.php
  app/i18n/nl/index.php
  app/i18n/oc/index.php
  app/i18n/pl/index.php
  app/i18n/pt-br/index.php
  app/i18n/ru/index.php
  app/i18n/sk/index.php
  app/i18n/tr/index.php
  app/i18n/zh-cn/index.php
  app/i18n/zh-tw/index.php
  app/install.php
Labels: UI :art:, UX

#5389 PHPMailer 6.8.0
  lib/.gitignore
  lib/composer.json
  lib/phpmailer/phpmailer/README.md
  lib/phpmailer/phpmailer/VERSION
  lib/phpmailer/phpmailer/src/PHPMailer.php
  lib/phpmailer/phpmailer/src/SMTP.php
Labels: System care

#5392 fix: docs: array syntax
  docs/en/internationalization.md
  docs/fr/internationalization.md
Labels: Documentation :books:

#5394 Link configuration to proper parameter
  lib/Minz/Extension.php
Labels: Extension :electric_plug:, Bug (confirmed) 🪲

#5393 PHPStan Level 7 for Share userController logs_pagination
  app/Controllers/configureController.php
  app/Controllers/userController.php
  app/Models/FeedDAO.php
  app/Models/Share.php
  app/Models/View.php
  app/views/helpers/logs_pagination.phtml
  lib/Minz/Paginator.php
  tests/phpstan-next.txt
Labels: System care

#5398 fix: "for" attribute in config display
  app/views/configure/display.phtml
Labels: UI :art:

#5397 Fix: scroll bar color in dark mode
  app/layout/layout.phtml
  p/themes/Origine/origine.css
  p/themes/Origine/origine.rtl.css
Labels: UI :art:

#5401 fix: CSS: refactor of a.btn
  p/themes/Alternative-Dark/adark.css
  p/themes/Alternative-Dark/adark.rtl.css
  p/themes/Ansum/_forms.scss
  p/themes/Ansum/ansum.css
  p/themes/Ansum/ansum.rtl.css
  p/themes/BlueLagoon/BlueLagoon.css
  p/themes/BlueLagoon/BlueLagoon.rtl.css
  p/themes/Flat/flat.css
  p/themes/Flat/flat.rtl.css
  p/themes/Mapco/_forms.scss
  p/themes/Mapco/mapco.css
  p/themes/Mapco/mapco.rtl.css
  p/themes/Nord/nord.css
  p/themes/Nord/nord.rtl.css
  p/themes/Origine-compact/origine-compact.css
  p/themes/Origine-compact/origine-compact.rtl.css
  p/themes/Origine/origine.css
  p/themes/Origine/origine.rtl.css
  p/themes/Pafat/pafat.css
  p/themes/Pafat/pafat.rtl.css
  p/themes/Screwdriver/screwdriver.css
  p/themes/Screwdriver/screwdriver.rtl.css
  p/themes/Swage/swage.css
  p/themes/Swage/swage.rtl.css
  p/themes/Swage/swage.scss
  p/themes/base-theme/base.css
  p/themes/base-theme/base.rtl.css
  p/themes/base-theme/frss.css
  p/themes/base-theme/frss.rtl.css
Labels: Theme, System care

#5400 PHPStan Level 7 for Minz_Request, FreshRSS_Feed, Minz_Error
  app/Controllers/authController.php
  app/Controllers/userController.php
  app/FreshRSS.php
  app/Models/Entry.php
  app/Models/Feed.php
  lib/Minz/Error.php
  lib/Minz/FrontController.php
  lib/Minz/Request.php
  lib/Minz/Url.php
  tests/phpstan-next.txt
Labels: System care

#5404 Fix again updateLastSeenUnchanged
  app/Controllers/feedController.php
  app/Controllers/importExportController.php
  app/Models/Entry.php
  app/Models/EntryDAO.php
Labels: Bug (confirmed) 🪲

#5406 PHPStan Level 7 complete
  composer.json
  lib/Minz/Configuration.php
  lib/Minz/Mailer.php
  lib/Minz/Migrator.php
  lib/Minz/Pdo.php
  lib/core-extensions/Google-Groups/extension.php
  lib/lib_date.php
  phpstan.neon
  tests/lib/Minz/MigratorTest.php
  tests/phpstan-next.txt
Labels: System care

#5426 Fixed: i18n extensions: 'en' as fallback
  lib/Minz/Translate.php
Labels: Extension :electric_plug:, I18n :earth_africa:

#5408 Update of Spanish translation
  app/i18n/es/admin.php
  app/i18n/es/conf.php
Labels: I18n :earth_africa:

#5431 phpstan-9 for Share.php
  app/Models/Search.php
  app/Models/Share.php
  tests/app/Models/SearchTest.php
  tests/phpstan-next.txt
Labels: System care
