Repository FreshRSS/FreshRSS, pull requests merged in 2023-04, with the labels that each got.

#5253 Fix addFeed
  app/Controllers/feedController.php
Labels: Critical :skull_and_crossbones:

#5254 Latvian localizations
  .typos.toml
  app/i18n/cz/gen.php
  app/i18n/de/gen.php
  app/i18n/el/gen.php
  app/i18n/en-us/gen.php
  app/i18n/en/gen.php
  app/i18n/es/gen.php
  app/i18n/fr/gen.php
  app/i18n/he/gen.php
  app/i18n/id/gen.php
  app/i18n/it/gen.php
  app/i18n/ja/gen.php
  app/i18n/ko/gen.php
  app/i18n/lv/admin.php
  app/i18n/lv/conf.php
  app/i18n/lv/feedback.php
  app/i18n/lv/gen.php
  app/i18n/lv/index.php
  app/i18n/lv/install.php
  app/i18n/lv/sub.php
  app/i18n/lv/user.php
  app/i18n/nl/gen.php
  app/i18n/oc/gen.php
  app/i18n/pl/gen.php
  app/i18n/pt-br/gen.php
  app/i18n/ru/gen.php
  app/i18n/sk/gen.php
  app/i18n/tr/gen.php
  app/i18n/zh-cn/gen.php
  app/i18n/zh-tw/gen.php
Labels: I18n :earth_africa:

#5243 Fix extensions in actualize_script
  app/Controllers/extensionController.php
  app/Controllers/feedController.php
  app/Controllers/updateController.php
  app/FreshRSS.php
  app/Models/View.php
  app/actualize_script.php
  cli/_cli.php
  lib/Minz/ActionController.php
  lib/Minz/Configuration.php
  lib/Minz/Extension.php
  lib/Minz/ExtensionManager.php
  lib/Minz/Request.php
  lib/core-extensions/Google-Groups/extension.php
  lib/core-extensions/Tumblr-GDPR/extension.php
  p/api/greader.php
  p/api/pshb.php
  tests/phpstan-next.txt
Labels: Important :fire:, Bug (confirmed) 🪲

#5258 PHPStan 6 for CLI
  cli/_cli.php
  cli/_update-or-create-user.php
  cli/check.translation.php
  cli/manipulate.translation.php
  cli/prepare.php
  tests/phpstan-next.txt
Labels: System care

#5263 Fix phpstan level 9 error for f.php
  lib/favicons.php
  p/f.php
Labels: System care

#5264 PHPStan level 6 for more files
  app/Controllers/authController.php
  app/Controllers/updateController.php
  app/Models/Auth.php
  app/Models/FormAuth.php
  lib/Minz/ActionController.php
  lib/Minz/FrontController.php
  lib/Minz/ModelArray.php
  lib/Minz/Url.php
  tests/phpstan-next.txt
Labels: System care

#5267 Use typed access to request parameters
  app/Controllers/apiController.php
  app/Controllers/authController.php
  app/Controllers/categoryController.php
  app/Controllers/configureController.php
  app/Controllers/entryController.php
  app/Controllers/feedController.php
  app/Controllers/importExportController.php
  app/Controllers/indexController.php
  app/Controllers/statsController.php
  app/Controllers/subscriptionController.php
  app/Controllers/tagController.php
  app/Controllers/updateController.php
  app/Controllers/userController.php
  app/FreshRSS.php
  app/Models/Auth.php
  app/Models/Context.php
  app/Models/SystemConfiguration.php
  app/Models/TagDAO.php
  app/Models/UserConfiguration.php
  app/Services/ExportService.php
  app/layout/aside_feed.phtml
  app/layout/header.phtml
  app/layout/layout.phtml
  app/layout/nav_menu.phtml
  app/views/entry/bookmark.phtml
  app/views/helpers/feed/update.phtml
  app/views/helpers/javascript_vars.phtml
  app/views/index/normal.phtml
  app/views/index/reader.phtml
  app/views/subscription/add.phtml
  app/views/subscription/feed.phtml
  docs/en/developers/Minz/index.md
  docs/fr/developers/Minz/index.md
  lib/Minz/Helper.php
  lib/Minz/Request.php
  lib/Minz/Url.php
  tests/phpstan-next.txt
Labels: System care

#5269 Phpstan Level6 for View.php
  app/Controllers/authController.php
  app/Controllers/entryController.php
  app/Controllers/subscriptionController.php
  app/Controllers/tagController.php
  app/Controllers/userController.php
  app/Models/CategoryDAO.php
  app/Models/Entry.php
  app/Models/EntryDAO.php
  app/Models/TagDAO.php
  app/Models/UserConfiguration.php
  app/Models/View.php
  app/Services/ExportService.php
  app/views/configure/display.phtml
  app/views/entry/read.phtml
  app/views/index/logs.phtml
  app/views/tag/getTagsForEntry.phtml
  lib/Minz/View.php
  p/api/greader.php
  tests/phpstan-next.txt
Labels: System care

#5251 Remove ConfigurationSetter
  app/Models/ConfigurationSetter.php
  app/Models/Context.php
  app/Models/UserConfiguration.php
  lib/Minz/Configuration.php
  tests/phpstan-next.txt
Labels: System care

#5271 Fix login
  app/Controllers/feedController.php
  lib/Minz/Request.php
  lib/Minz/Url.php
Labels: Bug (confirmed) 🪲

#5272 Fix phpstan level 6 error
  app/Models/EntryDAO.php
  app/Services/ExportService.php
  tests/phpstan-next.txt
Labels: System care

#5275 PHPStan Level 6 for more files
  app/Models/FilterAction.php
  app/Models/Themes.php
  app/Models/View.php
  lib/Minz/Log.php
  lib/Minz/Translate.php
  tests/phpstan-next.txt
Labels: System care

#5278 Fix display options
  app/Controllers/configureController.php
Labels: Important :fire:

#5280 Improved: Dark theme with vars
  p/themes/Dark/dark.css
  p/themes/Dark/dark.rtl.css
  p/themes/Dark/metadata.json
Labels: Theme

#5279 PHPStan 6 for remaining controllers
  app/Controllers/feedController.php
  app/Controllers/userController.php
  tests/phpstan-next.txt
Labels: System care

#5277 PHPStan 9 for lib/http-conditional.php
  lib/http-conditional.php
  tests/phpstan-next.txt
Labels: System care

#5281 Improved: Theme slider for mobile
  p/themes/base-theme/frss.css
  p/themes/base-theme/frss.rtl.css
Labels: UI :art:

#5284 docs: shares.php. Added "HTMLtag"
  app/shares.php
Labels: Documentation :books:

#5282 Feature/phpstan for session class
  lib/Minz/Session.php
  tests/phpstan-next.txt
Labels: System care

#5283 PHPstan level 6 for Migrator.php
  lib/Minz/Migrator.php
  tests/phpstan-next.txt
Labels: System care

#5094 Improved: config user settings in slider
  app/views/user/details.phtml
  app/views/user/manage.phtml
  p/scripts/extra.js
Labels: UX

#5288 Improved: Dark mode of Origine (Improve #5229)
  p/themes/Origine/origine.css
  p/themes/Origine/origine.rtl.css
Labels: Theme

#5289 PHPStan Level 6 for FreshRSS_Share
  app/Models/Share.php
  app/shares.php
  tests/phpstan-next.txt
Labels: System care

#5290 PHPstan level 6 for Dispatcher.php
  lib/Minz/Dispatcher.php
  tests/phpstan-next.txt
Labels: System care

#5292 PHPStan Level 6 FreshRSS_Search FreshRSS_Entry
  app/Models/BooleanSearch.php
  app/Models/Entry.php
  app/Models/EntryDAO.php
  app/Models/Search.php
  app/views/helpers/feed/update.phtml
  lib/Minz/Helper.php
  lib/Minz/Request.php
  tests/phpstan-next.txt
Labels: Search :mag:, System care

#5291 PHPstan level 6 for I18nFile.php
  cli/i18n/I18nData.php
  cli/i18n/I18nFile.php
  cli/i18n/I18nValue.php
  tests/phpstan-next.txt
Labels: System care

#5297 Improved: global view: mobile view
  app/views/index/global.phtml
  p/scripts/global_view.js
  p/themes/Alternative-Dark/adark.css
  p/themes/Alternative-Dark/adark.rtl.css
  p/themes/Ansum/_mobile.scss
  p/themes/Ansum/ansum.css
  p/themes/Ansum/ansum.rtl.css
  p/themes/BlueLagoon/BlueLagoon.css
  p/themes/BlueLagoon/BlueLagoon.rtl.css
  p/themes/Dark/dark.css
  p/themes/Dark/dark.rtl.css
  p/themes/Flat/flat.css
  p/themes/Flat/flat.rtl.css
  p/themes/Mapco/_mobile.scss
  p/themes/Mapco/mapco.css
  p/themes/Mapco/mapco.rtl.css
  p/themes/Nord/nord.css
  p/themes/Nord/nord.rtl.css
  p/themes/Origine/origine.css
  p/themes/Origine/origine.rtl.css
  p/themes/Pafat/pafat.css
  p/themes/Pafat/pafat.rtl.css
  p/themes/Screwdriver/screwdriver.css
  p/themes/Screwdriver/screwdriver.rtl.css
  p/themes/Swage/swage.css
  p/themes/Swage/swage.rtl.css
  p/themes/Swage/swage.scss
  p/themes/base-theme/base.css
  p/themes/base-theme/base.rtl.css
  p/themes/base-theme/frss.css
  p/themes/base-theme/frss.rtl.css
Labels: UI :art:, Theme

#5299 PHPStan level 6 for remaining DAO classes
  app/Models/CategoryDAO.php
  app/Models/Entry.php
  app/Models/EntryDAO.php
  app/Models/FeedDAO.php
  app/Models/TagDAO.php
  tests/phpstan-next.txt
Labels: System care

#5304 Improved: .scrollbar-thin for #sidebar
  app/layout/aside_feed.phtml
  p/themes/base-theme/frss.css
  p/themes/base-theme/frss.rtl.css
Labels: UI :art:, System care

#5295 Improved: share to clipboard improved with animation and icon
  p/scripts/main.js
  p/themes/base-theme/frss.css
  p/themes/base-theme/frss.rtl.css
Labels: UI :art:

#5303 Improved: CSS classes for theme preview slider changed
  app/views/configure/display.phtml
  p/themes/Alternative-Dark/adark.css
  p/themes/Alternative-Dark/adark.rtl.css
  p/themes/Ansum/_configuration.scss
  p/themes/Ansum/ansum.css
  p/themes/Ansum/ansum.rtl.css
  p/themes/Dark/dark.css
  p/themes/Dark/dark.rtl.css
  p/themes/Mapco/_configuration.scss
  p/themes/Mapco/mapco.css
  p/themes/Mapco/mapco.rtl.css
  p/themes/base-theme/frss.css
  p/themes/base-theme/frss.rtl.css
Labels: UI :art:, System care

#5308 More consistent use of iterable type
  app/Controllers/indexController.php
  app/Models/CategoryDAO.php
  app/Models/Entry.php
  app/Models/EntryDAO.php
  app/Models/Feed.php
  app/Models/FeedDAO.php
  app/Models/TagDAO.php
Labels: System care

#5309 phpstan level 7 for user-info.php
  app/Models/EntryDAO.php
  cli/user-info.php
  tests/phpstan-next.txt
Labels: System care

#5311 Fix safe_ascii
  lib/lib_rss.php
Labels: Important :fire:

#5313 PHPStan Level 7 Minz_ActionController and lib_date
  lib/Minz/ActionController.php
  lib/lib_date.php
  tests/phpstan-next.txt
Labels: System care

#5318 PHPStan 7 configureController
  app/Controllers/configureController.php
  app/Models/UserConfiguration.php
  lib/lib_rss.php
  tests/phpstan-next.txt
Labels: System care, Bug (confirmed) 🪲

#5314 Show REMOTE_ADDR in case of HTTP Basic Auth error
  app/Controllers/authController.php
Labels: Security :shield:

#5327 PHPStan Level 7 for ten more files
  app/Controllers/indexController.php
  app/Models/CategoryDAO.php
  app/Models/Entry.php
  app/Models/EntryDAO.php
  app/Models/Feed.php
  app/Models/FeedDAO.php
  app/Models/ReadingMode.php
  app/Models/TagDAO.php
  app/Models/Themes.php
  app/Models/View.php
  app/Services/ExportService.php
  app/Services/ImportService.php
  app/views/index/reader.phtml
  app/views/user/details.phtml
  cli/do-install.php
  cli/i18n/I18nFile.php
  p/api/greader.php
  tests/cli/i18n/I18nFileTest.php
  tests/phpstan-next.txt
Labels: System care

#5328 PHPStan Level 7 for more DAO PDO
  app/Controllers/categoryController.php
  app/Controllers/statsController.php
  app/Controllers/tagController.php
  app/Models/CategoryDAO.php
  app/Models/DatabaseDAO.php
  app/Models/DatabaseDAOPGSQL.php
  app/Models/DatabaseDAOSQLite.php
  app/Models/Entry.php
  app/Models/EntryDAO.php
  app/Models/EntryDAOSQLite.php
  app/Models/FeedDAO.php
  app/Models/StatsDAO.php
  app/Models/StatsDAOPGSQL.php
  app/Models/StatsDAOSQLite.php
  app/Models/TagDAO.php
  app/Models/View.php
  app/Services/ExportService.php
  app/views/stats/index.phtml
  app/views/stats/repartition.phtml
  cli/user-info.php
  lib/Minz/Configuration.php
  lib/Minz/ModelPdo.php
  lib/Minz/Pdo.php
  lib/Minz/PdoMysql.php
  lib/Minz/PdoPgsql.php
  lib/Minz/PdoSqlite.php
  p/api/fever.php
  p/api/greader.php
  tests/phpstan-next.txt
Labels: System care

#5352 phpstan level 7 for manipulate.translation.php
  cli/manipulate.translation.php
  tests/phpstan-next.txt
Labels: System care

#5353 phpstan level 9 for check.translation.php
  cli/check.translation.php
  cli/manipulate.translation.php
  tests/phpstan-next.txt
Labels: System care

#5359 Update .gitignore: ignore the directory data.back
  .gitignore
Labels: System care

#5362 Fix TagDAO for SQLite
  app/Models/TagDAO.php
Labels: Bug (confirmed) 🪲
