Repository FreshRSS/FreshRSS, pull requests merged in 2024-03, with the labels that each got.

#6137 Reduce API memory consumption
  lib/lib_rss.php
  p/api/greader.php
Labels: API :handshake:

#6148 docs: Update 02_Prerequisites.md (Apache + PHP version)
  docs/en/admins/02_Prerequisites.md
Labels: Documentation :books:

#6155 version_compare raise exception if param is not a string
  app/views/extension/index.phtml
Labels: Extension :electric_plug:

#6175 Dependabot better group for npm
  .github/dependabot.yml
Labels: System care

#6177 Refactor some cURL options and use CURLOPT_USERPWD
  app/Controllers/feedController.php
  app/Models/Category.php
  app/Models/Entry.php
  app/Models/Feed.php
  lib/lib_rss.php
Labels: Security :shield:

#6186 Fix: Extension list: "installed" or "update available" message missed in some cases
  app/views/extension/index.phtml
Labels: Extension :electric_plug:

#6185 Fix empty token bug
  app/Controllers/userController.php
Labels: Security :shield:, Bug (confirmed) 🪲

#6197 Fix #5058 origine compact theme
  p/themes/Alternative-Dark/adark.css
  p/themes/Alternative-Dark/adark.rtl.css
  p/themes/Dark/dark.css
  p/themes/Dark/dark.rtl.css
  p/themes/Nord/nord.css
  p/themes/Nord/nord.rtl.css
  p/themes/Pafat/pafat.css
  p/themes/Pafat/pafat.rtl.css
  p/themes/base-theme/frss.css
  p/themes/base-theme/frss.rtl.css
Labels: UI :art:, Theme

#6205 Fix crash during update of existing install
  app/Models/SystemConfiguration.php
  app/Models/UserConfiguration.php
  app/install.php
Labels: Important :fire:, Bug (confirmed) 🪲

#6206 Improved: Smoother scrolling while focussing articles
  p/themes/base-theme/frss.css
  p/themes/base-theme/frss.rtl.css
Labels: UX

#6202 fixed HTML: <fieldset> + <legend>
  app/install.php
  app/views/configure/integration.phtml
  app/views/configure/system.phtml
  app/views/feed/add.phtml
  app/views/helpers/category/update.phtml
  app/views/helpers/configure/query.phtml
  app/views/helpers/feed/update.phtml
  app/views/index/logs.phtml
  app/views/tag/update.phtml
  app/views/user/profile.phtml
  p/scripts/integration.js
  p/themes/Alternative-Dark/adark.css
  p/themes/Alternative-Dark/adark.rtl.css
  p/themes/Ansum/_tables.scss
  p/themes/Ansum/ansum.css
  p/themes/Ansum/ansum.rtl.css
  p/themes/Flat/flat.css
  p/themes/Flat/flat.rtl.css
  p/themes/Mapco/_tables.scss
  p/themes/Mapco/mapco.css
  p/themes/Mapco/mapco.rtl.css
  p/themes/Nord/nord.css
  p/themes/Nord/nord.rtl.css
  p/themes/Origine/origine.css
  p/themes/Origine/origine.rtl.css
  p/themes/Pafat/pafat.css
  p/themes/Pafat/pafat.rtl.css
  p/themes/Swage/swage.css
  p/themes/Swage/swage.rtl.css
  p/themes/base-theme/base.css
  p/themes/base-theme/base.rtl.css
Labels: UI :art:

#6214 Fix CLI install regressions
  Docker/README.md
  cli/create-user.php
  cli/do-install.php
Labels: CLI, Bug (confirmed) 🪲

#6234 Fix fix #6221
  app/views/feed/contentSelectorPreview.phtml
Labels: UI :art:

#6241 Fix: Clicking outside of article text area closes the article
  p/scripts/main.js
Labels: UX

#6242 Improve: Article footer clickable area of dropdowns
  p/themes/base-theme/frss.css
  p/themes/base-theme/frss.rtl.css
Labels: UX

#6246 Add a way to modify CSP rules within an extension
  docs/en/developers/03_Backend/05_Extensions.md
  lib/Minz/ActionController.php
  lib/Minz/Extension.php
Labels: Extension :electric_plug:, Security :shield:

#6219 Update documentation for Caddy reverse proxy with subfolder
  docs/en/admins/01_Index.md
  docs/en/admins/Caddy.md
Labels: Documentation :books:

#6247 Unicode preg_split new line
  app/Services/ImportService.php
  lib/Minz/Request.php
Labels: Bug (confirmed) 🐞
