Repository FreshRSS/FreshRSS, pull requests merged in 2024-08, with the labels that each got.

#6672 Fix parentheses for complex `OR` boolean search expressions
  app/Models/BooleanSearch.php
  app/Models/Entry.php
  app/Models/EntryDAO.php
  tests/app/Models/SearchTest.php
Labels: Search :mag:, Bug (confirmed) 🐞

#6668 markdownlint no-trailing-spaces
  .markdownlint.json
Labels: System care

#6691 Update zh tw translation
  app/i18n/zh-tw/admin.php
  app/i18n/zh-tw/conf.php
  app/i18n/zh-tw/gen.php
  app/i18n/zh-tw/sub.php
Labels: I18n :earth_africa:

#6685 Migrate to ESLint 9
  .eslintignore
  .eslintrc.json
  .github/dependabot.yml
  .github/workflows/tests.yml
  eslint.config.js
  package-lock.json
  package.json
Labels: System care, javascript

#6709 Update about running tests
  Docker/README.md
  app/Models/Feed.php
  composer.lock
  docs/en/developers/03_Running_tests.md
  package-lock.json
  package.json
Labels: Documentation :books:, System care

#6713 Improve SQL transactions
  app/Controllers/feedController.php
Labels: Bug (confirmed) 🐞

#6718 Fix HTTP cache of user queries
  app/Models/UserDAO.php
  lib/lib_rss.php
  p/api/query.php
  p/i/index.php
Labels: Bug (confirmed) 🐞

#6719 Fix HTTP cache of main page
  app/Models/EntryDAO.php
  app/Models/EntryDAOSQLite.php
  p/i/index.php
Labels: Bug (confirmed) 🐞

#6723 Fix HTTP cache for modified time when content is not modified
  lib/SimplePie/SimplePie.php
Labels: SimplePie :cake:

#6726 feat: Added Elestio as one-click deploy option
  README.fr.md
  README.md
Labels: Documentation :books:

#6730 Fix OIDC session params definition
  Docker/FreshRSS.Apache.conf
  Docker/entrypoint.sh
  docs/en/admins/16_OpenID-Connect.md
Labels: Security :shield:, Docker

#6736 Fix PHPUnit version for tests
  tests/README.md
Labels: Documentation :books:

#6739 composer update
  composer.lock
Labels: dependencies, php

#6738 Fix mark-as-read from user query
  app/Controllers/entryController.php
Labels: Search :mag:, Bug (confirmed) 🐞

#6740 fixed: Mapco/Ansum theme
  p/themes/Ansum/_sidebar.scss
  p/themes/Ansum/ansum.css
  p/themes/Ansum/ansum.rtl.css
  p/themes/Mapco/_sidebar.scss
  p/themes/Mapco/mapco.css
  p/themes/Mapco/mapco.rtl.css
Labels: Theme

#6741 fixed: Shortcut keys for moving between categories
  p/scripts/main.js
Labels: Shortcuts, Bug (confirmed) 🐞

#6746 Improved: Feed aside bar more improvements
  p/themes/Alternative-Dark/adark.css
  p/themes/Alternative-Dark/adark.rtl.css
  p/themes/Dark-pink/pinkdark.css
  p/themes/Dark-pink/pinkdark.rtl.css
  p/themes/Nord/nord.css
  p/themes/Nord/nord.rtl.css
  p/themes/base-theme/frss.css
  p/themes/base-theme/frss.rtl.css
Labels: Theme
