Repository FreshRSS/FreshRSS, pull requests merged in 2024-10, with the labels that each got.

#6753 improved: 'My Labels' field be searchable
  app/views/index/global.phtml
  app/views/index/normal.phtml
  p/scripts/main.js
Labels: UX

#6859 fix: #6850
  app/views/stats/idle.phtml
  p/themes/base-theme/frss.css
  p/themes/base-theme/frss.rtl.css
Labels: UI :art:, Bug (confirmed) 🐞

#6864 refactor labels article menu
  app/views/helpers/index/normal/entry_bottom.phtml
  app/views/index/normal.phtml
  p/scripts/main.js
Labels: System care, UX

#6872 Update IT Translation
  app/i18n/it/admin.php
Labels: I18n :earth_africa:

#6893 Apache allow OIDC
  .htaccess.dist
  p/.htaccess
Labels: Security :shield:, Bug (confirmed) 🐞

#4487 New unicity policies for feeds with bad GUIDs
  app/Controllers/feedController.php
  app/Controllers/subscriptionController.php
  app/Models/Entry.php
  app/Models/Feed.php
  app/i18n/cs/sub.php
  app/i18n/de/sub.php
  app/i18n/el/sub.php
  app/i18n/en-us/sub.php
  app/i18n/en/sub.php
  app/i18n/es/sub.php
  app/i18n/fa/sub.php
  app/i18n/fr/sub.php
  app/i18n/he/sub.php
  app/i18n/hu/sub.php
  app/i18n/id/sub.php
  app/i18n/it/sub.php
  app/i18n/ja/sub.php
  app/i18n/ko/sub.php
  app/i18n/lv/sub.php
  app/i18n/nl/sub.php
  app/i18n/oc/sub.php
  app/i18n/pl/sub.php
  app/i18n/pt-br/sub.php
  app/i18n/ru/sub.php
  app/i18n/sk/sub.php
  app/i18n/tr/sub.php
  app/i18n/zh-cn/sub.php
  app/i18n/zh-tw/sub.php
  app/views/helpers/feed/update.phtml
  p/themes/base-theme/frss.css
  p/themes/base-theme/frss.rtl.css
Labels: Feed problem :newspaper_roll:

#6880 Add hook entries_favorite
  app/Models/EntryDAO.php
  docs/fr/developers/03_Backend/05_Extensions.md
  lib/Minz/ExtensionManager.php
Labels: Extension :electric_plug:

#6868 Support: new form for feed problems
  .github/ISSUE_TEMPLATE/feed-report-form.yml
Labels: Feed problem :newspaper_roll:, Support

#6896 Fix PHPCS ControlSignature
  app/Controllers/feedController.php
  app/Controllers/subscriptionController.php
  phpcs.xml
Labels: System care, php

#6900 Fix add feed with MariaDB / MySQL
  app/Controllers/feedController.php
  app/Models/FeedDAO.php
Labels: Critical :skull_and_crossbones:, Bug (confirmed) 🐞

#6908 Added missing translations
  app/i18n/es/sub.php
Labels: I18n :earth_africa:

#6910 Use HTML5 hidden
  app/views/index/normal.phtml
  app/views/index/reader.phtml
  p/scripts/main.js
  p/themes/base-theme/frss.css
  p/themes/base-theme/frss.rtl.css
Labels: UI :art:

#6886 Add move to next unread Label on mark as read.
  app/Controllers/entryController.php
  app/Models/Context.php
  app/i18n/cs/conf.php
  app/i18n/de/conf.php
  app/i18n/el/conf.php
  app/i18n/en-us/conf.php
  app/i18n/en/conf.php
  app/i18n/es/conf.php
  app/i18n/fa/conf.php
  app/i18n/fr/conf.php
  app/i18n/he/conf.php
  app/i18n/hu/conf.php
  app/i18n/id/conf.php
  app/i18n/it/conf.php
  app/i18n/ja/conf.php
  app/i18n/ko/conf.php
  app/i18n/lv/conf.php
  app/i18n/nl/conf.php
  app/i18n/oc/conf.php
  app/i18n/pl/conf.php
  app/i18n/pt-br/conf.php
  app/i18n/ru/conf.php
  app/i18n/sk/conf.php
  app/i18n/tr/conf.php
  app/i18n/zh-cn/conf.php
  app/i18n/zh-tw/conf.php
Labels: UI :art:

#6899 Fix favicon error in case of wrong URL
  lib/favicons.php
Labels: Bug (confirmed) 🐞

#6913 Fix the Makefile for test and fix targets.
  Makefile
Labels: System care

#6777 JavaScript form validation compatibility older browsers
  p/scripts/extra.js
Labels: UI :art:, javascript

#6920 Prepare options for category-level filter actions
  app/i18n/cs/conf.php
  app/i18n/de/conf.php
  app/i18n/el/conf.php
  app/i18n/en-us/conf.php
  app/i18n/en/conf.php
  app/i18n/es/conf.php
  app/i18n/fa/conf.php
  app/i18n/fr/conf.php
  app/i18n/he/conf.php
  app/i18n/hu/conf.php
  app/i18n/id/conf.php
  app/i18n/it/conf.php
  app/i18n/ja/conf.php
  app/i18n/ko/conf.php
  app/i18n/lv/conf.php
  app/i18n/nl/conf.php
  app/i18n/oc/conf.php
  app/i18n/pl/conf.php
  app/i18n/pt-br/conf.php
  app/i18n/ru/conf.php
  app/i18n/sk/conf.php
  app/i18n/tr/conf.php
  app/i18n/zh-cn/conf.php
  app/i18n/zh-tw/conf.php
  app/views/configure/reading.phtml
  app/views/helpers/category/update.phtml
Labels: UI :art:

#6926 Allow regex parentheses
  app/Models/BooleanSearch.php
  app/Models/Search.php
  tests/app/Models/SearchTest.php
Labels: Search :mag:

#6936 Fix regex for references to user queries
  app/Models/BooleanSearch.php
Labels: Search :mag:

#6946 Fix: (#6945) reading view: show subscr. mgm button
  p/themes/base-theme/frss.css
  p/themes/base-theme/frss.rtl.css
Labels: View, UX

#6947 Remove 'ChristopheHenry' android app
  README.fr.md
  README.md
Labels: Documentation :books:, API :handshake:

#6950 Fix regex parentheses of referenced search
  app/Models/BooleanSearch.php
Labels: Search :mag:, Article filter, Bug (confirmed) 🐞

#6954 Translation Finnish
  .typos.toml
  app/i18n/cs/gen.php
  app/i18n/de/gen.php
  app/i18n/el/gen.php
  app/i18n/en-us/gen.php
  app/i18n/en/gen.php
  app/i18n/es/gen.php
  app/i18n/fa/gen.php
  app/i18n/fi/admin.php
  app/i18n/fi/conf.php
  app/i18n/fi/feedback.php
  app/i18n/fi/gen.php
  app/i18n/fi/index.php
  app/i18n/fi/install.php
  app/i18n/fi/sub.php
  app/i18n/fi/user.php
  app/i18n/fr/gen.php
  app/i18n/he/gen.php
  app/i18n/hu/gen.php
  app/i18n/id/gen.php
  app/i18n/it/gen.php
  app/i18n/ja/gen.php
  app/i18n/ko/gen.php
  app/i18n/lv/gen.php
  app/i18n/nl/gen.php
  app/i18n/oc/gen.php
  app/i18n/pl/gen.php
  app/i18n/pt-br/gen.php
  app/i18n/ru/gen.php
  app/i18n/sk/gen.php
  app/i18n/tr/gen.php
  app/i18n/zh-cn/gen.php
  app/i18n/zh-tw/gen.php
Labels: I18n :earth_africa:, Hacktoberfest, hacktoberfest-accepted
