Repository FreshRSS/FreshRSS, pull requests merged in 2024-01, with the labels that each got.

#6010 API allow negative feed IDs
  p/api/greader.php
Labels: API :handshake:

#6016 Sanitize parsing list of extensions
  app/Controllers/extensionController.php
  app/Models/View.php
Labels: Bug (confirmed) 🪲

#6018 i18n: Italian: fixed-typo
  app/i18n/it/gen.php
Labels: I18n :earth_africa:

#6023 Update dev dependencies
  .github/workflows/tests.yml
  Makefile
  composer.json
  composer.lock
  package-lock.json
  package.json
Labels: System care

#6028 2297 cli parameters consistency
  cli/README.md
  cli/_cli.php
  cli/_update-or-create-user.php
  cli/create-user.php
  cli/do-install.php
  cli/reconfigure.php
  cli/update-user.php
Labels: CLI

#6038 Fix PHP 7.4 compatibility
  app/Utils/dotpathUtil.php
  app/views/helpers/export/opml.phtml
  composer.json
  composer.lock
  tests/app/Utils/dotpathUtilTest.php
  tests/bootstrap.php
Labels: Bug (confirmed) 🪲

#6039 Explicit PHP version for Composer
  composer.json
  composer.lock
  phpstan.neon
Labels: System care

#6037 PHPStan prepare exceptions
  app/Controllers/authController.php
  app/Controllers/feedController.php
  app/Controllers/indexController.php
  app/Controllers/tagController.php
  app/Controllers/updateController.php
  app/Controllers/userController.php
  app/Exceptions/AlreadySubscribedException.php
  app/Exceptions/ContextException.php
  app/Exceptions/DAOException.php
  app/Exceptions/EntriesGetterException.php
  app/Exceptions/FeedException.php
  app/Exceptions/FeedNotAddedException.php
  app/Exceptions/ZipException.php
  app/Exceptions/ZipMissingException.php
  app/Models/CategoryDAO.php
  app/Models/Context.php
  app/Models/Entry.php
  app/Models/EntryDAO.php
  app/Models/Feed.php
  app/Models/FeedDAO.php
  app/Models/UserQuery.php
  app/Utils/dotpathUtil.php
  app/install.php
  lib/Minz/Configuration.php
  lib/Minz/Exception.php
  lib/Minz/ExtensionManager.php
  lib/Minz/Log.php
  lib/Minz/Mailer.php
  lib/Minz/ModelArray.php
  lib/Minz/ModelPdo.php
  lib/Minz/Pdo.php
  lib/Minz/PdoMysql.php
  lib/Minz/PdoPgsql.php
  lib/Minz/PdoSqlite.php
  lib/Minz/Request.php
  lib/Minz/Url.php
  lib/Minz/View.php
  lib/favicons.php
  lib/lib_install.php
  lib/lib_rss.php
  phpstan.neon
Labels: System care

#6036 Standardise command line option parsing
  cli/README.md
  cli/_cli.php
  cli/_update-or-create-user.php
  cli/actualize-user.php
  cli/check.translation.php
  cli/db-optimize.php
  cli/delete-user.php
  cli/do-install.php
  cli/export-opml-for-user.php
  cli/export-sqlite-for-user.php
  cli/export-zip-for-user.php
  cli/import-for-user.php
  cli/import-sqlite-for-user.php
  cli/manipulate.translation.php
  cli/reconfigure.php
  cli/user-info.php
Labels: CLI

#6041 Fix manipulate.translation ignore behaviour
  cli/i18n/I18nData.php
  tests/cli/i18n/I18nDataTest.php
Labels: I18n :earth_africa:, CLI

#6046 Native array return type forgotten
  app/Models/CategoryDAO.php
  app/Models/EntryDAO.php
Labels: System care

#4633 Add Read You
  README.fr.md
  README.md
  docs/en/developers/06_Fever_API.md
  docs/en/developers/06_GoogleReader_API.md
  docs/fr/users/06_Fever_API.md
  docs/fr/users/06_Mobile_access.md
Labels: Documentation :books:, API :handshake:

#6050 Read You not offline
  README.fr.md
  README.md
Labels: Documentation :books:, API :handshake:

#6060 Updated italian translations
  app/i18n/it/admin.php
  app/i18n/it/conf.php
  app/i18n/it/feedback.php
  app/i18n/it/gen.php
  app/i18n/it/index.php
  app/i18n/it/sub.php
Labels: I18n :earth_africa:

#6061 SimplePie log HTTP status of requests
  lib/SimplePie/SimplePie/File.php
Labels: SimplePie :cake:

#6067 Fix typos in pt-br translation
  app/i18n/pt-br/conf.php
Labels: I18n :earth_africa:

#6073 Fix default category name
  app/Models/Category.php
  app/views/helpers/category/update.phtml
Labels: Bug (confirmed) 🪲

#6074 Improve the padding of the notification banner
  p/themes/Nord/nord.css
  p/themes/Nord/nord.rtl.css
  p/themes/Origine-compact/origine-compact.css
  p/themes/Origine-compact/origine-compact.rtl.css
  p/themes/base-theme/frss.css
  p/themes/base-theme/frss.rtl.css
Labels: UI :art:

#6075 composer update
  composer.lock
  lib/lib_rss.php
Labels: System care
