Repository FreshRSS/FreshRSS, pull requests merged in 2024-12, with the labels that each got.

#7049 i18n: "still reachable"
  app/i18n/cs/sub.php
  app/i18n/de/sub.php
  app/i18n/el/sub.php
  app/i18n/en-us/sub.php
  app/i18n/en/sub.php
  app/i18n/es/sub.php
  app/i18n/fa/sub.php
  app/i18n/fi/sub.php
  app/i18n/fr/sub.php
  app/i18n/he/sub.php
  app/i18n/hu/sub.php
  app/i18n/id/sub.php
  app/i18n/ja/sub.php
  app/i18n/ko/sub.php
  app/i18n/lv/sub.php
  app/i18n/nl/sub.php
  app/i18n/oc/sub.php
  app/i18n/pl/sub.php
  app/i18n/pt-br/sub.php
  app/i18n/ru/sub.php
  app/i18n/sk/sub.php
  app/i18n/zh-cn/sub.php
  app/i18n/zh-tw/sub.php
Labels: I18n :earth_africa:

#7052 Update dev dependencies
  composer.json
  composer.lock
  package-lock.json
  package.json
Labels: System care

#7059 Fix initial scroll for some browsers
  p/scripts/main.js
Labels: UI :art:

#7029 Implement showing and hiding header depending on scroll
  app/layout/header.phtml
  p/scripts/main.js
  p/themes/base-theme/frss.css
  p/themes/base-theme/frss.rtl.css
Labels: UI :art:

#7053 #4870 opml category text field
  CREDITS.md
  app/i18n/cs/sub.php
  app/i18n/de/sub.php
  app/i18n/el/sub.php
  app/i18n/en-us/sub.php
  app/i18n/en/sub.php
  app/i18n/es/sub.php
  app/i18n/fa/sub.php
  app/i18n/fi/sub.php
  app/i18n/fr/sub.php
  app/i18n/he/sub.php
  app/i18n/hu/sub.php
  app/i18n/id/sub.php
  app/i18n/it/sub.php
  app/i18n/ja/sub.php
  app/i18n/ko/sub.php
  app/i18n/lv/sub.php
  app/i18n/nl/sub.php
  app/i18n/oc/sub.php
  app/i18n/pl/sub.php
  app/i18n/pt-br/sub.php
  app/i18n/ru/sub.php
  app/i18n/sk/sub.php
  app/i18n/tr/sub.php
  app/i18n/zh-cn/sub.php
  app/i18n/zh-tw/sub.php
  app/views/subscription/add.phtml
Labels: I18n :earth_africa:

#7048 improve api management
  app/i18n/cs/admin.php
  app/i18n/cs/conf.php
  app/i18n/de/admin.php
  app/i18n/de/conf.php
  app/i18n/el/admin.php
  app/i18n/el/conf.php
  app/i18n/en-us/admin.php
  app/i18n/en-us/conf.php
  app/i18n/en/admin.php
  app/i18n/en/conf.php
  app/i18n/es/admin.php
  app/i18n/es/conf.php
  app/i18n/fa/admin.php
  app/i18n/fa/conf.php
  app/i18n/fi/admin.php
  app/i18n/fi/conf.php
  app/i18n/fr/admin.php
  app/i18n/fr/conf.php
  app/i18n/he/admin.php
  app/i18n/he/conf.php
  app/i18n/hu/admin.php
  app/i18n/hu/conf.php
  app/i18n/id/admin.php
  app/i18n/id/conf.php
  app/i18n/it/admin.php
  app/i18n/it/conf.php
  app/i18n/ja/admin.php
  app/i18n/ja/conf.php
  app/i18n/ko/admin.php
  app/i18n/ko/conf.php
  app/i18n/lv/admin.php
  app/i18n/lv/conf.php
  app/i18n/nl/admin.php
  app/i18n/nl/conf.php
  app/i18n/oc/admin.php
  app/i18n/oc/conf.php
  app/i18n/pl/admin.php
  app/i18n/pl/conf.php
  app/i18n/pt-br/admin.php
  app/i18n/pt-br/conf.php
  app/i18n/ru/admin.php
  app/i18n/ru/conf.php
  app/i18n/sk/admin.php
  app/i18n/sk/conf.php
  app/i18n/tr/admin.php
  app/i18n/tr/conf.php
  app/i18n/zh-cn/admin.php
  app/i18n/zh-cn/conf.php
  app/i18n/zh-tw/admin.php
  app/i18n/zh-tw/conf.php
  app/views/helpers/configure/query.phtml
  app/views/user/profile.phtml
  docs/fr/users/06_Fever_API.md
  docs/fr/users/06_Mobile_access.md
Labels: API :handshake:, UX

#7060 API support edit multiple tags
  p/api/greader.php
Labels: API :handshake:

#7064 Revert "Implement showing and hiding header depending on scroll (#7029)"
  app/layout/header.phtml
  p/scripts/main.js
  p/themes/base-theme/frss.css
  p/themes/base-theme/frss.rtl.css
Labels: UI :art:, Bug (confirmed) 🐞

#7054 Rework UI authors
  app/views/helpers/index/article.phtml
  app/views/helpers/index/authors.phtml
  app/views/helpers/index/normal/entry_header.phtml
  app/views/index/normal.phtml
Labels: UI :art:

#7055 Parentheses in quoted search
  app/Models/BooleanSearch.php
  app/Models/Search.php
  docs/en/users/10_filter.md
  docs/fr/users/03_Main_view.md
  tests/app/Models/SearchTest.php
Labels: Search :mag:

#7056 Avoid Unicode escape of authors in HTML UI
  app/Models/Feed.php
Labels: UI :art:, Security :shield:

#7066 Fix invalid login message
  app/Controllers/javascriptController.php
Labels: Security :shield:, Bug (confirmed) 🐞

#7067 Merge SimplePie 1.8.1
  lib/composer.json
  lib/simplepie/simplepie/.gitignore
  lib/simplepie/simplepie/CHANGELOG.md
  lib/simplepie/simplepie/phpstan.neon.dist
  lib/simplepie/simplepie/src/File.php
  lib/simplepie/simplepie/src/Gzdecode.php
  lib/simplepie/simplepie/src/IRI.php
  lib/simplepie/simplepie/src/SimplePie.php
Labels: SimplePie :cake:

#7070 Docker: Alpine 3.21
  .devcontainer/Dockerfile
  Docker/Dockerfile-Alpine
Labels: Docker 🐋

#7074 improve(GReader): update doc URLs; add TODO
  p/api/greader.php
Labels: API :handshake:

#7068 i18n: german
  app/i18n/de/admin.php
  app/i18n/de/conf.php
  app/i18n/de/gen.php
  app/i18n/de/sub.php
Labels: I18n :earth_africa:

#7075 docs: headlines added
  docs/en/contributing.md
  docs/en/users/02_First_steps.md
Labels: Documentation :books:

#7062 Fixed: No user query - no information
  app/i18n/cs/conf.php
  app/i18n/de/conf.php
  app/i18n/el/conf.php
  app/i18n/en-us/conf.php
  app/i18n/en/conf.php
  app/i18n/es/conf.php
  app/i18n/fa/conf.php
  app/i18n/fi/conf.php
  app/i18n/fr/conf.php
  app/i18n/he/conf.php
  app/i18n/hu/conf.php
  app/i18n/id/conf.php
  app/i18n/it/conf.php
  app/i18n/ja/conf.php
  app/i18n/ko/conf.php
  app/i18n/lv/conf.php
  app/i18n/nl/conf.php
  app/i18n/oc/conf.php
  app/i18n/pl/conf.php
  app/i18n/pt-br/conf.php
  app/i18n/ru/conf.php
  app/i18n/sk/conf.php
  app/i18n/tr/conf.php
  app/i18n/zh-cn/conf.php
  app/i18n/zh-tw/conf.php
  app/views/configure/queries.phtml
Labels: UX

#7073 Sanitize before CSS manipulation
  app/Models/Entry.php
Labels: Bug (confirmed) 🐞

#7077 windows.open noopener
  p/scripts/main.js
Labels: UI :art:, Security :shield:, UX

#7086 I18n Italian update
  app/i18n/it/sub.php
Labels: I18n :earth_africa:

#7089 Always prevent default regardless of window.open() return status
  p/scripts/main.js
Labels: UI :art:, Security :shield:

#7091 Improved CSS filter
  app/Controllers/subscriptionController.php
  app/Models/Entry.php
Labels: Bug (confirmed) 🐞

#7090 Matching category colors across pie-charts
  app/views/stats/index.phtml
Labels: UI :art:

#7088 New state: favorite or unread
  .typos.toml
  app/Models/Context.php
  app/Models/Entry.php
  app/Models/EntryDAO.php
  app/i18n/cs/conf.php
  app/i18n/de/conf.php
  app/i18n/el/conf.php
  app/i18n/en-us/conf.php
  app/i18n/en/conf.php
  app/i18n/es/conf.php
  app/i18n/fa/conf.php
  app/i18n/fi/conf.php
  app/i18n/fr/conf.php
  app/i18n/he/conf.php
  app/i18n/hu/conf.php
  app/i18n/id/conf.php
  app/i18n/it/conf.php
  app/i18n/ja/conf.php
  app/i18n/ko/conf.php
  app/i18n/lv/conf.php
  app/i18n/nl/conf.php
  app/i18n/oc/conf.php
  app/i18n/pl/conf.php
  app/i18n/pt-br/conf.php
  app/i18n/ru/conf.php
  app/i18n/sk/conf.php
  app/i18n/tr/conf.php
  app/i18n/zh-cn/conf.php
  app/i18n/zh-tw/conf.php
  app/layout/aside_feed.phtml
  app/layout/nav_menu.phtml
  app/views/configure/reading.phtml
Labels: Search :mag:, UX

#7113 fix: sharing menu entry id
  app/views/helpers/index/normal/entry_share_menu.phtml
  app/views/index/normal.phtml
  p/scripts/main.js
Labels: Extension :electric_plug:, Bug (confirmed) 🐞

#7128 i18n: fix de
  app/i18n/de/admin.php
Labels: I18n :earth_africa:

#7127 doc(docker-cron): duplicate documentation from README to the official…
  docs/en/admins/08_FeedUpdates.md
Labels: Documentation :books:, Docker 🐋

#7132 Allow privacy page to non admins
  app/Controllers/configureController.php
Labels: Extension :electric_plug:, Security :shield:

#7137 reduce docker build for releases
  .github/workflows/docker-publish.yml
Labels: Docker 🐋

#7135 doc(openid-connect): clarify that OIDC is only supported for the Apache web server
  docs/en/admins/16_OpenID-Connect.md
Labels: Documentation :books:, Security :shield:

#7133 new: reader view: footer has manage icons
  app/views/feed/contentSelectorPreview.phtml
  app/views/helpers/index/article.phtml
  app/views/index/normal.phtml
  p/themes/Alternative-Dark/adark.css
  p/themes/Alternative-Dark/adark.rtl.css
  p/themes/Ansum/_layout.scss
  p/themes/Ansum/_reader-view.scss
  p/themes/Ansum/ansum.css
  p/themes/Ansum/ansum.rtl.css
  p/themes/Dark/dark.css
  p/themes/Dark/dark.rtl.css
  p/themes/Flat/flat.css
  p/themes/Flat/flat.rtl.css
  p/themes/Mapco/_layout.scss
  p/themes/Mapco/_reader-view.scss
  p/themes/Mapco/mapco.css
  p/themes/Mapco/mapco.rtl.css
  p/themes/Nord/nord.css
  p/themes/Nord/nord.rtl.css
  p/themes/Origine/origine.css
  p/themes/Origine/origine.rtl.css
  p/themes/Pafat/pafat.css
  p/themes/Pafat/pafat.rtl.css
  p/themes/Swage/swage.css
  p/themes/Swage/swage.rtl.css
  p/themes/Swage/swage.scss
  p/themes/base-theme/base.css
  p/themes/base-theme/base.rtl.css
  p/themes/base-theme/frss.css
  p/themes/base-theme/frss.rtl.css
Labels: UI :art:, View

#7144 Search in all feeds
  app/Controllers/entryController.php
  app/Controllers/indexController.php
  app/Models/Context.php
  app/Models/EntryDAO.php
  app/Models/UserQuery.php
  app/i18n/cs/conf.php
  app/i18n/de/conf.php
  app/i18n/el/conf.php
  app/i18n/el/sub.php
  app/i18n/en-us/conf.php
  app/i18n/en-us/sub.php
  app/i18n/en/conf.php
  app/i18n/en/sub.php
  app/i18n/es/conf.php
  app/i18n/fa/conf.php
  app/i18n/fi/conf.php
  app/i18n/fr/conf.php
  app/i18n/he/conf.php
  app/i18n/he/sub.php
  app/i18n/hu/conf.php
  app/i18n/id/conf.php
  app/i18n/id/sub.php
  app/i18n/it/conf.php
  app/i18n/ja/conf.php
  app/i18n/ko/conf.php
  app/i18n/lv/conf.php
  app/i18n/nl/conf.php
  app/i18n/oc/conf.php
  app/i18n/pl/conf.php
  app/i18n/pt-br/conf.php
  app/i18n/ru/conf.php
  app/i18n/sk/conf.php
  app/i18n/tr/conf.php
  app/i18n/zh-cn/conf.php
  app/i18n/zh-tw/conf.php
  app/layout/aside_feed.phtml
  app/layout/layout.phtml
  app/views/helpers/configure/query.phtml
  p/themes/base-theme/frss.css
  p/themes/base-theme/frss.rtl.css
Labels: Search :mag:

#7151 Adds BASE_URL to example .env file
  Docker/README.md
Labels: Documentation :books:, Docker 🐋

#7153 Hint .htaccess
  p/.htaccess
Labels: Documentation :books:, Security :shield:

#7155 Fix regressions on some array structures
  app/Controllers/indexController.php
  app/Controllers/subscriptionController.php
  app/Models/Category.php
  app/Models/CategoryDAO.php
  app/Models/Context.php
  app/Models/FeedDAO.php
  app/Models/TagDAO.php
  app/Models/UserQuery.php
  app/Models/View.php
  app/Models/ViewJavascript.php
  app/Models/ViewStats.php
  app/Services/ImportService.php
  p/api/query.php
  tests/app/Models/CategoryTest.php
  tests/app/Models/UserQueryTest.php
Labels: Critical :skull_and_crossbones:, Bug (confirmed) 🐞

#7158 Fix access to manifest
  .htaccess.dist
  p/.htaccess
  p/themes/.htaccess
Labels: Security :shield:, Bug (confirmed) 🐞

#7162 Improved: link back to rss feeds
  app/i18n/cs/gen.php
  app/i18n/de/gen.php
  app/i18n/el/gen.php
  app/i18n/en-us/gen.php
  app/i18n/en/gen.php
  app/i18n/es/gen.php
  app/i18n/fa/gen.php
  app/i18n/fi/gen.php
  app/i18n/fr/gen.php
  app/i18n/he/gen.php
  app/i18n/hu/gen.php
  app/i18n/id/gen.php
  app/i18n/it/gen.php
  app/i18n/ja/gen.php
  app/i18n/ko/gen.php
  app/i18n/lv/gen.php
  app/i18n/nl/gen.php
  app/i18n/oc/gen.php
  app/i18n/pl/gen.php
  app/i18n/pt-br/gen.php
  app/i18n/ru/gen.php
  app/i18n/sk/gen.php
  app/i18n/tr/gen.php
  app/i18n/zh-cn/gen.php
  app/i18n/zh-tw/gen.php
  app/layout/aside_configure.phtml
  app/layout/aside_subscription.phtml
  app/views/auth/index.phtml
  app/views/configure/archiving.phtml
  app/views/configure/display.phtml
  app/views/configure/integration.phtml
  app/views/configure/privacy.phtml
  app/views/configure/queries.phtml
  app/views/configure/reading.phtml
  app/views/configure/shortcut.phtml
  app/views/configure/system.phtml
  app/views/extension/index.phtml
  app/views/importExport/index.phtml
  app/views/index/about.phtml
  app/views/index/logs.phtml
  app/views/index/tos.phtml
  app/views/stats/idle.phtml
  app/views/stats/index.phtml
  app/views/stats/repartition.phtml
  app/views/subscription/add.phtml
  app/views/subscription/bookmarklet.phtml
  app/views/subscription/index.phtml
  app/views/tag/index.phtml
  app/views/update/apply.phtml
  app/views/update/checkInstall.phtml
  app/views/update/index.phtml
  app/views/user/manage.phtml
  app/views/user/profile.phtml
Labels: UI :art:
