Repository FreshRSS/FreshRSS, pull requests merged in 2024-05, with the labels that each got.

#6402 Docs: hidden configs
  docs/en/admins/01_Index.md
  docs/en/admins/17_configs_not_ui.md
Labels: Documentation :books:

#6401 Docker: Traefik 3.0
  Docker/freshrss/docker-compose-proxy.yml
Labels: Documentation :books:, Docker

#6423 Fix CSS selector preview
  app/Controllers/feedController.php
Labels: Bug (confirmed) 🐞

#6426 Fix CSS selector encoding
  app/Controllers/feedController.php
  app/Models/Entry.php
Labels: Bug (confirmed) 🐞

#6435 Fix individual OMPL feed export
  app/Controllers/indexController.php
  app/Models/Context.php
Labels: Bug (confirmed) 🐞

#6444 Fixed: clickable link block
  app/views/helpers/index/normal/entry_header.phtml
  p/themes/Alternative-Dark/adark.css
  p/themes/Alternative-Dark/adark.rtl.css
  p/themes/Dark/dark.css
  p/themes/Dark/dark.rtl.css
  p/themes/Nord/nord.css
  p/themes/Nord/nord.rtl.css
  p/themes/Pafat/pafat.css
  p/themes/Pafat/pafat.rtl.css
  p/themes/base-theme/frss.css
  p/themes/base-theme/frss.rtl.css
Labels: UI :art:, UX

#6445 Improved: side navigation headlines
  p/themes/Ansum/_sidebar.scss
  p/themes/Ansum/ansum.css
  p/themes/Ansum/ansum.rtl.css
  p/themes/Dark/dark.css
  p/themes/Dark/dark.rtl.css
  p/themes/Mapco/_sidebar.scss
  p/themes/Mapco/mapco.css
  p/themes/Mapco/mapco.rtl.css
  p/themes/Nord/nord.css
  p/themes/Nord/nord.rtl.css
  p/themes/Origine/origine.css
  p/themes/Origine/origine.rtl.css
  p/themes/Pafat/pafat.css
  p/themes/Pafat/pafat.rtl.css
  p/themes/base-theme/frss.css
  p/themes/base-theme/frss.rtl.css
Labels: UI :art:, Theme

#6452 Fix: click on feed title
  p/scripts/main.js
Labels: Important :fire:, Bug (confirmed) 🐞

#6450 Fix SQLite imports produced before FreshRSS 1.20.0
  app/Models/DatabaseDAO.php
  app/Models/FeedDAO.php
Labels: Bug (confirmed) 🐞

#6279 Auto-update 5038
  app/Models/DatabaseDAO.php
  app/SQL/install.sql.mysql.php
  app/SQL/install.sql.pgsql.php
  lib/Minz/ModelPdo.php
Labels: Update action :floppy_disk:

#6459 PHPStan 1.11 + minor update dev dependencies
  app/Controllers/updateController.php
  app/Models/Feed.php
  app/Models/TagDAO.php
  app/views/update/apply.phtml
  cli/CliOptionsParser.php
  cli/reconfigure.php
  composer.json
  composer.lock
  lib/Minz/Configuration.php
  lib/Minz/Dispatcher.php
  lib/Minz/Pdo.php
  lib/Minz/View.php
  lib/http-conditional.php
  lib/lib_rss.php
  package-lock.json
  package.json
Labels: System care

#6464 Improved the Hungarian translation
  app/i18n/hu/admin.php
  app/i18n/hu/conf.php
  app/i18n/hu/feedback.php
  app/i18n/hu/gen.php
  app/i18n/hu/index.php
  app/i18n/hu/install.php
  app/i18n/hu/sub.php
  app/i18n/hu/user.php
Labels: I18n :earth_africa:

#6467 [i18n] Russian translation
  app/i18n/ru/admin.php
  app/i18n/ru/conf.php
  app/i18n/ru/feedback.php
  app/i18n/ru/gen.php
  app/i18n/ru/index.php
  app/i18n/ru/sub.php
Labels: I18n :earth_africa:

#6471 Fix spanish language
  app/i18n/es/admin.php
  app/i18n/es/conf.php
  app/i18n/es/feedback.php
  app/i18n/es/gen.php
  app/i18n/es/index.php
  app/i18n/es/sub.php
Labels: I18n :earth_africa:

#6441 OPML export: Link to documentation
  app/i18n/de/sub.php
  app/i18n/el/sub.php
  app/i18n/en-us/sub.php
  app/i18n/en/sub.php
  app/i18n/es/sub.php
  app/i18n/fa/sub.php
  app/i18n/fr/sub.php
  app/i18n/he/sub.php
  app/i18n/hu/sub.php
  app/i18n/id/sub.php
  app/i18n/it/sub.php
  app/i18n/ja/sub.php
  app/i18n/ko/sub.php
  app/i18n/lv/sub.php
  app/i18n/nl/sub.php
  app/i18n/oc/sub.php
  app/i18n/pl/sub.php
  app/i18n/pt-br/sub.php
  app/i18n/ru/sub.php
  app/i18n/sk/sub.php
  app/i18n/tr/sub.php
  app/i18n/zh-cn/sub.php
  app/i18n/zh-tw/sub.php
Labels: Documentation :books:

#6486 fixed: hover over title while having the navigation buttons in mobile view
  p/themes/base-theme/frss.css
  p/themes/base-theme/frss.rtl.css
Labels: UI :art:

#6489 Fix broken links on README
  README.md
Labels: Documentation :books:, API :handshake:

#6492 Fix HTTP GET curl options
  app/Models/Entry.php
  app/Models/Feed.php
  lib/favicons.php
  lib/lib_rss.php
Labels: Bug (confirmed) 🐞

#6496 Better git error messages
  app/Controllers/updateController.php
Labels: Update action :floppy_disk:

#6504 Fixed: CZ language string
  app/i18n/cz/sub.php
Labels: I18n :earth_africa:

#6506 upd: Update Turkish translation
  app/i18n/tr/conf.php
  app/i18n/tr/sub.php
Labels: I18n :earth_africa:

#6505 Fixed: drag&drop Sharing/User Query
  p/scripts/draggable.js
Labels: Bug (confirmed) 🐞

#6508 Fixed: subscr. mgmg drag&drop
  p/scripts/category.js
Labels: Bug (confirmed) 🐞

#6513 Fix update git version
  app/Controllers/updateController.php
Labels: Update action :floppy_disk:, Bug (confirmed) 🐞

#6519 Improved: Button to export OMPL of a category
  app/views/helpers/category/update.phtml
  app/views/helpers/feed/update.phtml
Labels: UI :art:
