Repository FreshRSS/FreshRSS, pull requests merged in 2024-06, with the labels that each got.

#6543 Fix attributeBoolean
  app/Controllers/feedController.php
  app/Models/AttributesTrait.php
  app/Models/Entry.php
  app/views/helpers/feed/update.phtml
Labels: Bug (confirmed) 🐞

#6477 Docker Alpine 3.20
  .devcontainer/Dockerfile
  Docker/Dockerfile-Alpine
Labels: Docker

#6485 Improved: Nav buttons as buttons
  app/i18n/cz/gen.php
  app/i18n/de/gen.php
  app/i18n/el/gen.php
  app/i18n/en-us/gen.php
  app/i18n/en/gen.php
  app/i18n/es/gen.php
  app/i18n/fa/gen.php
  app/i18n/fr/gen.php
  app/i18n/he/gen.php
  app/i18n/hu/gen.php
  app/i18n/id/gen.php
  app/i18n/it/gen.php
  app/i18n/ja/gen.php
  app/i18n/ko/gen.php
  app/i18n/lv/gen.php
  app/i18n/nl/gen.php
  app/i18n/oc/gen.php
  app/i18n/pl/gen.php
  app/i18n/pt-br/gen.php
  app/i18n/ru/gen.php
  app/i18n/sk/gen.php
  app/i18n/tr/gen.php
  app/i18n/zh-cn/gen.php
  app/i18n/zh-tw/gen.php
  app/layout/nav_entries.phtml
  p/themes/Alternative-Dark/adark.css
  p/themes/Alternative-Dark/adark.rtl.css
  p/themes/Ansum/_layout.scss
  p/themes/Ansum/_mobile.scss
  p/themes/Ansum/ansum.css
  p/themes/Ansum/ansum.rtl.css
  p/themes/Flat/flat.css
  p/themes/Flat/flat.rtl.css
  p/themes/Mapco/_layout.scss
  p/themes/Mapco/_mobile.scss
  p/themes/Mapco/mapco.css
  p/themes/Mapco/mapco.rtl.css
  p/themes/Nord/nord.css
  p/themes/Nord/nord.rtl.css
  p/themes/Origine/origine.css
  p/themes/Origine/origine.rtl.css
  p/themes/Pafat/pafat.css
  p/themes/Pafat/pafat.rtl.css
  p/themes/Swage/swage.css
  p/themes/Swage/swage.rtl.css
  p/themes/Swage/swage.scss
  p/themes/base-theme/base.css
  p/themes/base-theme/base.rtl.css
  p/themes/base-theme/frss.css
  p/themes/base-theme/frss.rtl.css
Labels: UI :art:, a11y

#6267 Add core extensions: UserCSS, UserJS
  docs/en/developers/03_Backend/05_Extensions.md
  docs/en/users/05_Configuration.md
  docs/fr/developers/03_Backend/05_Extensions.md
  docs/i18n/freshrss.fr.po
  docs/i18n/templates/freshrss.pot
  lib/Minz/Extension.php
  lib/core-extensions/UserCSS/configure.phtml
  lib/core-extensions/UserCSS/extension.php
  lib/core-extensions/UserCSS/i18n/de/ext.php
  lib/core-extensions/UserCSS/i18n/en/ext.php
  lib/core-extensions/UserCSS/i18n/fr/ext.php
  lib/core-extensions/UserCSS/i18n/ja/ext.php
  lib/core-extensions/UserCSS/metadata.json
  lib/core-extensions/UserJS/configure.phtml
  lib/core-extensions/UserJS/extension.php
  lib/core-extensions/UserJS/i18n/de/ext.php
  lib/core-extensions/UserJS/i18n/en/ext.php
  lib/core-extensions/UserJS/i18n/fr/ext.php
  lib/core-extensions/UserJS/i18n/ja/ext.php
  lib/core-extensions/UserJS/metadata.json
Labels: Extension :electric_plug:

#6240 Empty title guid or first words
  app/Models/Entry.php
  app/views/configure/reading.phtml
  constants.php
Labels: View, UX

#6514 Fix code for Czech language
  .typos.toml
  app/i18n/cs/admin.php
  app/i18n/cs/conf.php
  app/i18n/cs/feedback.php
  app/i18n/cs/gen.php
  app/i18n/cs/index.php
  app/i18n/cs/install.php
  app/i18n/cs/sub.php
  app/i18n/cs/user.php
  app/i18n/de/gen.php
  app/i18n/el/gen.php
  app/i18n/en-us/gen.php
  app/i18n/en/gen.php
  app/i18n/es/gen.php
  app/i18n/fa/gen.php
  app/i18n/fr/gen.php
  app/i18n/he/gen.php
  app/i18n/hu/gen.php
  app/i18n/id/gen.php
  app/i18n/it/gen.php
  app/i18n/ja/gen.php
  app/i18n/ko/gen.php
  app/i18n/lv/gen.php
  app/i18n/nl/gen.php
  app/i18n/oc/gen.php
  app/i18n/pl/gen.php
  app/i18n/pt-br/gen.php
  app/i18n/ru/gen.php
  app/i18n/sk/gen.php
  app/i18n/tr/gen.php
  app/i18n/zh-cn/gen.php
  app/i18n/zh-tw/gen.php
  docs/en/users/05_Configuration.md
  docs/fr/users/05_Configuration.md
  docs/i18n/freshrss.fr.po
  docs/i18n/templates/freshrss.pot
Labels: I18n :earth_africa:

#6548 Fix broken cron regression 6541
  app/Models/View.php
  app/views/index/rss.phtml
Labels: Critical :skull_and_crossbones:

#5582 Default dark mode to auto
  app/Controllers/configureController.php
  app/i18n/cs/conf.php
  app/i18n/de/conf.php
  app/i18n/el/conf.php
  app/i18n/en-us/conf.php
  app/i18n/en/conf.php
  app/i18n/es/conf.php
  app/i18n/fa/conf.php
  app/i18n/fr/conf.php
  app/i18n/he/conf.php
  app/i18n/hu/conf.php
  app/i18n/id/conf.php
  app/i18n/it/conf.php
  app/i18n/ja/conf.php
  app/i18n/ko/conf.php
  app/i18n/lv/conf.php
  app/i18n/nl/conf.php
  app/i18n/oc/conf.php
  app/i18n/pl/conf.php
  app/i18n/pt-br/conf.php
  app/i18n/ru/conf.php
  app/i18n/sk/conf.php
  app/i18n/tr/conf.php
  app/i18n/zh-cn/conf.php
  app/i18n/zh-tw/conf.php
  app/views/configure/display.phtml
  config-user.default.php
Labels: Theme

#6544 Pass PHPStan level 9
  app/Controllers/apiController.php
  app/Controllers/authController.php
  app/Controllers/configureController.php
  app/Controllers/entryController.php
  app/Controllers/feedController.php
  app/Controllers/importExportController.php
  app/Models/DatabaseDAO.php
  app/Models/DatabaseDAOPGSQL.php
  app/Models/DatabaseDAOSQLite.php
  app/Models/Entry.php
  app/Models/EntryDAO.php
  app/Models/Feed.php
  app/Models/ReadingMode.php
  app/Models/UserConfiguration.php
  app/Models/UserQuery.php
  app/Services/ImportService.php
  app/layout/layout.phtml
  app/views/helpers/feed/update.phtml
  app/views/helpers/index/article.phtml
  app/views/helpers/index/normal/entry_bottom.phtml
  app/views/helpers/index/normal/entry_header.phtml
  app/views/helpers/stream-footer.phtml
  app/views/javascript/actualize.phtml
  app/views/user/profile.phtml
  composer.lock
  lib/Minz/Helper.php
  lib/Minz/Model.php
  lib/Minz/Request.php
  lib/Minz/Url.php
  lib/favicons.php
  lib/lib_rss.php
  p/api/fever.php
  p/api/greader.php
  p/api/pshb.php
  p/api/query.php
  phpstan-next.neon
  phpstan.neon
  tests/app/Models/SearchTest.php
Labels: System care

#6225 fix broken sharing services (part 2): delete Blogotext
  app/i18n/cs/conf.php
  app/i18n/cs/gen.php
  app/i18n/de/conf.php
  app/i18n/de/gen.php
  app/i18n/el/conf.php
  app/i18n/el/gen.php
  app/i18n/en-us/conf.php
  app/i18n/en-us/gen.php
  app/i18n/en/conf.php
  app/i18n/en/gen.php
  app/i18n/es/conf.php
  app/i18n/es/gen.php
  app/i18n/fa/conf.php
  app/i18n/fa/gen.php
  app/i18n/fr/conf.php
  app/i18n/fr/gen.php
  app/i18n/he/conf.php
  app/i18n/he/gen.php
  app/i18n/hu/conf.php
  app/i18n/hu/gen.php
  app/i18n/id/conf.php
  app/i18n/id/gen.php
  app/i18n/it/conf.php
  app/i18n/it/gen.php
  app/i18n/ja/conf.php
  app/i18n/ja/gen.php
  app/i18n/ko/conf.php
  app/i18n/ko/gen.php
  app/i18n/lv/conf.php
  app/i18n/lv/gen.php
  app/i18n/nl/conf.php
  app/i18n/nl/gen.php
  app/i18n/oc/conf.php
  app/i18n/oc/gen.php
  app/i18n/pl/conf.php
  app/i18n/pl/gen.php
  app/i18n/pt-br/conf.php
  app/i18n/pt-br/gen.php
  app/i18n/ru/conf.php
  app/i18n/ru/gen.php
  app/i18n/sk/conf.php
  app/i18n/sk/gen.php
  app/i18n/tr/conf.php
  app/i18n/tr/gen.php
  app/i18n/zh-cn/conf.php
  app/i18n/zh-cn/gen.php
  app/i18n/zh-tw/conf.php
  app/i18n/zh-tw/gen.php
  app/shares.php
  docs/en/users/08_sharing_services.md
Labels: deprecated

#6304 Sticky buttons
  p/themes/Alternative-Dark/adark.css
  p/themes/Alternative-Dark/adark.rtl.css
  p/themes/Dark/dark.css
  p/themes/Dark/dark.rtl.css
  p/themes/Flat/flat.css
  p/themes/Flat/flat.rtl.css
  p/themes/Nord/nord.css
  p/themes/Nord/nord.rtl.css
  p/themes/Origine/origine.css
  p/themes/Origine/origine.rtl.css
  p/themes/Pafat/pafat.css
  p/themes/Pafat/pafat.rtl.css
  p/themes/Swage/swage.css
  p/themes/Swage/swage.rtl.css
  p/themes/Swage/swage.scss
  p/themes/base-theme/frss.css
  p/themes/base-theme/frss.rtl.css
Labels: UI :art:, UX

#6297 Reading view: action icons position
  CREDITS.md
  app/Controllers/configureController.php
  app/Models/UserConfiguration.php
  app/i18n/cs/conf.php
  app/i18n/de/conf.php
  app/i18n/el/conf.php
  app/i18n/en-us/conf.php
  app/i18n/en/conf.php
  app/i18n/es/conf.php
  app/i18n/fa/conf.php
  app/i18n/fr/conf.php
  app/i18n/he/conf.php
  app/i18n/hu/conf.php
  app/i18n/id/conf.php
  app/i18n/it/conf.php
  app/i18n/ja/conf.php
  app/i18n/ko/conf.php
  app/i18n/lv/conf.php
  app/i18n/nl/conf.php
  app/i18n/oc/conf.php
  app/i18n/pl/conf.php
  app/i18n/pt-br/conf.php
  app/i18n/ru/conf.php
  app/i18n/ru/sub.php
  app/i18n/sk/conf.php
  app/i18n/tr/conf.php
  app/i18n/zh-cn/conf.php
  app/i18n/zh-tw/conf.php
  app/views/configure/reading.phtml
  app/views/helpers/index/article.phtml
  config-user.default.php
  p/themes/base-theme/frss.css
  p/themes/base-theme/frss.rtl.css
Labels: UI :art:

#6555 Sticky Footer Regression dark mode
  p/themes/Origine/origine.css
  p/themes/Origine/origine.rtl.css
Labels: UI :art:

#6564 Improve Japanese translation (TODO/DIRTY commented, swayed notation, and unnatural wording)
  app/i18n/ja/admin.php
  app/i18n/ja/conf.php
  app/i18n/ja/feedback.php
  app/i18n/ja/gen.php
  app/i18n/ja/index.php
  app/i18n/ja/install.php
  app/i18n/ja/sub.php
Labels: I18n :earth_africa:

#6593 Add quiet option to cli/db-backup.php
  app/Models/DatabaseDAO.php
  cli/README.md
  cli/db-backup.php
Labels: CLI

#6395 New: Sharing articles from the article title line
  app/Controllers/configureController.php
  app/Models/UserConfiguration.php
  app/views/configure/display.phtml
  app/views/helpers/index/normal/entry_bottom.phtml
  app/views/helpers/index/normal/entry_header.phtml
  app/views/helpers/index/normal/entry_share_menu.phtml
  config-user.default.php
  p/scripts/main.js
  p/themes/base-theme/frss.css
  p/themes/base-theme/frss.rtl.css
Labels: UI :art:, UX
