Repository FreshRSS/FreshRSS, pull requests merged in 2024-07, with the labels that each got.

#6612 Fix for disabled logged-in users
  app/Models/Auth.php
  p/api/query.php
Labels: Security :shield:

#6614 Update composer shfmt typos
  .github/workflows/tests.yml
  CONTRIBUTING.md
  Makefile
  cli/manipulate.translation.php
  docs/en/admins/07_LinuxUpdate.md
Labels: System care

#6617 Fixing dropdown menu for labels
  app/layout/aside_feed.phtml
Labels: Bug (confirmed) 🐞

#6624 Remove dependency to exif extension
  lib/favicons.php
  p/api/fever.php
  p/f.php
Labels: API :handshake:, Bug (confirmed) 🐞

#6631 JSON Dot Notation allow string conversion
  app/Utils/dotNotationUtil.php
Labels: Bug (confirmed) 🐞

#6634 Improve Spanish translations: Add missing entries and fix typos
  app/i18n/es/admin.php
  app/i18n/es/conf.php
  app/i18n/es/feedback.php
  app/i18n/es/gen.php
  app/i18n/es/index.php
  app/i18n/es/sub.php
Labels: I18n :earth_africa:

#6637 Re-enable OPCache for PHP 8.4-alpha2
  Docker/Dockerfile-Newest
Labels: Docker

#6641 Fix: feed dropdown
  p/scripts/main.js
Labels: UI :art:

#6651 Improve feed sidebar: main stream, favorites, important
  app/layout/aside_feed.phtml
  p/themes/Origine/origine.css
  p/themes/Origine/origine.rtl.css
Labels: UX

#6659 Add default API CORS HTTP Headers
  p/api/greader.php
  p/api/query.php
Labels: Security :shield:, API :handshake:

#6661 Strong type array parameter helper
  app/Controllers/entryController.php
  lib/Minz/Request.php
Labels: Extension :electric_plug:

#6663 Fix markAsReadUponGone regression
  app/Controllers/feedController.php
  app/Models/Feed.php
  app/Models/FeedDAO.php
Labels: Important :fire:, Bug (confirmed) 🐞

#6671 Fix muted feeds for WebSub
  app/Controllers/feedController.php
Labels: Bug (confirmed) 🐞
