Repository FreshRSS/FreshRSS, pull requests merged in 2025-04, with the labels that each got.

#7471 Add CSP to favicons
  p/f.php
Labels: Security :shield:

#7468 Fix escaping of tag search
  app/Controllers/tagController.php
  app/views/helpers/index/normal/entry_bottom.phtml
  app/views/helpers/index/tags.phtml
Labels: Search :mag:, Bug (confirmed) 🐞

#6303 Referrer-Policy: same-origin
  app/install.php
  lib/lib_rss.php
  p/.htaccess
  p/ext.php
Labels: Security :shield:

#7478 Partial revert Referrer-Policy
  p/.htaccess
Labels: Security :shield:

#7474 Restrict valid paths in ext.php for extensions
  p/ext.php
Labels: Extension :electric_plug:, Security :shield:

#7477 Make update URL readonly
  app/Controllers/configureController.php
  app/Models/SystemConfiguration.php
  app/views/configure/system.phtml
Labels: Update action :floppy_disk:, Security :shield:

#7464 Update 10_filter.md to provide detailed explanations of the time syntax.
  docs/en/users/10_filter.md
  docs/fr/users/03_Main_view.md
Labels: Documentation :books:, Search :mag:

#7479 Fix ext.php: Restrict valid paths in ext.php for extensions
  p/ext.php
Labels: Extension :electric_plug:, Security :shield:

#7488 Pass phpstan-strict-rules 2.0.4
  app/Models/CategoryDAO.php
  app/Models/EntryDAO.php
  app/Models/FeedDAO.php
  app/Models/TagDAO.php
  composer.json
  composer.lock
Labels: System care, php

#7490 fix mapco/ansum theme
  p/themes/Ansum/_components.css
  p/themes/Ansum/_components.rtl.css
  p/themes/Ansum/ansum.css
  p/themes/Ansum/ansum.rtl.css
  p/themes/Mapco/_components.css
  p/themes/Mapco/_components.rtl.css
  p/themes/Mapco/mapco.css
  p/themes/Mapco/mapco.rtl.css
Labels: Theme 🖌

#7491 Add :focus style to .dropdown-menu .item
  p/themes/Alternative-Dark/adark.css
  p/themes/Alternative-Dark/adark.rtl.css
  p/themes/Dark/dark.css
  p/themes/Dark/dark.rtl.css
  p/themes/Flat/flat.css
  p/themes/Flat/flat.rtl.css
  p/themes/Nord/nord.css
  p/themes/Nord/nord.rtl.css
  p/themes/Origine/origine.css
  p/themes/Origine/origine.rtl.css
  p/themes/Pafat/pafat.css
  p/themes/Pafat/pafat.rtl.css
Labels: UI :art:, a11y

#7489 Use HTTP POST for logout
  app/Controllers/authController.php
  app/layout/aside_configure.phtml
  app/layout/header.phtml
  app/layout/simple.phtml
  p/themes/Ansum/_sidebar.scss
  p/themes/Ansum/ansum.css
  p/themes/Ansum/ansum.css.map
  p/themes/Ansum/ansum.rtl.css
  p/themes/Flat/flat.css
  p/themes/Flat/flat.rtl.css
  p/themes/Mapco/_sidebar.scss
  p/themes/Mapco/mapco.css
  p/themes/Mapco/mapco.css.map
  p/themes/Mapco/mapco.rtl.css
  p/themes/Nord/nord.css
  p/themes/Nord/nord.rtl.css
  p/themes/Origine/origine.css
  p/themes/Origine/origine.rtl.css
  p/themes/Pafat/pafat.css
  p/themes/Pafat/pafat.rtl.css
  p/themes/Swage/swage.css
  p/themes/Swage/swage.css.map
  p/themes/Swage/swage.rtl.css
  p/themes/Swage/swage.scss
  p/themes/base-theme/base.css
  p/themes/base-theme/base.rtl.css
  p/themes/base-theme/frss.css
  p/themes/base-theme/frss.rtl.css
Labels: Security :shield:

#7494 Disallow iframe srcdoc for now
  lib/lib_rss.php
Labels: Security :shield:

#7496 Web scraping forbid security headers in cURL
  app/views/helpers/feed/update.phtml
  lib/lib_rss.php
Labels: Security :shield:, Web Scraping

#7495 Secure serving of user files from extensions
  app/Controllers/extensionController.php
  app/views/extension/serve.phtml
  docs/en/developers/03_Backend/05_Extensions.md
  docs/fr/developers/03_Backend/05_Extensions.md
  lib/Minz/Extension.php
  lib/core-extensions/UserCSS/extension.php
  lib/core-extensions/UserCSS/metadata.json
  lib/core-extensions/UserJS/extension.php
  lib/core-extensions/UserJS/metadata.json
  p/ext.php
Labels: Security :shield:, Bug (confirmed) 🐞

#7499 Fix regression ext.php
  p/ext.php
Labels: Extension :electric_plug:, Bug (confirmed) 🐞

#7506 SimplePie forbid formaction attribute
  lib/lib_rss.php
Labels: SimplePie :cake:, Security :shield:

#7508 Update Polish translation
  app/i18n/pl/admin.php
  app/i18n/pl/conf.php
  app/i18n/pl/feedback.php
  app/i18n/pl/gen.php
  app/i18n/pl/index.php
  app/i18n/pl/install.php
  app/i18n/pl/sub.php
Labels: I18n :earth_africa:

#7515 SimplePie: Fix support for feeds with XML preample + DTD
  lib/composer.json
  lib/simplepie/simplepie/src/Parser.php
Labels: SimplePie :cake:

#7505 Improve favicon hash
  app/Models/Feed.php
Labels: Security :shield:

#7526 Themes fix CSS .as-link
  p/themes/Alternative-Dark/adark.css
  p/themes/Alternative-Dark/adark.rtl.css
  p/themes/Ansum/_sidebar.scss
  p/themes/Ansum/ansum.css
  p/themes/Ansum/ansum.rtl.css
  p/themes/Dark-pink/pinkdark.css
  p/themes/Dark-pink/pinkdark.rtl.css
  p/themes/Dark/dark.css
  p/themes/Dark/dark.rtl.css
  p/themes/Flat/flat.css
  p/themes/Flat/flat.rtl.css
  p/themes/Mapco/_sidebar.scss
  p/themes/Mapco/mapco.css
  p/themes/Mapco/mapco.rtl.css
  p/themes/Nord/nord.css
  p/themes/Nord/nord.rtl.css
  p/themes/Origine/origine.css
  p/themes/Origine/origine.rtl.css
  p/themes/Pafat/pafat.css
  p/themes/Pafat/pafat.rtl.css
  p/themes/Swage/swage.css
  p/themes/Swage/swage.rtl.css
  p/themes/Swage/swage.scss
  p/themes/base-theme/base.css
  p/themes/base-theme/base.rtl.css
  p/themes/base-theme/frss.css
  p/themes/base-theme/frss.rtl.css
Labels: Theme 🖌

#7528 HTTP Auth disallow multiple headers
  lib/lib_rss.php
Labels: Security :shield:
