Repository FreshRSS/FreshRSS, pull requests merged in 2025-03, with the labels that each got.

#7394 Fix dynamic OPML
  app/Models/Category.php
  app/Services/ImportService.php
Labels: Bug (confirmed) 🐞

#7401 docs: add link to freshrss_python_api
  docs/en/developers/06_Fever_API.md
Labels: Documentation :books:, API :handshake:

#7404 i18n do not translate XPath code
  app/i18n/es/sub.php
  app/i18n/fa/sub.php
  app/i18n/sk/user.php
Labels: Documentation :books:, I18n :earth_africa:, XPath

#7397 Changelog 1.17.0 forgotten
  CHANGELOG.md
Labels: Documentation :books:, Docker 🐋

#7403 Fix regression cURL HTTP headers
  app/Controllers/feedController.php
  app/Controllers/subscriptionController.php
  lib/composer.json
  lib/simplepie/simplepie/src/File.php
Labels: Critical :skull_and_crossbones:, SimplePie :cake:, Bug (confirmed) 🐞

#7413 improve origine theme
  p/themes/Origine/origine.css
  p/themes/Origine/origine.rtl.css
Labels: Theme 🖌

#7271 feat: Add one-click deploy to Zeabur button on README.md
  README.fr.md
  README.md
Labels: Documentation :books:

#7414 Implement JSON string concatenation with & operator
  app/Utils/dotNotationUtil.php
  docs/en/users/11_website_scraping.md
  tests/app/Utils/dotNotationUtilTest.php
Labels: Web Scraping

#7432 fr update
  app/i18n/fr/admin.php
  app/i18n/fr/conf.php
Labels: I18n :earth_africa:

#7434 SimplePie sync upstream
  CHANGELOG.md
  lib/composer.json
Labels: SimplePie :cake:

#7431 Update PHPStan 2.1.8
  composer.lock
  lib/Minz/Helper.php
  package-lock.json
Labels: System care

#7448 Update 02_Prerequisites.md
  docs/en/admins/02_Prerequisites.md
  docs/fr/users/01_Installation.md
Labels: Documentation :books:

#7430 Fix CLI flag parsing
  cli/CliOptionsParser.php
  cli/check.translation.php
  cli/create-user.php
  cli/db-backup.php
  cli/db-restore.php
  cli/import-sqlite-for-user.php
  cli/manipulate.translation.php
  cli/user-info.php
  tests/cli/CliOptionsParserTest.php
Labels: Bug (confirmed) 🐞

#7168 Fix: 6262: Scroll bar if default font-size is smaller than 16px
  p/themes/Alternative-Dark/adark.css
  p/themes/Alternative-Dark/adark.rtl.css
  p/themes/Flat/flat.css
  p/themes/Flat/flat.rtl.css
  p/themes/Nord/nord.css
  p/themes/Nord/nord.rtl.css
  p/themes/Origine-compact/origine-compact.css
  p/themes/Origine-compact/origine-compact.rtl.css
  p/themes/Origine/origine.css
  p/themes/Origine/origine.rtl.css
  p/themes/Swage/swage.css
  p/themes/Swage/swage.rtl.css
  p/themes/Swage/swage.scss
  p/themes/base-theme/base.css
  p/themes/base-theme/base.rtl.css
Labels: UI :art:

#7426 Clarify MINZ usage
  README.fr.md
  README.md
  app/i18n/cs/index.php
  app/i18n/de/index.php
  app/i18n/el/index.php
  app/i18n/en-us/index.php
  app/i18n/en/index.php
  app/i18n/es/index.php
  app/i18n/fa/index.php
  app/i18n/fi/index.php
  app/i18n/fr/index.php
  app/i18n/he/index.php
  app/i18n/hu/index.php
  app/i18n/id/index.php
  app/i18n/it/index.php
  app/i18n/ja/index.php
  app/i18n/ko/index.php
  app/i18n/lv/index.php
  app/i18n/nl/index.php
  app/i18n/oc/index.php
  app/i18n/pl/index.php
  app/i18n/pt-br/index.php
  app/i18n/pt-pt/index.php
  app/i18n/ru/index.php
  app/i18n/sk/index.php
  app/i18n/tr/index.php
  app/i18n/zh-cn/index.php
  app/i18n/zh-tw/index.php
  app/views/index/about.phtml
Labels: Documentation :books:, I18n :earth_africa:

#7369 Support multiple JSON fragments in HTML+XPath+JSON mode
  app/Models/Feed.php
  app/i18n/cs/sub.php
  app/i18n/de/sub.php
  app/i18n/el/sub.php
  app/i18n/en-us/sub.php
  app/i18n/en/sub.php
  app/i18n/es/sub.php
  app/i18n/fa/sub.php
  app/i18n/fi/sub.php
  app/i18n/fr/sub.php
  app/i18n/he/sub.php
  app/i18n/hu/sub.php
  app/i18n/id/sub.php
  app/i18n/it/sub.php
  app/i18n/ja/sub.php
  app/i18n/ko/sub.php
  app/i18n/lv/sub.php
  app/i18n/nl/sub.php
  app/i18n/oc/sub.php
  app/i18n/pl/sub.php
  app/i18n/pt-br/sub.php
  app/i18n/pt-pt/sub.php
  app/i18n/ru/sub.php
  app/i18n/sk/sub.php
  app/i18n/tr/sub.php
  app/i18n/zh-cn/sub.php
  app/i18n/zh-tw/sub.php
Labels: Web Scraping

#7449 Update bcrypt.js from 2.4.4 to 3.0.2
  .jshintignore
  app/Controllers/authController.php
  app/Controllers/userController.php
  app/Utils/passwordUtil.php
  p/scripts/bcrypt.min.js
  p/scripts/extra.js
  p/scripts/vendor/bcrypt.js
Labels: Security :shield:, javascript
