Repository FreshRSS/FreshRSS, pull requests merged in 2025-07, with the labels that each got.

#7722 Disallow setting non-existent theme
  app/Controllers/configureController.php
  app/Models/Themes.php
Labels: Security :shield:

#7725 fix: interpolate FRESHRSS_INSTALL and FRESHRSS_USER variables
  Docker/entrypoint.sh
Labels: Docker 🐋

#7721 i18n:ID
  app/i18n/id/conf.php
  app/i18n/id/feedback.php
  app/i18n/id/gen.php
  app/i18n/id/index.php
  app/i18n/id/sub.php
Labels: I18n :earth_africa:

#7733 Honor "disable update" on index page
  app/views/update/index.phtml
Labels: Docker 🐋

#7740 DevContainer: Alpine 3.22
  .devcontainer/Dockerfile
Labels: Docker 🐋

#7752 Update chart.js from 3.5.1 to 4.5.0
  app/Controllers/statsController.php
  p/scripts/vendor/chart.min.js
  p/scripts/vendor/chart.umd.min.js
Labels: javascript

#7762 Regenerate cookie ID after logging out
  app/Controllers/authController.php
Labels: Security :shield:

#7761 `before_login_btn` hook + system conf attributes
  app/Controllers/userController.php
  app/Models/Context.php
  app/Models/UserConfiguration.php
  app/views/auth/formLogin.phtml
  app/views/auth/register.phtml
  docs/en/developers/03_Backend/05_Extensions.md
  lib/Minz/Configuration.php
  lib/Minz/ExtensionManager.php
Labels: Extension :electric_plug:

#7753 Implement sudo mode / reauthentication
  app/Controllers/authController.php
  app/Controllers/updateController.php
  app/Controllers/userController.php
  app/Models/Auth.php
  app/Models/SystemConfiguration.php
  app/i18n/cs/gen.php
  app/i18n/de/gen.php
  app/i18n/el/gen.php
  app/i18n/en-us/gen.php
  app/i18n/en/gen.php
  app/i18n/es/gen.php
  app/i18n/fa/gen.php
  app/i18n/fi/gen.php
  app/i18n/fr/gen.php
  app/i18n/he/gen.php
  app/i18n/hu/gen.php
  app/i18n/id/gen.php
  app/i18n/it/gen.php
  app/i18n/ja/gen.php
  app/i18n/ko/gen.php
  app/i18n/lv/gen.php
  app/i18n/nl/gen.php
  app/i18n/oc/gen.php
  app/i18n/pl/gen.php
  app/i18n/pt-br/gen.php
  app/i18n/pt-pt/gen.php
  app/i18n/ru/gen.php
  app/i18n/sk/gen.php
  app/i18n/tr/gen.php
  app/i18n/zh-cn/gen.php
  app/i18n/zh-tw/gen.php
  app/views/auth/reauth.phtml
  config.default.php
  docs/i18n/flags/gen/de.svg
  docs/i18n/flags/gen/id.svg
  lib/core-extensions/UserJS/extension.php
  lib/core-extensions/UserJS/metadata.json
  p/scripts/extra.js
Labels: Security :shield:
